using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.RegularExpressions;

namespace Sustantix.Aip.Licensing.Core
{
    /// <summary>A refused change set: the error code the hosts map to an HTTP status, and the item it concerns.</summary>
    public sealed class ChangeSetException : Exception
    {
        public string Code { get; private set; }
        public ChangeSetException(string code, string message) : base(message) { Code = code; }
    }

    public sealed class ChangeColumn
    {
        public string Name;
        public string Kind;
        public string Attribute;
        public string Target;
        public string Scope;
        public bool Editable;
    }

    public sealed class ChangeEntity
    {
        public string Name;
        public string Label;
        public string Layer;
        public string Table;
        public List<string> Writers;
        public bool Editable;
        public bool Scoped;
        public Dictionary<string, ChangeColumn> Columns;
    }

    /// <summary>The Dataverse change model generated by tools/schema (powerplatform/schema/change-model.json).</summary>
    public sealed class ChangeModel
    {
        public int MaxItems;
        public string Key;
        public string ChangeSetTable;
        public Dictionary<string, ChangeEntity> Entities;
        public Dictionary<string, HashSet<string>> PlatformCodes;

        public static ChangeModel Parse(string json)
        {
            var root = JsonValue.Parse(json);
            var m = new ChangeModel
            {
                MaxItems = int.Parse(root["maxItems"].Text, CultureInfo.InvariantCulture),
                Key = root["key"].AsString(),
                ChangeSetTable = root["changeSetTable"].AsString(),
                Entities = new Dictionary<string, ChangeEntity>(StringComparer.Ordinal),
                PlatformCodes = new Dictionary<string, HashSet<string>>(StringComparer.Ordinal),
            };
            foreach (var e in root["entities"].Items)
            {
                var entity = new ChangeEntity
                {
                    Name = e["name"].AsString(),
                    Label = e["label"].AsString(),
                    Layer = e["layer"].AsString(),
                    Table = e["table"].AsString(),
                    Writers = e["writers"].Items.Select(w => w.AsString()).ToList(),
                    Editable = e["editable"].Bool,
                    Scoped = e["scoped"].Kind == JsonKind.Bool && e["scoped"].Bool,
                    Columns = new Dictionary<string, ChangeColumn>(StringComparer.Ordinal),
                };
                foreach (var c in e["columns"].Items)
                {
                    entity.Columns[c["name"].AsString()] = new ChangeColumn
                    {
                        Name = c["name"].AsString(),
                        Kind = c["kind"].AsString(),
                        Attribute = c["attribute"].AsString(),
                        Target = c["target"].AsString(),
                        Scope = c["scope"].AsString(),
                        Editable = c["editable"].Bool,
                    };
                }
                m.Entities[entity.Name] = entity;
            }
            foreach (var kv in root["platformCodes"].Fields)
                m.PlatformCodes[kv.Key] = new HashSet<string>(kv.Value.Items.Select(x => x.AsString()), StringComparer.Ordinal);
            return m;
        }
    }

    /// <summary>A lookup bound by the target's alternate key (sus_name).</summary>
    public sealed class LookupValue
    {
        public string Table;
        public string Key;
    }

    /// <summary>An amount for a Money attribute; carried as decimal, never as floating point.</summary>
    public sealed class MoneyValue
    {
        public decimal Amount;
    }

    /// <summary>statecode for an is_active change on a master or transaction (0 active, 1 inactive).</summary>
    public sealed class StateValue
    {
        public bool Active;
    }

    public enum OpKind { Create, Update, Delete }

    public sealed class PlannedOp
    {
        public OpKind Kind;
        public string Entity;
        public string Table;
        /// <summary>The business code as the change set addressed it.</summary>
        public string Code;
        /// <summary>The row's alternate-key value in Dataverse (scope/CODE for scoped vocabulary).</summary>
        public string Key;
        public long? RowVersion;
        public Dictionary<string, object> Attributes = new Dictionary<string, object>(StringComparer.Ordinal);
    }

    public sealed class ChangeSetPlan
    {
        public Guid Id;
        public string Source;
        public List<PlannedOp> Ops = new List<PlannedOp>();
    }

    /// <summary>
    /// Validates a change set against the change model and the caller's AIP role and turns it into Dataverse operations,
    /// exactly as aip.apply_change_set does on Supabase: unknown entities or columns, read-only columns, time series,
    /// platform vocabulary, values of the wrong type and missing row versions are refused with the item they concern.
    /// </summary>
    public static class ChangeSetPlanner
    {
        private static readonly Regex DecimalPattern = new Regex(@"^-?\d{1,15}(\.\d{1,6})?$");
        private static readonly Regex DatePattern = new Regex(@"^\d{4}-\d{2}-\d{2}$");
        private static readonly Regex DateTimePattern = new Regex(@"^\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}(:\d{2}(\.\d{1,6})?)?$");
        private static readonly Regex ScopedKey = new Regex(@"^[a-z][a-z0-9_]*:[^:]+$");
        private static readonly Regex RefCode = new Regex(@"^[A-Z0-9][A-Z0-9_-]*$");
        private static readonly string[] Sources = { "grid", "runtime", "agent", "import" };

        public static ChangeSetPlan Plan(string json, ChangeModel model, string role)
        {
            JsonValue root;
            try { root = JsonValue.Parse(json); }
            catch (FormatException e) { throw new ChangeSetException("invalid_json", "the change set is not JSON: " + e.Message); }

            Guid id;
            if (!Guid.TryParse(root["id"].AsString() ?? "", out id)) throw new ChangeSetException("invalid_change_set", "a change set needs a uuid id");
            var source = root["source"].AsString() ?? "grid";
            if (Array.IndexOf(Sources, source) < 0) throw new ChangeSetException("invalid_change_set", "unknown source " + source);
            var items = root["items"];
            if (items.Kind != JsonKind.Array || items.Items.Count < 1 || items.Items.Count > model.MaxItems)
                throw new ChangeSetException("invalid_change_set", "a change set holds 1 to " + model.MaxItems + " items");
            if (role != "planner" && role != "admin") throw new ChangeSetException("forbidden", "only planners and administrators write change sets");

            var plan = new ChangeSetPlan { Id = id, Source = source };
            for (var i = 0; i < items.Items.Count; i++) plan.Ops.Add(PlanItem(items.Items[i], i + 1, model, role));
            return plan;
        }

        private static PlannedOp PlanItem(JsonValue item, int n, ChangeModel model, string role)
        {
            var where = "item " + n;
            ChangeEntity e;
            var entityName = item["entity"].AsString() ?? "";
            if (!model.Entities.TryGetValue(entityName, out e)) throw new ChangeSetException("unknown_entity", where + ": unknown entity " + entityName);
            if (!e.Editable) throw new ChangeSetException("read_only", where + ": " + e.Label + " is written by integrations only");
            if (!e.Writers.Contains(role)) throw new ChangeSetException("forbidden", where + ": your role cannot change " + e.Label);

            var op = item["op"].AsString();
            OpKind kind;
            if (op == "insert") kind = OpKind.Create;
            else if (op == "update") kind = OpKind.Update;
            else if (op == "delete") kind = OpKind.Delete;
            else throw new ChangeSetException("invalid_change_set", where + ": unknown operation " + op);

            var code = (item["code"].AsString() ?? "").Trim();
            if (code.Length < 1 || code.Length > 200) throw new ChangeSetException("invalid_change_set", where + ": a business code is required");
            var key = code;
            string refCode = null;
            if (e.Scoped)
            {
                if (!ScopedKey.IsMatch(code)) throw new ChangeSetException("invalid_code", where + ": " + e.Label + " rows are addressed as scope:CODE");
                var parts = code.Split(':');
                key = parts[0] + "/" + parts[1];
                refCode = parts[1];
            }
            else if (e.Layer == "reference") refCode = code;
            if (refCode != null && kind == OpKind.Create && !RefCode.IsMatch(refCode)) throw new ChangeSetException("invalid_value", where + ": codes are upper-case letters, digits, '-' and '_'");
            if (e.Layer == "reference" && kind != OpKind.Create)
            {
                HashSet<string> platform;
                if (model.PlatformCodes.TryGetValue(e.Name, out platform) && platform.Contains(key))
                    throw new ChangeSetException("forbidden", where + ": " + code + " is a platform code; platform vocabulary changes only with a Sustantix release");
            }

            var planned = new PlannedOp { Kind = kind, Entity = e.Name, Table = e.Table, Code = code, Key = key };
            var version = item["baseVersion"];
            if (kind != OpKind.Create)
            {
                long v;
                if (version.Kind != JsonKind.Number || !long.TryParse(version.Text, NumberStyles.Integer, CultureInfo.InvariantCulture, out v) || v < 1)
                    throw new ChangeSetException("invalid_change_set", where + ": " + op + " needs the row version it was read at");
                planned.RowVersion = v;
            }

            var values = item["values"];
            if (kind == OpKind.Delete)
            {
                if (values.Kind == JsonKind.Object && values.Fields.Count > 0) throw new ChangeSetException("invalid_change_set", where + ": a delete carries no values");
                return planned;
            }
            if (values.Kind != JsonKind.Object && values.Kind != JsonKind.Null) throw new ChangeSetException("invalid_change_set", where + ": values must be an object");
            if (kind == OpKind.Update && (values.Kind != JsonKind.Object || values.Fields.Count == 0)) throw new ChangeSetException("invalid_change_set", where + ": nothing to change");

            if (kind == OpKind.Create)
            {
                planned.Attributes[model.Key] = key;
                if (refCode != null) planned.Attributes["sus_code"] = refCode;
            }
            if (values.Kind == JsonKind.Object)
            {
                foreach (var kv in values.Fields)
                {
                    ChangeColumn c;
                    if (!e.Columns.TryGetValue(kv.Key, out c) || !c.Editable) throw new ChangeSetException("invalid_value", where + ": " + kv.Key + " is not an editable column of " + e.Label);
                    planned.Attributes[c.Attribute] = Convert(c, kv.Value, where);
                }
            }
            return planned;
        }

        private static object Convert(ChangeColumn c, JsonValue v, string where)
        {
            if (v.Kind == JsonKind.Null) return null;
            Func<ChangeSetException> bad = () => new ChangeSetException("invalid_value", where + ": " + c.Name + " cannot be " + v + (c.Kind == "money" || c.Kind == "decimal" ? " (amounts are sent as decimal strings)" : ""));
            switch (c.Kind)
            {
                case "fk":
                case "ref":
                {
                    var code = v.AsString();
                    if (string.IsNullOrWhiteSpace(code) || code.Length > 200) throw bad();
                    return new LookupValue { Table = c.Target, Key = c.Scope != null ? c.Scope + "/" + code : code };
                }
                case "integer":
                {
                    int i;
                    if (v.Kind != JsonKind.Number || !int.TryParse(v.Text, NumberStyles.Integer, CultureInfo.InvariantCulture, out i)) throw bad();
                    return i;
                }
                case "decimal":
                case "money":
                {
                    // Amounts arrive as strings; never accept a JSON number that may already have been through floating point.
                    var s = v.AsString();
                    decimal d;
                    if (s == null || !DecimalPattern.IsMatch(s) || !decimal.TryParse(s, NumberStyles.Number, CultureInfo.InvariantCulture, out d)) throw bad();
                    return c.Kind == "money" ? (object)new MoneyValue { Amount = d } : d;
                }
                case "date":
                {
                    var s = v.AsString();
                    DateTime d;
                    if (s == null || !DatePattern.IsMatch(s) || !DateTime.TryParseExact(s, "yyyy-MM-dd", CultureInfo.InvariantCulture, DateTimeStyles.None, out d)) throw bad();
                    return DateTime.SpecifyKind(d, DateTimeKind.Unspecified);
                }
                case "datetime":
                {
                    var s = v.AsString();
                    DateTime d;
                    if (s == null || !DateTimePattern.IsMatch(s) || !DateTime.TryParse(s.Replace(' ', 'T'), CultureInfo.InvariantCulture, DateTimeStyles.None, out d)) throw bad();
                    return DateTime.SpecifyKind(d, DateTimeKind.Unspecified);
                }
                case "boolean":
                    if (v.Kind != JsonKind.Bool) throw bad();
                    return c.Attribute == "statecode" ? (object)new StateValue { Active = v.Bool } : v.Bool;
                default:
                {
                    var s = v.AsString();
                    if (s == null || s.Length > 4000) throw bad();
                    return s;
                }
            }
        }

        /// <summary>The AIP role a Dataverse user holds through the provisioned security roles.</summary>
        public static string RoleOf(IEnumerable<string> securityRoles)
        {
            var names = new HashSet<string>(securityRoles ?? Enumerable.Empty<string>(), StringComparer.OrdinalIgnoreCase);
            if (names.Contains("Sustantix AIP Administrator") || names.Contains("System Administrator")) return "admin";
            if (names.Contains("Sustantix AIP User")) return "planner";
            return "viewer";
        }
    }
}
