-- Compatibility views rebuild their sheets (generated by tools/schema from the round trip — do not edit by hand).
-- Run after the seed has loaded the tenant below.
\set ON_ERROR_STOP 1
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."ai_alerts_and_rul" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."ai_alerts_and_rul" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'ai_alerts_and_rul: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "alert_id", "asset_id", "plant_id", "asset_tag", "component", "alert_timestamp", "model", "risk_score", "rul_days", "confidence_pct", "risk_tier", "alert_status", "evidence_summary", "data_basis" from aip_compat."ai_alerts_and_rul" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "alert_id", "asset_id", "plant_id", "asset_tag", "component", "alert_timestamp", "model", "risk_score", "rul_days", "confidence_pct", "risk_tier", "alert_status", "evidence_summary", "data_basis" from aip."ai_alerts_and_rul" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'ai_alerts_and_rul: % rebuilt row(s) differ on 14 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."prescriptive_actions" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."prescriptive_actions" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'prescriptive_actions: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "recommendation_id", "alert_id", "asset_id", "asset_tag", "risk_score", "rul_days", "recommended_action", "cost_now", "cost_if_deferred", "cost_avoided", "confidence_pct", "decision_status", "rationale", "plant_id" from aip_compat."prescriptive_actions" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "recommendation_id", "alert_id", "asset_id", "asset_tag", "risk_score", "rul_days", "recommended_action", "cost_now", "cost_if_deferred", "cost_avoided", "confidence_pct", "decision_status", "rationale", "plant_id" from aip."prescriptive_actions" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'prescriptive_actions: % rebuilt row(s) differ on 14 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."work_orders" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."work_orders" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'work_orders: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "work_order_id", "asset_id", "plant_id", "description", "created_date", "sla_due", "sla_hours", "actual_resolution_hours", "sla_result", "source", "estimated_cost", "assigned_technician_id", "assigned_crew", "pm_frequency_days", "pm_due_date", "actual_pm_completion_date", "pm_compliance_tolerance_days", "pm_compliance_result", "pm_overdue_days", "linked_alert_id", "required_part_id", "required_part_qty", "module_id", "data_basis" from aip_compat."work_orders" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "work_order_id", "asset_id", "plant_id", "description", "created_date", "sla_due", "sla_hours", "actual_resolution_hours", "sla_result", "source", "estimated_cost", "assigned_technician_id", "assigned_crew", "pm_frequency_days", "pm_due_date", "actual_pm_completion_date", "pm_compliance_tolerance_days", "pm_compliance_result", "pm_overdue_days", "linked_alert_id", "required_part_id", "required_part_qty", "module_id", "data_basis" from aip."work_orders" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'work_orders: % rebuilt row(s) differ on 24 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."event_log" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."event_log" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'event_log: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "event_id", "incident_id", "plant_id", "asset_id", "event_date_time", "alarm_code", "weather_context", "generation_loss_mwh", "revenue_impact", "event_timestamp", "module_id", "classified_failure" from aip_compat."event_log" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "event_id", "incident_id", "plant_id", "asset_id", "event_date_time", "alarm_code", "weather_context", "generation_loss_mwh", "revenue_impact", "event_timestamp", "module_id", "classified_failure" from aip."event_log" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'event_log: % rebuilt row(s) differ on 12 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."event_root_cause_cases" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."event_root_cause_cases" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'event_root_cause_cases: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "rca_id", "event_id", "plant_id", "asset_id", "oem", "model", "event_time", "cause_name", "reference_id", "verification_method", "confidence_pct", "engineer_approval" from aip_compat."event_root_cause_cases" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "rca_id", "event_id", "plant_id", "asset_id", "oem", "model", "event_time", "cause_name", "reference_id", "verification_method", "confidence_pct", "engineer_approval" from aip."event_root_cause_cases" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'event_root_cause_cases: % rebuilt row(s) differ on 12 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."event_root_cause_evidence" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."event_root_cause_evidence" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'event_root_cause_evidence: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "evidence_id", "event_id", "rca_id", "plant_id", "asset_id", "signal", "actual_value", "peer_baseline", "deviation_pct", "evidence_role", "engineering_interpretation" from aip_compat."event_root_cause_evidence" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "evidence_id", "event_id", "rca_id", "plant_id", "asset_id", "signal", "actual_value", "peer_baseline", "deviation_pct", "evidence_role", "engineering_interpretation" from aip."event_root_cause_evidence" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'event_root_cause_evidence: % rebuilt row(s) differ on 11 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."vision_inspections" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."vision_inspections" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'vision_inspections: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "inspection_id", "plant_id", "inspection_date_time", "inspection_type", "device_id", "panels_inspected", "images_captured", "coverage_pct", "weather", "flight_altitude_m", "inspection_status", "inspector", "asset_id", "data_basis" from aip_compat."vision_inspections" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "inspection_id", "plant_id", "inspection_date_time", "inspection_type", "device_id", "panels_inspected", "images_captured", "coverage_pct", "weather", "flight_altitude_m", "inspection_status", "inspector", "asset_id", "data_basis" from aip."vision_inspections" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'vision_inspections: % rebuilt row(s) differ on 14 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."vision_findings" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."vision_findings" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'vision_findings: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "finding_id", "inspection_id", "plant_id", "asset_id", "detection_mode", "confidence_pct", "estimated_loss_k_wh_day", "annual_revenue_risk", "recommended_action", "work_order_id", "affected_area_sqm", "physical_location", "inspection_date", "inspector", "module_id", "classified_failure", "data_basis" from aip_compat."vision_findings" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "finding_id", "inspection_id", "plant_id", "asset_id", "detection_mode", "confidence_pct", "estimated_loss_k_wh_day", "annual_revenue_risk", "recommended_action", "work_order_id", "affected_area_sqm", "physical_location", "inspection_date", "inspector", "module_id", "classified_failure", "data_basis" from aip."vision_findings" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'vision_findings: % rebuilt row(s) differ on 17 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."warranty_claims" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."warranty_claims" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'warranty_claims: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "claim_id", "warranty_id", "incident_id", "asset_id", "asset_tag", "plant_id", "claim_date", "failure_event_id", "claim_status", "claimed_amount", "approved_amount", "days_open", "evidence_completeness_pct", "notice_deadline", "oem_response_date", "rejection_reason", "next_action", "work_order_id", "module_id", "data_basis" from aip_compat."warranty_claims" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "claim_id", "warranty_id", "incident_id", "asset_id", "asset_tag", "plant_id", "claim_date", "failure_event_id", "claim_status", "claimed_amount", "approved_amount", "days_open", "evidence_completeness_pct", "notice_deadline", "oem_response_date", "rejection_reason", "next_action", "work_order_id", "module_id", "data_basis" from aip."warranty_claims" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'warranty_claims: % rebuilt row(s) differ on 20 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."pm_plans" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."pm_plans" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'pm_plans: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "pm_plan_id", "asset_id", "asset_tag", "task", "frequency_days", "last_done", "next_due", "overdue_days", "standard_labour_hours", "primary_part_id", "required_skill", "plant_id", "data_basis" from aip_compat."pm_plans" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "pm_plan_id", "asset_id", "asset_tag", "task", "frequency_days", "last_done", "next_due", "overdue_days", "standard_labour_hours", "primary_part_id", "required_skill", "plant_id", "data_basis" from aip."pm_plans" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'pm_plans: % rebuilt row(s) differ on 13 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."cbm_assessments" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."cbm_assessments" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'cbm_assessments: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "cbm_assessment_id", "plant_id", "asset_id", "primary_condition", "source_mode", "latest_evidence_time", "freshness_class", "max_deviation_pct", "evidence_count", "corroboration_count", "condition_severity", "risk_context", "evidence_sufficiency_pct", "engineering_physics_fit_pct", "confidence_pct", "condition_state", "recommended_action", "governance_class", "approval_role", "source_module", "source_record_id", "target_view", "work_order_id", "reference_id", "verification_method", "decision_basis" from aip_compat."cbm_assessments" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "cbm_assessment_id", "plant_id", "asset_id", "primary_condition", "source_mode", "latest_evidence_time", "freshness_class", "max_deviation_pct", "evidence_count", "corroboration_count", "condition_severity", "risk_context", "evidence_sufficiency_pct", "engineering_physics_fit_pct", "confidence_pct", "condition_state", "recommended_action", "governance_class", "approval_role", "source_module", "source_record_id", "target_view", "work_order_id", "reference_id", "verification_method", "decision_basis" from aip."cbm_assessments" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'cbm_assessments: % rebuilt row(s) differ on 26 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."cbm_evidence" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."cbm_evidence" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'cbm_evidence: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "cbm_evidence_id", "cbm_assessment_id", "plant_id", "asset_id", "evidence_source", "arrival_mode", "source_module", "target_view", "source_record_id", "observed_time", "signal_name", "observed_value", "baseline_or_peer", "deviation_pct", "evidence_role", "quality_pct", "engineering_interpretation", "freshness_label" from aip_compat."cbm_evidence" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "cbm_evidence_id", "cbm_assessment_id", "plant_id", "asset_id", "evidence_source", "arrival_mode", "source_module", "target_view", "source_record_id", "observed_time", "signal_name", "observed_value", "baseline_or_peer", "deviation_pct", "evidence_role", "quality_pct", "engineering_interpretation", "freshness_label" from aip."cbm_evidence" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'cbm_evidence: % rebuilt row(s) differ on 18 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."msi_spare_requirements" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."msi_spare_requirements" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'msi_spare_requirements: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "requirement_id", "intervention_id", "work_order_id", "decision_id", "plant_id", "asset_id", "part_id", "required_qty", "requirement_status", "requirement_source", "source_record_id" from aip_compat."msi_spare_requirements" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "requirement_id", "intervention_id", "work_order_id", "decision_id", "plant_id", "asset_id", "part_id", "required_qty", "requirement_status", "requirement_source", "source_record_id" from aip."msi_spare_requirements" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'msi_spare_requirements: % rebuilt row(s) differ on 11 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."plan_requirements" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."plan_requirements" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'plan_requirements: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "requirement_id", "intervention_id", "requirement_type", "requirement_ref", "quantity", "mandatory", "source" from aip_compat."plan_requirements" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "requirement_id", "intervention_id", "requirement_type", "requirement_ref", "quantity", "mandatory", "source" from aip."plan_requirements" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'plan_requirements: % rebuilt row(s) differ on 7 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."planned_outages" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."planned_outages" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'planned_outages: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "outage_id", "plant_id", "asset_scope", "capacity_out_mw", "start", "end", "reason", "status", "data_provenance" from aip_compat."planned_outages" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "outage_id", "plant_id", "asset_scope", "capacity_out_mw", "start", "end", "reason", "status", "data_provenance" from aip."planned_outages" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'planned_outages: % rebuilt row(s) differ on 9 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."bess_capacity_tests" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."bess_capacity_tests" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'bess_capacity_tests: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "test_id", "bess_id", "test_date", "test_type", "test_standard", "rated_power_during_test_mw", "discharged_energy_poi_mwh", "charged_energy_poi_mwh", "ac_rte_pct", "soh_energy_pct", "ambient_temp_c", "witness", "result", "data_provenance" from aip_compat."bess_capacity_tests" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "test_id", "bess_id", "test_date", "test_type", "test_standard", "rated_power_during_test_mw", "discharged_energy_poi_mwh", "charged_energy_poi_mwh", "ac_rte_pct", "soh_energy_pct", "ambient_temp_c", "witness", "result", "data_provenance" from aip."bess_capacity_tests" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'bess_capacity_tests: % rebuilt row(s) differ on 14 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."sus_hse_hours" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."sus_hse_hours" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'sus_hse_hours: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "period", "plant_id", "worker_type", "hours_worked", "data_status" from aip_compat."sus_hse_hours" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "period", "plant_id", "worker_type", "hours_worked", "data_status" from aip."sus_hse_hours" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'sus_hse_hours: % rebuilt row(s) differ on 5 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."sus_ghg_activity" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."sus_ghg_activity" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'sus_ghg_activity: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "activity_id", "period", "plant_id", "asset_id", "ghg_scope", "emission_source", "activity_value", "activity_unit", "data_status", "asset_reference_basis", "factor_id", "factor_value", "factor_unit", "factor_resolution" from aip_compat."sus_ghg_activity" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "activity_id", "period", "plant_id", "asset_id", "ghg_scope", "emission_source", "activity_value", "activity_unit", "data_status", "asset_reference_basis", "factor_id", "factor_value", "factor_unit", "factor_resolution" from aip."sus_ghg_activity" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'sus_ghg_activity: % rebuilt row(s) differ on 14 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."sus_water_cleaning" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."sus_water_cleaning" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'sus_water_cleaning: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "cleaning_event_id", "date", "plant_id", "pv_array_id", "pv_array_name", "asset_id", "cleaning_type", "water_m3", "soiling_before_pct", "soiling_after_pct", "mwh_recovered", "water_per_recovered_mwh_l", "data_status", "asset_reference_basis" from aip_compat."sus_water_cleaning" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "cleaning_event_id", "date", "plant_id", "pv_array_id", "pv_array_name", "asset_id", "cleaning_type", "water_m3", "soiling_before_pct", "soiling_after_pct", "mwh_recovered", "water_per_recovered_mwh_l", "data_status", "asset_reference_basis" from aip."sus_water_cleaning" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'sus_water_cleaning: % rebuilt row(s) differ on 14 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."plan_execution_feedback" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."plan_execution_feedback" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'plan_execution_feedback: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "execution_feedback_id", "work_order_id", "plant_id", "asset_id", "planned_start", "actual_start", "planned_duration_hours", "actual_duration_hours", "date_variance_hours", "duration_variance_pct", "conformance_status", "outcome_status", "source" from aip_compat."plan_execution_feedback" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "execution_feedback_id", "work_order_id", "plant_id", "asset_id", "planned_start", "actual_start", "planned_duration_hours", "actual_duration_hours", "date_variance_hours", "duration_variance_pct", "conformance_status", "outcome_status", "source" from aip."plan_execution_feedback" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'plan_execution_feedback: % rebuilt row(s) differ on 13 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."fcst_run" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."fcst_run" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'fcst_run: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "forecast_run_id", "plant_id", "forecast_run_timestamp", "horizon_hours", "forecast_start", "forecast_end", "resolution_minutes", "physics_forecast_mwh", "hybrid_forecast_mwh", "operational_energy_at_risk_mwh", "calibrated_band_pct", "data_trust_pct", "model_reliability_n_mae_pct", "physics_model_id", "residual_model_id", "uncertainty_model_id", "run_status", "source_mode" from aip_compat."fcst_run" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "forecast_run_id", "plant_id", "forecast_run_timestamp", "horizon_hours", "forecast_start", "forecast_end", "resolution_minutes", "physics_forecast_mwh", "hybrid_forecast_mwh", "operational_energy_at_risk_mwh", "calibrated_band_pct", "data_trust_pct", "model_reliability_n_mae_pct", "physics_model_id", "residual_model_id", "uncertainty_model_id", "run_status", "source_mode" from aip."fcst_run" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'fcst_run: % rebuilt row(s) differ on 18 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."plan_outcome_validation" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."plan_outcome_validation" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'plan_outcome_validation: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "outcome_validation_id", "execution_feedback_id", "work_order_id", "plant_id", "asset_id", "forecast_run_id", "predicted_avoided_loss_mwh", "predicted_value_protected", "actual_validated_recovery_mwh", "actual_value_realized", "execution_cost", "net_realized_value", "realization_pct", "outcome_confidence_pct", "variance_driver", "validation_status", "learning_feedback_status", "source_mode" from aip_compat."plan_outcome_validation" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "outcome_validation_id", "execution_feedback_id", "work_order_id", "plant_id", "asset_id", "forecast_run_id", "predicted_avoided_loss_mwh", "predicted_value_protected", "actual_validated_recovery_mwh", "actual_value_realized", "execution_cost", "net_realized_value", "realization_pct", "outcome_confidence_pct", "variance_driver", "validation_status", "learning_feedback_status", "source_mode" from aip."plan_outcome_validation" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'plan_outcome_validation: % rebuilt row(s) differ on 18 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."commercial_and_ppa" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."commercial_and_ppa" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'commercial_and_ppa: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "ppa_id", "plant_id", "offtaker", "ppa_tariff_k_wh", "contracted_capacity_mw", "contract_start_date", "contract_expiry_date", "availability_obligation_pct", "scheduled_energy_mwh", "delivered_energy_mwh", "deemed_generation_mwh", "shortfall_energy_mwh", "availability_penalty", "curtailment_compensation", "invoice_amount", "amount_received", "receivable_balance", "days_outstanding", "contract_status" from aip_compat."commercial_and_ppa" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "ppa_id", "plant_id", "offtaker", "ppa_tariff_k_wh", "contracted_capacity_mw", "contract_start_date", "contract_expiry_date", "availability_obligation_pct", "scheduled_energy_mwh", "delivered_energy_mwh", "deemed_generation_mwh", "shortfall_energy_mwh", "availability_penalty", "curtailment_compensation", "invoice_amount", "amount_received", "receivable_balance", "days_outstanding", "contract_status" from aip."commercial_and_ppa" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'commercial_and_ppa: % rebuilt row(s) differ on 19 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."twin_telemetry" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."twin_telemetry" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'twin_telemetry: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "timestamp", "plant_id", "poa_wm2", "ghi_wm2", "ambient_temp_c", "module_temp_c", "wind_speed_ms", "soiling_ratio", "expected_dc_mw", "expected_ac_mw", "actual_ac_mw", "pr_pct", "availability_pct", "inverter_efficiency_pct", "grid_frequency_hz", "power_factor", "data_quality_pct", "source", "clear_sky_poa_wm2", "cloud_cover_pct", "cloud_transmittance_pct", "clear_sky_ac_potential_mw", "weather_adjusted_expected_ac_mw", "weather_loss_mw", "plant_operational_loss_mw", "curtailment_pct", "asset_health_score", "weather_source", "weather_mode", "data_provenance" from aip_compat."twin_telemetry" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "timestamp", "plant_id", "poa_wm2", "ghi_wm2", "ambient_temp_c", "module_temp_c", "wind_speed_ms", "soiling_ratio", "expected_dc_mw", "expected_ac_mw", "actual_ac_mw", "pr_pct", "availability_pct", "inverter_efficiency_pct", "grid_frequency_hz", "power_factor", "data_quality_pct", "source", "clear_sky_poa_wm2", "cloud_cover_pct", "cloud_transmittance_pct", "clear_sky_ac_potential_mw", "weather_adjusted_expected_ac_mw", "weather_loss_mw", "plant_operational_loss_mw", "curtailment_pct", "asset_health_score", "weather_source", "weather_mode", "data_provenance" from aip."twin_telemetry" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'twin_telemetry: % rebuilt row(s) differ on 30 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."inverter_telemetry" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."inverter_telemetry" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'inverter_telemetry: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "timestamp", "plant_id", "asset_id", "inverter_tag", "dc_power_mw", "ac_power_mw", "dc_voltage_v", "dc_current_a", "inverter_temp_c", "status", "alarm_code", "data_provenance" from aip_compat."inverter_telemetry" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "timestamp", "plant_id", "asset_id", "inverter_tag", "dc_power_mw", "ac_power_mw", "dc_voltage_v", "dc_current_a", "inverter_temp_c", "status", "alarm_code", "data_provenance" from aip."inverter_telemetry" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'inverter_telemetry: % rebuilt row(s) differ on 12 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."bess_telemetry" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."bess_telemetry" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'bess_telemetry: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "timestamp", "bess_id", "plant_id", "charge_mw_poi", "discharge_mw_poi", "charge_source", "dispatch_schedule_mw", "available_mw", "so_c_pct", "aux_load_mw", "cell_temp_max_c", "cell_temp_avg_c", "ambient_temp_c", "co_located_pv_mw", "operating_mode", "data_quality_pct", "data_provenance" from aip_compat."bess_telemetry" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "timestamp", "bess_id", "plant_id", "charge_mw_poi", "discharge_mw_poi", "charge_source", "dispatch_schedule_mw", "available_mw", "so_c_pct", "aux_load_mw", "cell_temp_max_c", "cell_temp_avg_c", "ambient_temp_c", "co_located_pv_mw", "operating_mode", "data_quality_pct", "data_provenance" from aip."bess_telemetry" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'bess_telemetry: % rebuilt row(s) differ on 17 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."bess_daily_operations" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."bess_daily_operations" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'bess_daily_operations: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "date", "bess_id", "plant_id", "charge_mwh_poi", "discharge_mwh_poi", "aux_mwh", "start_so_c_pct", "end_so_c_pct", "equivalent_full_cycles", "availability_pct", "scheduled_discharge_mwh", "max_cell_temp_c", "cumulative_discharge_mwh_since_cod", "data_provenance" from aip_compat."bess_daily_operations" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "date", "bess_id", "plant_id", "charge_mwh_poi", "discharge_mwh_poi", "aux_mwh", "start_so_c_pct", "end_so_c_pct", "equivalent_full_cycles", "availability_pct", "scheduled_discharge_mwh", "max_cell_temp_c", "cumulative_discharge_mwh_since_cod", "data_provenance" from aip."bess_daily_operations" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'bess_daily_operations: % rebuilt row(s) differ on 14 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."forecast_weather" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."forecast_weather" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'forecast_weather: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "plant_id", "forecast_run_timestamp", "interval_start", "lead_hours", "clear_sky_index", "cloud_cover_pct", "ambient_temp_c", "wind_speed_ms", "forecast_curtailment_pct", "nwp_source", "data_provenance" from aip_compat."forecast_weather" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "plant_id", "forecast_run_timestamp", "interval_start", "lead_hours", "clear_sky_index", "cloud_cover_pct", "ambient_temp_c", "wind_speed_ms", "forecast_curtailment_pct", "nwp_source", "data_provenance" from aip."forecast_weather" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'forecast_weather: % rebuilt row(s) differ on 11 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."fcst_interval" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."fcst_interval" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'fcst_interval: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "forecast_run_timestamp", "plant_id", "interval_start", "interval_minutes", "lead_hours", "clear_sky_poa_wm2", "forecast_poa_wm2", "cloud_cover_pct", "ambient_temp_c", "wind_speed_ms", "soiling_pct", "availability_pct", "curtailment_pct", "asset_health_score", "clear_sky_ac_potential_mw", "weather_adjusted_physics_mw", "after_availability_mw", "after_curtailment_mw", "after_asset_state_mw", "ml_residual_pct", "ml_residual_correction_mw", "forecast_delivered_mw", "uncertainty_pct", "forecast_lower_mw", "forecast_upper_mw", "model_id", "physics_model_version", "residual_model_version", "data_source", "uncertainty_method" from aip_compat."fcst_interval" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "forecast_run_timestamp", "plant_id", "interval_start", "interval_minutes", "lead_hours", "clear_sky_poa_wm2", "forecast_poa_wm2", "cloud_cover_pct", "ambient_temp_c", "wind_speed_ms", "soiling_pct", "availability_pct", "curtailment_pct", "asset_health_score", "clear_sky_ac_potential_mw", "weather_adjusted_physics_mw", "after_availability_mw", "after_curtailment_mw", "after_asset_state_mw", "ml_residual_pct", "ml_residual_correction_mw", "forecast_delivered_mw", "uncertainty_pct", "forecast_lower_mw", "forecast_upper_mw", "model_id", "physics_model_version", "residual_model_version", "data_source", "uncertainty_method" from aip."fcst_interval" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'fcst_interval: % rebuilt row(s) differ on 30 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."fcst_actual" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."fcst_actual" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'fcst_actual: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "plant_id", "interval_start", "actual_ac_mw", "actual_energy_mwh", "observed_poa_wm2", "actual_availability_pct", "actual_curtailment_pct", "data_quality_status", "source_mode" from aip_compat."fcst_actual" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "plant_id", "interval_start", "actual_ac_mw", "actual_energy_mwh", "observed_poa_wm2", "actual_availability_pct", "actual_curtailment_pct", "data_quality_status", "source_mode" from aip."fcst_actual" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'fcst_actual: % rebuilt row(s) differ on 9 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."fcst_validation" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."fcst_validation" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'fcst_validation: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "forecast_run_id", "plant_id", "interval_start", "lead_hours", "physics_forecast_mw", "hybrid_forecast_mw", "actual_mw", "physics_error_mw", "hybrid_error_mw", "physics_abs_error_pct", "hybrid_abs_error_pct", "inside_80_pct_band", "horizon_bucket_hours", "validation_mode" from aip_compat."fcst_validation" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "forecast_run_id", "plant_id", "interval_start", "lead_hours", "physics_forecast_mw", "hybrid_forecast_mw", "actual_mw", "physics_error_mw", "hybrid_error_mw", "physics_abs_error_pct", "hybrid_abs_error_pct", "inside_80_pct_band", "horizon_bucket_hours", "validation_mode" from aip."fcst_validation" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'fcst_validation: % rebuilt row(s) differ on 14 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."reliability_life_history" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."reliability_life_history" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'reliability_life_history: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "reliability_record_id", "asset_id", "asset_tag", "plant_id", "commissioned_date", "observation_date", "operating_hours", "failed_surviving", "right_censored", "replacement_reset", "evidence_source", "source_mode", "data_quality_status", "group_id", "module_id", "observation_basis", "calendar_exposure_hours", "model_id", "batch_id", "evidence_reference", "failure_criterion", "data_basis" from aip_compat."reliability_life_history" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "reliability_record_id", "asset_id", "asset_tag", "plant_id", "commissioned_date", "observation_date", "operating_hours", "failed_surviving", "right_censored", "replacement_reset", "evidence_source", "source_mode", "data_quality_status", "group_id", "module_id", "observation_basis", "calendar_exposure_hours", "model_id", "batch_id", "evidence_reference", "failure_criterion", "data_basis" from aip."reliability_life_history" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'reliability_life_history: % rebuilt row(s) differ on 22 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."plan_resource_calendar" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."plan_resource_calendar" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'plan_resource_calendar: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "resource_event_id", "resource_type", "resource_id", "plant_id", "start", "end", "event_type", "availability", "available_hours", "committed_hours", "capacity_pct", "skill_or_certification", "location", "reason", "source" from aip_compat."plan_resource_calendar" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "resource_event_id", "resource_type", "resource_id", "plant_id", "start", "end", "event_type", "availability", "available_hours", "committed_hours", "capacity_pct", "skill_or_certification", "location", "reason", "source" from aip."plan_resource_calendar" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'plan_resource_calendar: % rebuilt row(s) differ on 15 checked column(s)', d; end if;
end $$;
do $$
declare a int; b int; d int;
begin
  select count(*) into a from aip_compat."plan_weather_forecast" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  select count(*) into b from aip."plan_weather_forecast" where tenant_id = '00000000-0000-0000-0000-0000000000c1';
  if a <> b then raise exception 'plan_weather_forecast: compat view has % rows, sheet has %', a, b; end if;
  select count(*) into d from (select "row_key", "weather_id", "plant_id", "forecast_time", "valid_from", "valid_to", "rain_probability_pct", "rainfall_mm", "wind_kmh", "gust_kmh", "lightning_risk", "temperature_c", "visibility_km", "work_at_height_status", "outdoor_electrical_status", "access_status", "freshness_status", "source_mode", "evidence_id" from aip_compat."plan_weather_forecast" where tenant_id = '00000000-0000-0000-0000-0000000000c1' except all select "row_key", "weather_id", "plant_id", "forecast_time", "valid_from", "valid_to", "rain_probability_pct", "rainfall_mm", "wind_kmh", "gust_kmh", "lightning_risk", "temperature_c", "visibility_km", "work_at_height_status", "outdoor_electrical_status", "access_status", "freshness_status", "source_mode", "evidence_id" from aip."plan_weather_forecast" where tenant_id = '00000000-0000-0000-0000-0000000000c1') x;
  if d <> 0 then raise exception 'plan_weather_forecast: % rebuilt row(s) differ on 18 checked column(s)', d; end if;
end $$;
\echo 'compatibility views rebuild 34 sheets'
