
(()=>{
const AIG={tab:'policy',audit:[],policies:[
{id:'GR-VIS-01',cap:'AI Vision',rule:'Evidence confidence and image quality',threshold:'Confidence ≥ 90% and image quality ≥ 80%',outcome:'Allow',enabled:true},
{id:'GR-VIS-02',cap:'AI Vision',rule:'Low-confidence defect',threshold:'Confidence < 75%',outcome:'Manual Review',enabled:true},
{id:'GR-WO-01',cap:'Work Orders',rule:'Safety-critical or high-cost work',threshold:'Critical safety class or cost > ₹5 lakh',outcome:'Approval',enabled:true},
{id:'GR-WO-02',cap:'Work Orders',rule:'Release readiness',threshold:'Parts ready + permit ready + approved',outcome:'Block',enabled:true},
{id:'GR-CR-01',cap:'Crew Planning',rule:'Mandatory certification',threshold:'Required certification valid on job date',outcome:'Block',enabled:true},
{id:'GR-CR-02',cap:'Crew Planning',rule:'Shift and fatigue limit',threshold:'≤ 12 hours and rest window satisfied',outcome:'Block',enabled:true},
{id:'GR-SP-01',cap:'Spares',rule:'Auto-reservation authority',threshold:'Value ≤ ₹1 lakh and no critical-stock breach',outcome:'Allow',enabled:true},
{id:'GR-SP-02',cap:'Spares',rule:'Substitute part approval',threshold:'OEM-approved substitute only',outcome:'Approval',enabled:true},
{id:'GR-WAR-01',cap:'Warranty',rule:'Claim evidence completeness',threshold:'Serial + timestamp + defect evidence ≥ 85%',outcome:'Approval',enabled:true},
{id:'GR-AST-01',cap:'Assistant',rule:'Grounded operational response',threshold:'Source evidence present; no direct transaction execution',outcome:'Manual Review',enabled:true}
],events:[
{time:'Today 09:42',cap:'Crew Planning',decision:'Blocked',detail:'HV certification expired for recommended technician',policy:'GR-CR-01'},
{time:'Today 09:18',cap:'AI Vision',decision:'Manual Review',detail:'Thermal image quality 68%; confidence 73%',policy:'GR-VIS-02'},
{time:'Yesterday 17:30',cap:'Work Orders',decision:'Approval',detail:'Estimated cost ₹8.4 lakh exceeded delegated authority',policy:'GR-WO-01'},
{time:'Yesterday 15:12',cap:'Spares',decision:'Allowed',detail:'Reservation ₹72,000 within policy limit',policy:'GR-SP-01'}
]};
window.AIG=AIG;
function esc(x){return String(x??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function pill(v){const c=/block/i.test(v)?'block':/review/i.test(v)?'review':/approval/i.test(v)?'approve':'allow';return `<span class="aig-pill aig-${c}">${esc(v)}</span>`}
function kpi(l,n,s,c,i,pct){const p=Math.max(0,Math.min(100,Number(pct)||0));return `<div class="aig-kpi aig-kpi-standard-ring" style="--aig:${c};--aip-ring:${p}"><div class="aig-kpi-copy"><div class="l">${l}</div><div class="n">${n}</div></div><div class="aip-kpi-ring-wrap"><div class="aip-kpi-ring" style="--aip-ring:${p};--aip-ring-accent:${c}"><span class="aip-kpi-ring-value">${p.toFixed(p%1?1:0)}%</span></div><div class="aip-kpi-ring-note">${s}</div></div></div>`}
function tabs(){return `<div class="aig-tabs">${[['policy','Policy Centre'],['autonomy','Autonomy Controls'],['approvals','Approval Matrix'],['hardstops','Safety & Hard Stops'],['evidence','Confidence & Evidence'],['overrides','Overrides & Exceptions'],['monitor','Guardrail Monitoring'],['audit','Audit & Policy History'],['test','Policy Simulator']].map(x=>`<button class="aig-tab ${AIG.tab===x[0]?'active':''}" onclick="aigTab('${x[0]}')">${x[1]}</button>`).join('')}</div>`}
function policy(){return `<div class="aig-grid"><div class="aig-panel"><h3>Enforceable capability policies</h3><div class="aig-muted">Policies determine whether an AI action is allowed, routed for approval, sent to manual review, or blocked.</div>${AIG.policies.map(p=>`<div class="aig-policy"><div class="aig-policy-head"><div><b>${p.id} · ${p.cap}</b><div class="aig-muted">${p.rule}</div></div><div class="aig-toggle ${p.enabled?'on':''}" onclick="aigToggle('${p.id}')"></div></div><div class="aig-row"><span>${p.threshold}</span><span>${pill(p.outcome)}</span><span>Policy v1.0</span><span>Owner: AI Governance</span><button class="aig-btn" onclick="aigEdit('${p.id}')">Edit</button></div></div>`).join('')}</div><div class="aig-panel"><h3>Runtime decision sequence</h3>${['Validate input freshness and completeness','Check model health and confidence','Apply safety and hard-stop rules','Check authority, cost and autonomy level','Route to allow, approval, review or block','Log model, policy, evidence and outcome'].map((x,i)=>`<div class="aig-banner"><b>${i+1}. ${x}</b>${i<2?pill('Allow'):i<4?pill('Approval'):pill('Logged')}</div>`).join('')}</div></div>`}
function autonomy(){const rows=[['AI Vision classification','Recommend','Auto within threshold','Engineer'],['Work-order creation','Draft','Approval required','Planner'],['Crew assignment','Recommend','No auto-dispatch','Maintenance planner'],['Spares reservation','Execute within limit','Auto ≤ ₹1 lakh','Inventory controller'],['Inventory transfer','Recommend','Approval required','Regional stores lead'],['Warranty claim','Draft only','Never auto-submit','Commercial manager'],['Assistant','Answer / analyse','No direct transaction','User']];return `<div class="aig-panel"><h3>Autonomy control matrix</h3><div class="aig-tablewrap"><table class="aig-table"><thead><tr><th>Capability</th><th>Permitted action</th><th>Autonomy limit</th><th>Accountable role</th><th>Runtime control</th></tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}<td>${pill(/No|Never/.test(r[2])?'Manual Review':/Approval/.test(r[2])?'Approval':'Allow')}</td></tr>`).join('')}</tbody></table></div></div>`}
function approvals(){const rows=[['Critical safety work order','Reliability Engineer → Plant Head','2 approvals','30 min'],['WO cost > ₹5 lakh','Plant Head → Finance','2 approvals','4 h'],['Non-OEM spare substitute','Engineering → Stores','2 approvals','2 h'],['Emergency procurement','Plant Head → Procurement','2 approvals','1 h'],['Warranty claim > ₹10 lakh','Engineering → Commercial','2 approvals','1 day']];return table('Human approval matrix',['Trigger','Approval chain','Minimum','Escalation'],rows)}
function hardstops(){return `<div class="aig-grid"><div class="aig-panel"><h3>Non-negotiable hard stops</h3>${['Missing or expired mandatory certification','Permit-to-work not approved','Asset identity uncertain','Critical spare unavailable or quarantined','Model deployment marked degraded','Source data stale beyond operating tolerance','OEM safety limit conflict','Shift/fatigue limit exceeded'].map(x=>`<div class="aig-banner block"><b>${x}</b>${pill('Block')}</div>`).join('')}</div><div class="aig-panel"><h3>Fail-safe behaviour</h3>${['Preserve existing schedule','Prevent transaction execution','Route to named human owner','Show exact block reason','Retain evidence and model version','Fall back to manual or rule-based workflow'].map(x=>`<div class="aig-banner"><b>${x}</b>${pill('Manual Review')}</div>`).join('')}</div></div>`}
function evidence(){const rows=[['AI Vision defect','90%','80% image quality','Asset ID + timestamp + location'],['Failure prediction','85%','24 h data freshness','Sensor health + model health'],['Crew recommendation','80%','100% mandatory constraints','Skill + cert + availability'],['Spares demand','75%','Current stock snapshot','WO + BOM + lead time'],['Warranty eligibility','85%','Complete evidence pack','Serial + date + coverage']];return table('Confidence and evidence rules',['Capability','Auto-action confidence','Minimum quality','Required evidence'],rows)}
function overrides(){return `<div class="aig-grid"><div class="aig-panel"><h3>Override governance</h3>${[['Crew Match v2.4','38%','Travel estimate inaccurate','Review routing data'],['Vision Defect v3.1','11%','Image glare / shadow','Add quality pre-check'],['Spares Forecast v2.0','17%','Campaign maintenance demand','Add campaign calendar']].map(x=>`<div class="aig-policy"><b>${x[0]}</b><div class="aig-row"><span>Override rate ${x[1]}</span><span>${x[2]}</span><span>${pill('Manual Review')}</span><span>${x[3]}</span><button class="aig-btn">Investigate</button></div></div>`).join('')}</div><div class="aig-panel"><h3>Mandatory override record</h3>${['Original AI recommendation','Final human decision','Reason and evidence','Risk accepted','Approver','Outcome after execution'].map(x=>`<div class="aig-banner"><b>${x}</b>${pill('Logged')}</div>`).join('')}</div></div>`}
function monitor(){return `<div class="aig-grid"><div class="aig-panel"><h3>Guardrail outcomes — last 30 days</h3>${[['Allowed',428,'Allow'],['Approval required',74,'Approval'],['Manual review',39,'Manual Review'],['Blocked',18,'Block']].map(x=>`<div class="aig-row"><b>${x[0]}</b><b>${x[1]}</b><span>${pill(x[2])}</span><span>${Math.round(x[1]/559*100)}%</span><button class="aig-btn">Details</button></div>`).join('')}</div><div class="aig-panel"><h3>Risk signals</h3>${[['Low-confidence decisions','12','review'],['Stale-data events','4','block'],['Policy breaches','0','allow'],['Approval SLA misses','3','review'],['Degraded models','1','block']].map(x=>`<div class="aig-banner ${x[2]==='block'?'block':x[2]==='review'?'warn':''}"><b>${x[0]}</b><strong>${x[1]}</strong></div>`).join('')}</div></div>`}
function audit(){return table('Immutable guardrail decision ledger',['Timestamp','Capability','Decision','Policy','Detail'],AIG.events.map(e=>[e.time,e.cap,pill(e.decision),e.policy,e.detail]))}
function simulator(){return `<div class="aig-grid"><div class="aig-panel"><h3>Policy simulator</h3><div class="aig-test"><div class="aig-field"><label>Capability</label><select id="aigCap"><option>AI Vision</option><option>Work Orders</option><option>Crew Planning</option><option>Spares</option><option>Warranty</option></select></div><div class="aig-field"><label>Confidence (%)</label><input id="aigConf" type="number" value="82"></div><div class="aig-field"><label>Safety critical</label><select id="aigSafety"><option>No</option><option>Yes</option></select></div><div class="aig-field"><label>Evidence complete</label><select id="aigEvidence"><option>Yes</option><option>No</option></select></div><div class="aig-field"><label>Permit ready</label><select id="aigPermit"><option>Yes</option><option>No</option></select></div><div class="aig-field"><label>Certification valid</label><select id="aigCert"><option>Yes</option><option>No</option></select></div></div><button class="aig-btn primary" style="margin-top:12px" onclick="aigSimulate()">Evaluate action</button><div id="aigResult"></div></div><div class="aig-panel"><h3>Interpretation</h3><div class="aig-muted">The simulator uses the same decision sequence displayed across operational modules. It demonstrates the expected runtime outcome without executing a real transaction.</div>${['Allow — action can proceed inside configured autonomy limit','Approval — named approver must authorize','Manual Review — evidence or confidence is insufficient','Block — hard-stop condition prevents execution'].map(x=>`<div class="aig-banner"><b>${x}</b></div>`).join('')}</div></div>`}
function table(title,heads,rows){return `<div class="aig-panel"><h3>${title}</h3><div class="aig-tablewrap"><table class="aig-table"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`}
function content(){return AIG.tab==='policy'?policy():AIG.tab==='autonomy'?autonomy():AIG.tab==='approvals'?approvals():AIG.tab==='hardstops'?hardstops():AIG.tab==='evidence'?evidence():AIG.tab==='overrides'?overrides():AIG.tab==='monitor'?monitor():AIG.tab==='audit'?audit():simulator()}
window.renderAIGuardrails=function(){const v=document.getElementById('view-guardrails');if(!v)return;v.innerHTML=`<div class="view-head"><div><div class="eyebrow" style="color:#16865b">TRUSTED AI · RUNTIME POLICY ENFORCEMENT</div><h1>AI Guardrails</h1></div></div><div class="aig-kpis">${kpi('Actions evaluated','559','100% of governed actions evaluated','#16865b',1,100)}${kpi('Approval required','74','13.2% routed to named human approval','#3157b7',2,13.2)}${kpi('Manual review','39','7.0% required evidence or confidence review','#d59600',3,7.0)}${kpi('Blocked actions','18','3.2% stopped by hard-stop protection','#c43b3b',4,3.2)}</div>${tabs()}${content()}`}
window.aigTab=t=>{AIG.tab=t;renderAIGuardrails()};window.aigToggle=id=>{const p=AIG.policies.find(x=>x.id===id);if(p)p.enabled=!p.enabled;renderAIGuardrails()};window.aigEdit=id=>{if(window.showToast)showToast('Policy editor',id+' selected for controlled update')};
window.aigSimulate=()=>{const cap=document.getElementById('aigCap').value,conf=+document.getElementById('aigConf').value,safety=document.getElementById('aigSafety').value==='Yes',evid=document.getElementById('aigEvidence').value==='Yes',permit=document.getElementById('aigPermit').value==='Yes',cert=document.getElementById('aigCert').value==='Yes';let d='Allow',why='All configured controls passed.';if(!permit||!cert){d='Block';why=!permit?'Permit-to-work is not ready.':'Mandatory certification is invalid.'}else if(safety){d='Approval';why='Safety-critical action requires named human approval.'}else if(!evid||conf<75){d='Manual Review';why='Evidence or confidence is below the operating threshold.'}else if(conf<90&&cap==='AI Vision'){d='Manual Review';why='AI Vision confidence is below the auto-action threshold.'}const cls=/Block/.test(d)?'block':/Review/.test(d)?'warn':'';document.getElementById('aigResult').innerHTML=`<div class="aig-result aig-banner ${cls}"><div><b>${d}</b><div class="aig-muted">${why}</div></div>${pill(d)}</div>`;AIG.events.unshift({time:new Date().toLocaleString(),cap,decision:d,detail:why,policy:'Simulation'});}
function addNav(){const model=document.querySelector('.nav-item[data-view="models"]');if(!model||document.querySelector('[data-view="guardrails"]'))return;const n=document.createElement('div');n.className='nav-item';n.dataset.view='guardrails';n.innerHTML='<span aria-hidden="true" class="ic ic-green"><svg viewBox="0 0 24 24"><path d="M12 3 4 6v6c0 4.8 3.2 7.7 8 9 4.8-1.3 8-4.2 8-9V6l-8-3z"></path><path d="m8.5 12 2.2 2.2 4.8-5"></path></svg></span> AI Guardrails';model.parentNode.insertBefore(n,model.nextSibling);n.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));n.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById('view-guardrails').classList.add('active');renderAIGuardrails();});}
function addView(){if(document.getElementById('view-guardrails'))return;const v=document.createElement('div');v.className='view';v.id='view-guardrails';document.querySelector('.content')?.appendChild(v)}
function decorate(){const ids=['aivision','workorderintelligence','crewscheduling','spares','inventory','warrantyrecovery','dataexplorer'];ids.forEach(id=>{const v=document.getElementById('view-'+id);if(!v||v.querySelector('.guardrail-chip'))return;const h=v.querySelector('.view-head h1');if(h)h.insertAdjacentHTML('afterend','<span class="guardrail-chip" title="AI actions are evaluated against active runtime policies">Guardrails active</span>')})}
function wrap(){if(window.__aigWrapped)return;window.__aigWrapped=true;const oldRelease=window.avxRelease;window.avxRelease=id=>{const f=(window.VISION_FINDINGS||[]).find((x,i)=>(x.id||`VIS-${1001+i}`)===id);if(f&&(f.confidence<75||f.permitStatus!=='Ready')){AIG.events.unshift({time:new Date().toLocaleString(),cap:'AI Vision',decision:'Blocked',detail:id+' failed confidence or permit hard stop',policy:'GR-VIS-02 / readiness'});window.showToast?.('Guardrail blocked release','Confidence or permit readiness did not meet policy');return renderAIVision()}return oldRelease?.(id)};const oldAssign=window.opsAssignCrew;window.opsAssignCrew=(id,crew)=>{const roster=(window.CREW_ROSTER||[]);const c=roster.find(x=>(x.crew||x.Crew_ID||x.name||x.Technician_Name)===crew);if(c&&String(c.certExpiry||c.Certification_Expiry||'')&&Date.parse(c.certExpiry||c.Certification_Expiry)<Date.now()){AIG.events.unshift({time:new Date().toLocaleString(),cap:'Crew Planning',decision:'Blocked',detail:id+' assignment blocked: expired certification',policy:'GR-CR-01'});window.toast?.('Guardrail blocked assignment','Mandatory certification is expired');return}return oldAssign?.(id,crew)};}
document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{addView();addNav();wrap();decorate();try{if(typeof V2_HELP!=='undefined')V2_HELP.guardrails={title:'AI Guardrails',what:'The runtime policy-enforcement layer governing what AI may recommend, draft, execute, or block across AI Vision, work orders, crew planning, spares, warranty and the Assistant.',metrics:[{name:'Actions evaluated',desc:'AI-assisted decisions checked against active policies.'},{name:'Approval required',desc:'Actions routed to named human approvers because of risk, cost, safety or authority limits.'},{name:'Manual review',desc:'Cases with insufficient confidence, evidence or data quality.'},{name:'Blocked actions',desc:'Actions prevented by hard-stop safety, certification, permit, model-health or data-quality rules.'}],interact:'Use Policy Centre to enable or disable governed rules; Autonomy Controls to define permitted action levels; Approval Matrix for human decision rights; Safety & Hard Stops for non-negotiable blocks; Confidence & Evidence for thresholds; Overrides for human departures from AI advice; Monitoring and Audit for outcomes; and Policy Simulator to test a scenario without executing a transaction.',tip:'Guardrails are separate from model monitoring, approval workflow and ERP integration. Model Registry reports model health; Guardrails decide what AI is permitted to do; Approval Workflow executes required human approvals; Integrations sends approved business transactions to connected systems.',spec:'Input validation → model health → confidence and evidence → hard stops → authority and autonomy → allow / approve / review / block → immutable audit.'};}catch(e){}},150));
let __decorateQueued=false;
const mo=new window.__APMSafeMutationObserver(()=>{
  if(window.__aipScrollbarDragActive||window.__aipMainScrollActive)return;
  if(__decorateQueued) return;
  __decorateQueued=true;
  requestAnimationFrame(()=>{__decorateQueued=false;decorate();});
});
document.addEventListener('DOMContentLoaded',()=>mo.observe(document.getElementById('main')||document.body,{subtree:true,childList:true}));
})();
