// Governed-mode parity: the runtime boots on the governed workbook (phase 3 compatibility views) instead of only its
// bundled data. Screens that read the data change where governed data differs from the bundle (corrections,
// canonical vocabulary, masters overriding stale copies), so this run compares against its own reviewed baseline:
//   node test/governed.mjs            exact check against reference/v915-governed-crawl.json
//   node test/governed.mjs --rebase   writes that baseline and docs/parity/governed-baseline.md for review
import { execFileSync, spawn } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { generateSigningKey, issueLicense } from "@sustantix/license/issuer";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "../../..");
const rebase = process.argv.includes("--rebase");
const tmp = process.env.AIP_PARITY_OUT ?? mkdtempSync(join(tmpdir(), "aip-governed-"));
mkdirSync(tmp, { recursive: true });
const { signing, publicJwk } = generateSigningKey("sx-governed");
writeFileSync(join(tmp, "keys.json"), JSON.stringify([publicJwk]));
const env = { ...process.env, AIP_EXTRA_TRUSTED_KEYS: join(tmp, "keys.json") };
execFileSync("node", ["build.mjs"], { cwd: join(root, "packages/host-bridge"), env, stdio: "inherit" });
execFileSync("node", ["build.mjs", "--target", "standalone", "--out", "dist/governed"], { cwd: join(here, ".."), env, stdio: "inherit" });
const workbook = join(tmp, "governed.json");
execFileSync("pnpm", ["--silent", "--filter", "@sustantix/schema", "governed:json", workbook], { cwd: root, stdio: "inherit" });

const port = 4800 + Math.floor(Math.random() * 500);
const server = spawn("node", ["serve.mjs", "dist/governed", String(port)], { cwd: join(here, ".."), stdio: "ignore" });
await new Promise((r) => setTimeout(r, 800));
const reference = JSON.parse(readFileSync(join(root, "reference/v915-screen-crawl.json"), "utf8"));
const capturedAt = Math.floor(Date.parse(reference.capturedAt) / 1000);
const license = issueLicense(signing, { customer: { id: "QA", name: "Governed QA" }, platform: "vercel", bind: { domains: ["localhost"] }, edition: "enterprise", validDays: 30 }, capturedAt).token;
const out = join(tmp, "governed-crawl.json");
try {
  execFileSync("node", [join(here, "crawl.mjs"), `http://localhost:${port}/`, out, "--license", license, "--clock", reference.capturedAt, "--governed", workbook], { stdio: "inherit" });
} finally {
  server.kill();
}
const got = JSON.parse(readFileSync(out, "utf8"));
const same = (a, b) => a && b && a.text === b.text && JSON.stringify(a.tabs) === JSON.stringify(b.tabs) && JSON.stringify(a.heads) === JSON.stringify(b.heads);
const excerpt = (a, b) => {
  let i = 0;
  while (i < a.length && a[i] === b[i]) i++;
  const cut = (s) => s.slice(Math.max(0, i - 60), i + 140).replace(/\s+/g, " ").replace(/\|/g, "\\|");
  return { at: i, reference: cut(a), governed: cut(b) };
};

if (rebase) {
  const ref = Object.fromEntries(reference.views.map((v) => [v.v, v]));
  const rows = got.views.map((v) => {
    const r = ref[v.v];
    if (same(r, v)) return `| ${v.t} | unchanged | | |`;
    const e = excerpt(r?.text ?? "", v.text ?? "");
    return `| ${v.t} | **changed** | ${e.reference} | ${e.governed} |`;
  });
  const changed = rows.filter((r) => r.includes("**changed**")).length;
  writeFileSync(join(root, "reference/v915-governed-crawl.json"), JSON.stringify(got, null, 1));
  mkdirSync(join(root, "docs/parity"), { recursive: true });
  writeFileSync(
    join(root, "docs/parity/governed-baseline.md"),
    [
      "# Governed-mode screen baseline (for review)",
      "",
      "Generated by `pnpm --filter @sustantix/aip-runtime test:governed -- --rebase`. The runtime booted on the governed workbook (phase 3 compatibility views, built from the governed workbook with corrections C1–C12) instead of only its bundled data, at the reference capture instant.",
      "",
      `Screens: ${got.views.length} · unchanged ${got.views.length - changed} · changed ${changed} · page errors ${got.errors.length} (reference ${reference.errors?.length ?? 0}).`,
      "",
      "A changed screen shows governed data where the bundle showed the workbook's original values: corrected records (planned and HSE-cited work orders, case assets, re-keyed parts), canonical vocabulary labels, and masters replacing stale copies. Each change below is reviewed before this baseline is accepted; from then on CI requires the governed crawl to match it exactly.",
      "",
      "| Screen | Result | Reference (first difference) | Governed |",
      "| --- | --- | --- | --- |",
      ...rows,
      "",
    ].join("\n"),
  );
  console.log(`governed baseline written: ${changed} of ${got.views.length} screens changed · ${got.errors.length} page errors`);
  process.exit(got.errors.length > (reference.errors?.length ?? 0) ? 1 : 0);
}

const basePath = join(root, "reference/v915-governed-crawl.json");
if (!existsSync(basePath)) throw new Error("no governed baseline: run with --rebase and review docs/parity/governed-baseline.md");
const base = Object.fromEntries(JSON.parse(readFileSync(basePath, "utf8")).views.map((v) => [v.v, v]));
let failures = 0;
for (const v of got.views) {
  const ok = same(base[v.v], v);
  console.log(`${ok ? "✓" : "✗"} governed parity · ${v.t}`);
  if (!ok) {
    failures++;
    const e = excerpt(base[v.v]?.text ?? "", v.text ?? "");
    console.log(`    at ${e.at}\n      baseline: ${e.reference}\n      got:      ${e.governed}`);
  }
}
if (got.errors.length > (reference.errors?.length ?? 0)) { console.log(`✗ governed mode raised ${got.errors.length} page error(s): ${got.errors.slice(0, 3).join(" | ")}`); failures++; }
console.log(failures ? `\n${failures} governed check(s) FAILED` : "\ngoverned parity: all checks passed");
process.exit(failures ? 1 : 0);
