// Screen-grid parity (phase 4): the runtime with every screen grid switched on, held to a reviewed baseline.
//   node test/grids.mjs [--rebase]
// --rebase writes reference/v915-grid-crawl.json and docs/parity/grid-baseline.md (what changed on each screen, for
// review). Without it, every screen must match that baseline exactly and every switched-on table must be a grid.
import { execFileSync, spawn } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { generateSigningKey, issueLicense } from "@sustantix/license/issuer";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "../../..");
const rebase = process.argv.includes("--rebase");
const tmp = process.env.AIP_PARITY_OUT ?? mkdtempSync(join(tmpdir(), "aip-grids-"));
mkdirSync(tmp, { recursive: true });
const { signing, publicJwk } = generateSigningKey("sx-grids");
writeFileSync(join(tmp, "keys.json"), JSON.stringify([publicJwk]));
const env = { ...process.env, AIP_EXTRA_TRUSTED_KEYS: join(tmp, "keys.json") };
execFileSync("node", ["build.mjs"], { cwd: join(root, "packages/host-bridge"), env, stdio: "inherit" });
execFileSync("node", ["build.mjs"], { cwd: join(root, "packages/grid"), stdio: "inherit" });
execFileSync("node", ["build.mjs", "--target", "standalone", "--out", "dist/grids"], { cwd: join(here, ".."), env, stdio: "inherit" });

const port = 5300 + Math.floor(Math.random() * 500);
const server = spawn("node", ["serve.mjs", "dist/grids", String(port)], { cwd: join(here, ".."), stdio: "ignore" });
await new Promise((r) => setTimeout(r, 800));
const reference = JSON.parse(readFileSync(join(root, "reference/v915-screen-crawl.json"), "utf8"));
const capturedAt = Math.floor(Date.parse(reference.capturedAt) / 1000);
const license = issueLicense(signing, { customer: { id: "QA", name: "Grid QA" }, platform: "vercel", bind: { domains: ["localhost"] }, edition: "enterprise", validDays: 30 }, capturedAt).token;
const out = join(tmp, "grid-crawl.json");
try {
  execFileSync("node", [join(here, "crawl.mjs"), `http://localhost:${port}/`, out, "--license", license, "--clock", reference.capturedAt, "--grid-screens", "all"], { stdio: "inherit" });
} finally {
  server.kill();
}
const got = JSON.parse(readFileSync(out, "utf8"));
const same = (a, b) => a && b && a.text === b.text && JSON.stringify(a.tabs) === JSON.stringify(b.tabs) && JSON.stringify(a.heads) === JSON.stringify(b.heads);
const excerpt = (a, b) => {
  let i = 0;
  while (i < a.length && a[i] === b[i]) i++;
  const cut = (s) => s.slice(Math.max(0, i - 60), i + 140).replace(/\s+/g, " ").replace(/\|/g, "\\|");
  return { at: i, reference: cut(a), grid: cut(b) };
};

// Every table the screen census names becomes a grid on its screen (Asset Explorer needs the governed workspace).
const expected = JSON.parse(readFileSync(join(root, "packages/grid/dist/screen-grids.json"), "utf8"));
let failures = 0;
for (const v of got.views) {
  const want = expected[v.v];
  if (want === undefined) continue;
  const ok = v.grids === want;
  console.log(`${ok ? "✓" : "✗"} ${v.t}: ${v.grids} of ${want} table(s) shown as grids`);
  if (!ok) failures++;
}

if (rebase) {
  const ref = Object.fromEntries(reference.views.map((v) => [v.v, v]));
  const rows = got.views.map((v) => {
    const r = ref[v.v];
    if (same(r, v)) return `| ${v.t} | unchanged | | |`;
    const e = excerpt(r?.text ?? "", v.text ?? "");
    return `| ${v.t} | **changed** | ${e.reference} | ${e.grid} |`;
  });
  const changed = rows.filter((r) => r.includes("**changed**")).length;
  writeFileSync(join(root, "reference/v915-grid-crawl.json"), JSON.stringify(got, null, 1));
  mkdirSync(join(root, "docs/parity"), { recursive: true });
  writeFileSync(
    join(root, "docs/parity/grid-baseline.md"),
    [
      "# Screen-grid baseline (for review)",
      "",
      "Generated by `pnpm --filter @sustantix/aip-runtime test:grids -- --rebase`: the runtime on its bundled data with every screen grid switched on (`AIP_GRID_SCREENS=all`), at the reference capture instant. With the switch off (the default) every screen stays identical to the reference; `test` proves that separately.",
      "",
      `Screens: ${got.views.length} · unchanged ${got.views.length - changed} · changed ${changed} · page errors ${got.errors.length} (reference ${reference.errors?.length ?? 0}).`,
      "",
      "On a changed screen the table is presented by the Enterprise Grid: its toolbar (search, filter, grouping, columns, export) and footer appear, and only the rows in view are drawn, so text further down the table is no longer on the page until scrolled to. Headers, values and the screen's own cell content are the table's. Each change below is reviewed before this baseline is accepted; from then on CI requires the grid crawl to match it exactly.",
      "",
      "| Screen | Result | Reference (first difference) | With screen grids |",
      "| --- | --- | --- | --- |",
      ...rows,
      "",
    ].join("\n"),
  );
  console.log(`grid baseline written: ${changed} of ${got.views.length} screens changed · ${got.errors.length} page errors`);
  process.exit(failures || got.errors.length > (reference.errors?.length ?? 0) ? 1 : 0);
}

const basePath = join(root, "reference/v915-grid-crawl.json");
if (!existsSync(basePath)) throw new Error("no grid baseline: run with --rebase and review docs/parity/grid-baseline.md");
const base = Object.fromEntries(JSON.parse(readFileSync(basePath, "utf8")).views.map((v) => [v.v, v]));
for (const v of got.views) {
  const ok = same(base[v.v], v);
  console.log(`${ok ? "✓" : "✗"} grid parity · ${v.t}`);
  if (!ok) {
    failures++;
    const e = excerpt(base[v.v]?.text ?? "", v.text ?? "");
    console.log(`    at ${e.at}\n      baseline: ${e.reference}\n      got:      ${e.grid}`);
  }
}
if (got.errors.length > (reference.errors?.length ?? 0)) { console.log(`✗ screen grids raised ${got.errors.length} page error(s): ${got.errors.slice(0, 3).join(" | ")}`); failures++; }
console.log(failures ? `\n${failures} grid check(s) FAILED` : "\nscreen-grid parity: all checks passed");
process.exit(failures ? 1 : 0);
