/**
 * Postgres for the phase 2 masters: one tenant-scoped table per master with uuid identity, a business code unique
 * per tenant, composite tenant-safe foreign keys, controlled values as foreign keys into the reference tables
 * (guarded so a tenant can only use platform rows or its own), optimistic concurrency, audit and lineage.
 */
import type { BuiltMaster, MasterColumn, MasterDef } from "./masters.ts";
import { topoOrder } from "./masters.ts";

const q = (id: string) => `"${id.replace(/"/g, '""')}"`;
const lit = (s: string) => `'${s.replace(/'/g, "''")}'`;

/** Database column for a master column: references end in _id and hold the target's uuid. */
export const dbColumn = (c: MasterColumn) => (c.kind === "fk" || c.kind === "ref" ? `${c.name}_id` : c.name);

export function masterPgType(c: MasterColumn): string {
  switch (c.kind) {
    case "fk":
    case "ref":
      return "uuid";
    case "text":
    case "memo":
    case "url":
      return "text";
    case "integer":
      return "integer";
    case "decimal":
      return `numeric(24,${c.precision ?? 4})`;
    case "money":
      // Amounts are numeric(19,4) beside the row's ISO currency; never floating point.
      return "numeric(19,4)";
    case "date":
      return "date";
    case "datetime":
      return "timestamp without time zone";
    case "boolean":
      return "boolean";
  }
}

/** Registers are operational: planners write them. Masters are reference-grade: administrators write them. */
export const writers = (d: MasterDef) => (d.layer === "register" ? ["planner", "admin"] : ["admin"]);

const hasMoney = (d: MasterDef) => d.columns.some((c) => c.kind === "money");

export function mastersSql(defs: MasterDef[], defaultCurrency: string): string {
  const ordered = topoOrder(defs);
  const out: string[] = [
    `-- Sustantix AIP · phase 2: master data and consolidated registers
-- Generated by tools/schema from src/masters.ts — do not edit by hand.
-- Every master: id uuid identity, business code unique per tenant, composite (tenant_id, id) foreign keys so no row
-- can reference another tenant's row, controlled values as foreign keys into aip.ref_*, row_version for optimistic
-- concurrency, audit on every change, and lineage back to the workbook rows it replaced.

-- Audits a master row keyed on its business code.
create or replace function aip.audit_master_row() returns trigger language plpgsql security definer set search_path = aip, pg_temp as $$
begin
  insert into aip.audit_log(tenant_id, actor, action, entity, entity_key, before, after)
  values (coalesce(new.tenant_id, old.tenant_id), auth.uid(), lower(tg_op), tg_table_name, coalesce(new.code, old.code),
          case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) end,
          case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) end);
  return coalesce(new, old);
end $$;
revoke all on function aip.audit_master_row() from public, anon, authenticated;

-- A controlled value must be a platform default (tenant_id null) or a row of the same tenant.
-- Arguments: pairs of (column, reference table).
create or replace function aip.ref_tenant_guard() returns trigger language plpgsql security definer set search_path = aip, pg_temp as $$
declare
  i int := 0;
  v uuid;
  owner uuid;
  found_row boolean;
begin
  while i < tg_nargs loop
    v := (to_jsonb(new) ->> tg_argv[i])::uuid;
    if v is not null then
      execute format('select true, tenant_id from aip.%I where id = $1', tg_argv[i + 1]) into found_row, owner using v;
      if found_row is null then raise exception '%.%: unknown reference %', tg_table_name, tg_argv[i], v using errcode = '23503'; end if;
      if owner is not null and owner <> new.tenant_id then
        raise exception '%.%: reference % belongs to another tenant', tg_table_name, tg_argv[i], v using errcode = '42501';
      end if;
    end if;
    i := i + 2;
  end loop;
  return new;
end $$;
revoke all on function aip.ref_tenant_guard() from public, anon, authenticated;

-- Creates (idempotently) one master table with the standard columns, row-level security and triggers.
-- Migration-only: executes the supplied column DDL, so no application role may call it.
create or replace function aip.create_master_table(p_name text, p_label text, p_columns text, p_currency char(3), p_writers text[])
returns void language plpgsql set search_path = aip, pg_temp as $fn$
declare
  t text := format('aip.%I', p_name);
begin
  if p_name !~ '^[a-z][a-z0-9_]*$' then raise exception 'invalid master name %', p_name; end if;
  if p_currency is not null and p_currency !~ '^[A-Z]{3}$' then raise exception 'invalid currency %', p_currency; end if;
  execute format(
    'create table if not exists %s (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references aip.tenants(id) on delete cascade, code text not null check (length(code) between 1 and 200), %s%s, is_active boolean not null default true, row_version bigint not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (tenant_id, code), unique (tenant_id, id))',
    t, p_columns,
    case when p_currency is null then '' else format(', currency char(3) not null default %L check (currency ~ ''^[A-Z]{3}$'')', p_currency) end);
  execute format('comment on table %s is %L', t, 'Master: ' || p_label);
  execute format('alter table %s enable row level security', t);
  execute format('drop policy if exists p_read on %s', t);
  execute format('create policy p_read on %s for select to authenticated using (aip.has_role(tenant_id))', t);
  execute format('drop policy if exists p_write on %s', t);
  execute format('create policy p_write on %s for all to authenticated using (aip.has_role(tenant_id, %L::text[])) with check (aip.has_role(tenant_id, %L::text[]))', t, p_writers, p_writers);
  execute format('drop trigger if exists t_audit on %s', t);
  execute format('create trigger t_audit after insert or update or delete on %s for each row execute function aip.audit_master_row()', t);
  execute format('drop trigger if exists t_touch on %s', t);
  execute format('create trigger t_touch before update on %s for each row execute function aip.touch_versioned()', t);
  execute format('grant select, insert, update, delete on %s to authenticated', t);
  execute format('grant all on %s to service_role', t);
end $fn$;
revoke all on function aip.create_master_table(text, text, text, char, text[]) from public;

-- Adds (idempotently) a tenant-safe foreign key (tenant_id, column) → target(tenant_id, id), and its index.
create or replace function aip.ensure_master_fk(p_table text, p_column text, p_target text, p_unique boolean)
returns void language plpgsql set search_path = aip, pg_temp as $fn$
declare
  c text := left('fk_' || p_table || '_' || p_column, 63);
begin
  if not exists (select 1 from pg_constraint where conname = c and conrelid = format('aip.%I', p_table)::regclass) then
    execute format('alter table aip.%I add constraint %I foreign key (tenant_id, %I) references aip.%I (tenant_id, id)', p_table, c, p_column, p_target);
  end if;
  if p_unique then
    execute format('create unique index if not exists %I on aip.%I (tenant_id, %I)', left('ux_' || p_table || '_' || p_column, 63), p_table, p_column);
  else
    execute format('create index if not exists %I on aip.%I (tenant_id, %I)', left('ix_' || p_table || '_' || p_column, 63), p_table, p_column);
  end if;
end $fn$;
revoke all on function aip.ensure_master_fk(text, text, text, boolean) from public;

-- Which workbook rows each master row replaced: the basis of the phase 3 compatibility views.
create table if not exists aip.master_lineage (
  tenant_id uuid not null references aip.tenants(id) on delete cascade,
  master text not null,
  code text not null,
  source_table text not null,
  source_key text not null,
  role text not null check (role in ('primary','merged','extension','derived')),
  loaded_at timestamptz not null default now(),
  primary key (tenant_id, master, code, source_table, source_key)
);
create index if not exists master_lineage_source_idx on aip.master_lineage(tenant_id, source_table, source_key);
alter table aip.master_lineage enable row level security;
drop policy if exists p_read on aip.master_lineage;
create policy p_read on aip.master_lineage for select to authenticated using (aip.has_role(tenant_id));
grant select on aip.master_lineage to authenticated;
grant all on aip.master_lineage to service_role;
`,
  ];
  for (const d of ordered) {
    const cols = d.columns.map((c) => `${q(dbColumn(c))} ${masterPgType(c)}${c.kind === "ref" ? ` references aip.${q(`ref_${c.ref}`)}(id)` : ""}`).join(", ");
    out.push(
      `-- ${d.label}: ${d.description.replace(/\n/g, " ")}`,
      `select aip.create_master_table(${lit(d.name)}, ${lit(d.label)}, $cols$${cols}$cols$, ${hasMoney(d) ? lit(defaultCurrency) : "null"}, array[${writers(d).map(lit).join(",")}]);`,
    );
    // Columns added after a table first shipped (create table if not exists leaves existing tables alone).
    for (const c of d.columns) out.push(`alter table aip.${q(d.name)} add column if not exists ${q(dbColumn(c))} ${masterPgType(c)}${c.kind === "ref" ? ` references aip.${q(`ref_${c.ref}`)}(id)` : ""};`);
    const refs = d.columns.filter((c) => c.kind === "ref");
    out.push(`drop trigger if exists t_ref_guard on aip.${q(d.name)};`);
    if (refs.length) out.push(`create trigger t_ref_guard before insert or update on aip.${q(d.name)} for each row execute function aip.ref_tenant_guard(${refs.map((c) => `${lit(dbColumn(c))}, ${lit(`ref_${c.ref}`)}`).join(", ")});`);
  }
  out.push("", "-- Foreign keys (after every table exists).");
  for (const d of ordered) for (const c of d.columns.filter((x) => x.kind === "fk")) out.push(`select aip.ensure_master_fk(${lit(d.name)}, ${lit(dbColumn(c))}, ${lit(c.fk!)}, ${c.unique ? "true" : "false"});`);
  return out.join("\n") + "\n";
}

// ── Seed ────────────────────────────────────────────────────────────────────

function sqlLiteral(v: unknown): string {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number") {
    if (!Number.isFinite(v)) throw new Error("non-finite number");
    return String(v);
  }
  if (typeof v === "boolean") return v ? "true" : "false";
  return lit(String(v));
}

/**
 * Loads built masters into one tenant: upsert on (tenant_id, code), references resolved by joining on business
 * codes, self-references in a second pass, then lineage. Idempotent.
 */
export function masterSeedSql(masters: BuiltMaster[], tenantId: string, currency: string, chunk = 500): string {
  const T = lit(tenantId);
  const out: string[] = [];
  for (const { def, rows } of masters) {
    if (!rows.length) continue;
    const self = def.columns.filter((c) => c.kind === "fk" && c.fk === def.name);
    const plain = def.columns.filter((c) => !self.includes(c));
    const vcols = ["code", ...plain.map((c) => c.name)];
    const joins: string[] = [];
    const selects: string[] = [T, "v.code"];
    plain.forEach((c, i) => {
      if (c.kind === "fk") {
        joins.push(`left join aip.${q(c.fk!)} j${i} on j${i}.tenant_id = ${T} and j${i}.code = v.${q(c.name)}`);
        selects.push(`j${i}.id`);
      } else if (c.kind === "ref") {
        joins.push(`left join aip.${q(`ref_${c.ref}`)} j${i} on j${i}.tenant_id is null and j${i}.code = v.${q(c.name)}${c.scope ? ` and j${i}.scope = ${lit(c.scope)}` : ""}`);
        selects.push(`j${i}.id`);
      } else selects.push(`v.${q(c.name)}::${masterPgType(c)}`);
    });
    const money = hasMoney(def);
    const target = ["tenant_id", "code", ...plain.map(dbColumn), ...(money ? ["currency"] : [])];
    if (money) selects.push(lit(currency));
    const updates = target.filter((c) => c !== "tenant_id" && c !== "code").map((c) => `${q(c)} = excluded.${q(c)}`);
    for (let i = 0; i < rows.length; i += chunk) {
      const values = rows.slice(i, i + chunk).map((r) => `(${[sqlLiteral(r.code), ...plain.map((c) => sqlLiteral(r.values[c.name]))].join(",")})`);
      out.push(
        `insert into aip.${q(def.name)} (${target.map(q).join(",")})\nselect ${selects.join(", ")}\nfrom (values\n${values.join(",\n")}\n) as v(${vcols.map(q).join(",")})\n${joins.join("\n")}\non conflict (tenant_id, code) do update set ${updates.join(", ")};`,
      );
    }
    for (const c of self) {
      const linked = rows.filter((r) => r.values[c.name] !== null && r.values[c.name] !== undefined);
      for (let i = 0; i < linked.length; i += chunk) {
        const values = linked.slice(i, i + chunk).map((r) => `(${sqlLiteral(r.code)},${sqlLiteral(r.values[c.name])})`);
        out.push(
          `update aip.${q(def.name)} m set ${q(dbColumn(c))} = p.id\nfrom (values\n${values.join(",\n")}\n) as v(code, ref_code)\njoin aip.${q(def.name)} p on p.tenant_id = ${T} and p.code = v.ref_code\nwhere m.tenant_id = ${T} and m.code = v.code and m.${q(dbColumn(c))} is distinct from p.id;`,
        );
      }
    }
  }
  const lineage = masters.flatMap(({ def, rows }) => rows.flatMap((r) => r.lineage.map((l) => `(${T},${lit(def.name)},${sqlLiteral(r.code)},${lit(l.table)},${sqlLiteral(l.key)},${lit(l.role)})`)));
  for (let i = 0; i < lineage.length; i += chunk * 2) {
    out.push(`insert into aip.master_lineage(tenant_id, master, code, source_table, source_key, role) values\n${lineage.slice(i, i + chunk * 2).join(",\n")}\non conflict do nothing;`);
  }
  return out.join("\n") + "\n";
}
