import type { ColumnDef, Registry, TableDef } from "./registry.ts";

const q = (id: string) => `"${id.replace(/"/g, '""')}"`;
const lit = (s: string) => `'${s.replace(/'/g, "''")}'`;

function pgType(c: ColumnDef): string {
  switch (c.kind) {
    case "text":
      return `varchar(${c.maxLength ?? 200})`;
    case "memo":
    case "url":
      return "text";
    case "integer":
      return "integer";
    case "bigint":
      return "bigint";
    case "decimal":
      return `numeric(24,${c.precision ?? 4})`;
    case "money":
      return `numeric(24,${c.precision ?? 2})`;
    case "date":
      return "date";
    case "datetime":
      // Source timestamps are plant-local wall-clock values; kept zone-independent.
      return "timestamp without time zone";
    case "boolean":
      return "boolean";
  }
}

/** Platform objects: tenancy, roles, RLS helpers, audit, FX, license memory, runtime state. */
export function platformSql(defaultCurrency: string): string {
  return `-- Sustantix AIP · platform schema (generated by tools/schema — do not edit by hand)
create extension if not exists pgcrypto;
create schema if not exists aip;
revoke all on schema aip from public;
grant usage on schema aip to authenticated, service_role;

create table if not exists aip.tenants (
  id uuid primary key default gen_random_uuid(),
  name text not null check (length(name) between 1 and 200),
  region text not null default 'IN',
  default_currency char(3) not null default ${lit(defaultCurrency)} check (default_currency ~ '^[A-Z]{3}$'),
  created_at timestamptz not null default now()
);

create table if not exists aip.tenant_members (
  tenant_id uuid not null references aip.tenants(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('viewer','planner','admin')),
  created_at timestamptz not null default now(),
  primary key (tenant_id, user_id)
);
create index if not exists tenant_members_user_idx on aip.tenant_members(user_id);

create or replace function aip.has_role(t uuid, roles text[] default array['viewer','planner','admin'])
returns boolean language sql stable security definer set search_path = aip, pg_temp as $$
  select exists (select 1 from aip.tenant_members m where m.tenant_id = t and m.user_id = auth.uid() and m.role = any(roles));
$$;
revoke all on function aip.has_role(uuid, text[]) from public;
grant execute on function aip.has_role(uuid, text[]) to authenticated;

alter table aip.tenants enable row level security;
alter table aip.tenant_members enable row level security;
drop policy if exists tenants_read on aip.tenants;
create policy tenants_read on aip.tenants for select to authenticated using (aip.has_role(id));
drop policy if exists members_read on aip.tenant_members;
create policy members_read on aip.tenant_members for select to authenticated using (aip.has_role(tenant_id));
drop policy if exists members_admin on aip.tenant_members;
create policy members_admin on aip.tenant_members for all to authenticated
  using (aip.has_role(tenant_id, array['admin'])) with check (aip.has_role(tenant_id, array['admin']));

-- Append-only audit trail for every state transition.
create table if not exists aip.audit_log (
  id bigint generated always as identity primary key,
  tenant_id uuid not null references aip.tenants(id) on delete cascade,
  actor uuid,
  action text not null,
  entity text not null,
  entity_key text,
  before jsonb,
  after jsonb,
  at timestamptz not null default now()
);
create index if not exists audit_log_tenant_at_idx on aip.audit_log(tenant_id, at desc);
alter table aip.audit_log enable row level security;
drop policy if exists audit_read on aip.audit_log;
create policy audit_read on aip.audit_log for select to authenticated using (aip.has_role(tenant_id, array['admin']));

create or replace function aip.audit_log_immutable() returns trigger language plpgsql set search_path = aip, pg_temp as $$
begin
  raise exception 'aip.audit_log is append-only';
end $$;
drop trigger if exists audit_log_no_update on aip.audit_log;
create trigger audit_log_no_update before update or delete on aip.audit_log
  for each row execute function aip.audit_log_immutable();

create or replace function aip.audit_row() returns trigger language plpgsql security definer set search_path = aip, pg_temp as $$
declare
  t uuid := coalesce(new.tenant_id, old.tenant_id);
  k text := coalesce(new.row_key, old.row_key);
begin
  insert into aip.audit_log(tenant_id, actor, action, entity, entity_key, before, after)
  values (t, auth.uid(), lower(tg_op), tg_table_name, k,
          case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) end,
          case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) end);
  return coalesce(new, old);
end $$;
-- Trigger-only: never callable through the API.
revoke all on function aip.audit_row() from public, anon, authenticated;

create or replace function aip.touch_updated_at() returns trigger language plpgsql set search_path = aip, pg_temp as $$
begin
  new.updated_at := now();
  return new;
end $$;

-- Creates (idempotently) one tenant-scoped data-model table with the standard columns,
-- row-level security (viewer read; planner/admin write), audit and updated_at triggers.
-- Migration-only: executes the supplied column DDL, so no application role may call it.
create or replace function aip.create_tenant_table(p_table text, p_sheet text, p_columns text, p_currency char(3) default null)
returns void language plpgsql set search_path = aip, pg_temp as $fn$
declare
  t text := format('aip.%I', p_table);
begin
  if p_currency is not null and p_currency !~ '^[A-Z]{3}$' then raise exception 'invalid currency %', p_currency; end if;
  execute format(
    'create table if not exists %s (tenant_id uuid not null references aip.tenants(id) on delete cascade, row_key text not null, %s%s, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), primary key (tenant_id, row_key))',
    t, p_columns,
    case when p_currency is null then '' else format(', currency char(3) not null default %L check (currency ~ ''^[A-Z]{3}$'')', p_currency) end);
  -- The sheet's own row order (screens list rows in workbook order).
  execute format('alter table %s add column if not exists source_ordinal integer', t);
  execute format('comment on table %s is %L', t, 'Workbook sheet "' || p_sheet || '"');
  execute format('alter table %s enable row level security', t);
  execute format('drop policy if exists p_read on %s', t);
  execute format('create policy p_read on %s for select to authenticated using (aip.has_role(tenant_id))', t);
  execute format('drop policy if exists p_write on %s', t);
  execute format('create policy p_write on %s for all to authenticated using (aip.has_role(tenant_id, array[''planner'',''admin''])) with check (aip.has_role(tenant_id, array[''planner'',''admin'']))', t);
  execute format('drop trigger if exists t_audit on %s', t);
  execute format('create trigger t_audit after insert or update or delete on %s for each row execute function aip.audit_row()', t);
  execute format('drop trigger if exists t_touch on %s', t);
  execute format('create trigger t_touch before update on %s for each row execute function aip.touch_updated_at()', t);
end $fn$;
revoke all on function aip.create_tenant_table(text, text, text, char) from public;

-- Daily FX rates for multi-currency reporting (rate: 1 base = rate quote).
create table if not exists aip.fx_rates (
  rate_date date not null,
  base char(3) not null check (base ~ '^[A-Z]{3}$'),
  quote char(3) not null check (quote ~ '^[A-Z]{3}$'),
  rate numeric(24,10) not null check (rate > 0),
  source text not null,
  primary key (rate_date, base, quote)
);
alter table aip.fx_rates enable row level security;
drop policy if exists fx_read on aip.fx_rates;
create policy fx_read on aip.fx_rates for select to authenticated using (true);

-- Workbook-import snapshot consumed by the AIP runtime (gzip JSON).
create table if not exists aip.runtime_state (
  tenant_id uuid primary key references aip.tenants(id) on delete cascade,
  payload bytea not null,
  bytes integer not null,
  sha256 text not null,
  updated_by uuid,
  updated_at timestamptz not null default now()
);
alter table aip.runtime_state enable row level security;
drop policy if exists runtime_state_read on aip.runtime_state;
create policy runtime_state_read on aip.runtime_state for select to authenticated using (aip.has_role(tenant_id));
drop policy if exists runtime_state_write on aip.runtime_state;
create policy runtime_state_write on aip.runtime_state for all to authenticated
  using (aip.has_role(tenant_id, array['admin'])) with check (aip.has_role(tenant_id, array['admin']));

-- License anti-rollback memory: written by the server (service role) only.
create table if not exists aip.license_clock (
  lid text primary key,
  first_seen bigint not null,
  last_seen bigint not null,
  verdict text not null,
  updated_at timestamptz not null default now()
);
alter table aip.license_clock enable row level security;

grant select, insert, update, delete on all tables in schema aip to authenticated;
grant all on all tables in schema aip to service_role;
revoke insert, update, delete on aip.audit_log from authenticated;
revoke all on aip.license_clock from authenticated;
`;
}

function tableSql(t: TableDef, defaultCurrency: string): string {
  const moneyCurrency = t.columns.some((c) => c.kind === "money") ? (t.columns.find((c) => c.kind === "money")?.currency ?? defaultCurrency) : null;
  const cols = t.columns.map((c) => `${q(c.name)} ${pgType(c)}`).join(", ");
  const key = t.key.length ? `key: ${t.key.join(" + ")}` : "synthetic row key";
  return `-- ${t.sheet} · ${t.domain} · ${key}
select aip.create_tenant_table(${lit(t.name)}, ${lit(t.sheet)}, $cols$${cols}$cols$, ${moneyCurrency ? lit(moneyCurrency) : "null"});`;
}

export function dataModelSql(reg: Registry): string {
  return (
    `-- Sustantix AIP · governed data model from ${reg.source} (sha256 ${reg.sourceSha256.slice(0, 12)}…)\n-- Generated by tools/schema — do not edit by hand.\n` +
    reg.tables.map((t) => tableSql(t, reg.defaultCurrency)).join("\n") +
    `\n\ngrant select, insert, update, delete on all tables in schema aip to authenticated;\ngrant all on all tables in schema aip to service_role;\nrevoke insert, update, delete on aip.audit_log from authenticated;\nrevoke all on aip.license_clock from authenticated;\n`
  );
}
