/**
 * Builds the runtime catalogue and writes what it decided, for review and for the database:
 *   tsx src/runtime-catalogue-cli.ts        → schema/runtime-sheets.json, docs/data/runtime-sheets.md
 * The governed sheets (and their columns) are the governed workbook built from the reference workbook, exactly as the
 * host serves it (sheets above the governed workbook's row limit are not served, so their copies stay catalogue sheets).
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { governedWorkbook } from "./compat.ts";
import { loadCorrections } from "./corrections.ts";
import { buildMasters } from "./masters.ts";
import { loadVocabulary } from "./reference.ts";
import type { Registry } from "./registry.ts";
import { readSheets } from "./rows.ts";
import { buildCatalogue, type Catalogue } from "./runtime-catalogue.ts";
import type { Json } from "../../../packages/host-bridge/src/dataset-parts.ts";
import { GOVERNED_MAX_ROWS } from "./workbook-format.ts";

/** The runtime's tenant datasets (every bundled dataset that is not product content), in manifest order, with labels. */
export function runtimeDatasets(root: string): Array<{ id: string; label: string; value: Json }> {
  const src = join(root, "apps/runtime/src");
  const manifest = JSON.parse(readFileSync(join(src, "manifest.json"), "utf8")) as { datasets: Record<string, unknown> };
  const classes = JSON.parse(readFileSync(join(src, "../dataset-classes.json"), "utf8")) as { product: Record<string, string>; tenant: Record<string, string> };
  return Object.keys(manifest.datasets)
    .filter((id) => !(id in classes.product))
    .map((id) => {
      const label = classes.tenant[id];
      if (!label) throw new Error(`dataset ${id} is neither product content nor a labelled tenant dataset (apps/runtime/dataset-classes.json)`);
      return { id, label, value: JSON.parse(readFileSync(join(src, "data", `${id}.json`), "utf8")) as Json };
    });
}

/** Columns of every sheet the governed workbook serves. */
export function governedColumns(root: string): Record<string, string[]> {
  const reg = JSON.parse(readFileSync(join(root, "schema/aip-data-model.json"), "utf8")) as Registry;
  const raw = readSheets(readFileSync(join(root, "reference/AIP_Data_v915.xlsx")));
  const vocab = loadVocabulary(root);
  const corrections = loadCorrections(root);
  const g = governedWorkbook(reg, raw, buildMasters(reg, raw, vocab, corrections), vocab, corrections, { maxRows: GOVERNED_MAX_ROWS });
  const out: Record<string, string[]> = {};
  for (const [sheet, rows] of Object.entries(g.sheets)) {
    const cols = new Set<string>();
    for (const r of rows as Array<Record<string, unknown>>) for (const k of Object.keys(r)) cols.add(k);
    if (cols.size) out[sheet] = [...cols];
  }
  return out;
}

export function buildRuntimeCatalogue(root: string): Catalogue {
  return buildCatalogue(runtimeDatasets(root), governedColumns(root));
}

/** What is recorded for review: where every table of every dataset is held (no data). */
export function catalogueMap(c: Catalogue) {
  return {
    version: 1,
    about: "Generated by tools/schema (src/runtime-catalogue-cli.ts): where each table of the runtime's tenant datasets is held. Regenerate after a runtime or governed-schema change; CI checks it is current.",
    datasets: c.datasets.map((d) => ({ id: d.id, label: d.label })),
    governed: c.governed,
    sheets: c.sheets.map((s) => ({ name: s.name, rows: s.rows.length, ...(s.groups ? { groups: s.groups.length } : {}), usedBy: s.usedBy })),
  };
}

export function catalogueReport(c: Catalogue): string {
  const refs = c.governed.reduce((n, g) => n + g.usedBy.length, 0);
  const tables = refs + c.sheets.reduce((n, s) => n + s.usedBy.length, 0);
  const lines = [
    "# Runtime catalogue",
    "",
    "Generated by `pnpm --filter @sustantix/schema runtime:catalogue`; do not edit by hand.",
    "",
    `The runtime's ${c.datasets.length} tenant datasets hold ${tables} tables. Each is held once, by name:`,
    "",
    `- **${refs} tables read ${c.governed.length} governed sheets.** They are copies of a governed workbook sheet, so they are not stored again: the dataset reads the governed sheet (its own columns, in its order), and edits made to the governed tables reach every screen.`,
    `- **The other ${tables - refs} tables are ${c.sheets.length} catalogue sheets** in \`aip.runtime_sheet\`: each distinct table once, whichever datasets carry it. ${c.sheets.filter((s) => s.groups).length} of them hold a family of like lists (the same list kept per decision, per asset…) as one sheet grouped by that key.`,
    "- **Each dataset keeps only its layout** (`aip.runtime_dataset`): its structure and values, with references in place of tables.",
    "",
    "Read any sheet in SQL: `select ordinal, group_key, record from aip.runtime_sheet_rows where sheet = '<name>' order by ordinal;`",
    "",
    "## Datasets",
    "",
    "| Dataset | Id |",
    "|---|---|",
    ...c.datasets.map((d) => `| ${d.label} | \`${d.id}\` |`),
    "",
    "## Governed sheets read by the datasets",
    "",
    "| Governed sheet | Read by |",
    "|---|---|",
    ...c.governed.map((g) => `| ${g.sheet} | ${g.usedBy.map((u) => `\`${u}\``).join("<br>")} |`),
    "",
    "## Catalogue sheets",
    "",
    "| Sheet | Rows | Holds |",
    "|---|---|---|",
    ...c.sheets.map((s) => `| ${s.name.replace(/\|/g, "\\|")} | ${s.rows.length}${s.groups ? ` (${s.groups.length} groups)` : ""} | ${s.usedBy.slice(0, 6).map((u) => `\`${u.replace(/\|/g, "\\|")}\``).join("<br>")}${s.usedBy.length > 6 ? `<br>… ${s.usedBy.length - 6} more` : ""} |`),
    "",
  ];
  return lines.join("\n");
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const root = fileURLToPath(new URL("../../../", import.meta.url));
  const c = buildRuntimeCatalogue(root);
  writeFileSync(join(root, "schema/runtime-sheets.json"), JSON.stringify(catalogueMap(c), null, 1) + "\n");
  mkdirSync(join(root, "docs/data"), { recursive: true });
  writeFileSync(join(root, "docs/data/runtime-sheets.md"), catalogueReport(c));
  console.log(`runtime catalogue: ${c.datasets.length} datasets · ${c.governed.length} governed sheets read · ${c.sheets.length} catalogue sheets`);
}
