-- Sustantix AIP · phase 5: outbox and signed webhook delivery
-- Generated by tools/schema from src/outbox-sql.ts — do not edit by hand.

-- Where events go. The signing secret is readable only by the delivery worker (service role).
create table if not exists aip.outbox_destination (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references aip.tenants(id) on delete cascade,
  name text not null check (name ~ '^[A-Za-z0-9][A-Za-z0-9 ._-]{0,79}$'),
  url text not null check (url ~ '^https://[^/?#@\s]+(/[^\s]*)?$' and length(url) <= 500),
  events text[] not null default array['change','proposal'] check (events <@ array['change','proposal']),
  entities text[] not null default '{}',
  secret text not null check (length(secret) >= 32),
  enabled boolean not null default true,
  created_by uuid,
  created_at timestamptz not null default now(),
  unique (tenant_id, name)
);
alter table aip.outbox_destination enable row level security;
drop policy if exists p_read on aip.outbox_destination;
create policy p_read on aip.outbox_destination for select to authenticated using (aip.has_role(tenant_id, array['admin']));
drop policy if exists p_update on aip.outbox_destination;
create policy p_update on aip.outbox_destination for update to authenticated using (aip.has_role(tenant_id, array['admin'])) with check (aip.has_role(tenant_id, array['admin']));
revoke all on aip.outbox_destination from authenticated;
grant select (id, tenant_id, name, url, events, entities, enabled, created_by, created_at), update (enabled, events, entities) on aip.outbox_destination to authenticated;
grant all on aip.outbox_destination to service_role;

-- One row per event and destination. event_id is the idempotency key the receiver sees.
create table if not exists aip.outbox (
  id bigint generated always as identity primary key,
  tenant_id uuid not null references aip.tenants(id) on delete cascade,
  destination_id uuid not null references aip.outbox_destination(id) on delete cascade,
  event_id uuid not null default gen_random_uuid(),
  kind text not null check (kind in ('change','proposal')),
  event text not null,
  entity text not null,
  code text not null,
  payload jsonb not null,
  status text not null default 'pending' check (status in ('pending','sending','delivered','failed','dead')),
  attempts integer not null default 0,
  next_attempt_at timestamptz not null default now(),
  lease_until timestamptz,
  last_error text,
  delivered_at timestamptz,
  created_at timestamptz not null default now(),
  unique (destination_id, event_id)
);
create index if not exists outbox_due_idx on aip.outbox(next_attempt_at) where status in ('pending','failed','sending');
alter table aip.outbox enable row level security;
drop policy if exists p_read on aip.outbox;
create policy p_read on aip.outbox for select to authenticated using (aip.has_role(tenant_id, array['admin']));
revoke all on aip.outbox from authenticated;
grant select on aip.outbox to authenticated;
grant all on aip.outbox to service_role;

drop view if exists aip.v_outbox;
create view aip.v_outbox with (security_invoker = true) as
select o.id::text as code, o.tenant_id, d.name as destination, o.event, o.entity, o.code as record, o.status, o.attempts,
       o.next_attempt_at, o.last_error, o.delivered_at, o.created_at, o.event_id::text as event_id
from aip.outbox o join aip.outbox_destination d on d.id = o.destination_id;
grant select on aip.v_outbox to authenticated, service_role;

-- Same transaction as the change: one event per applied item, per subscribed destination, with the record as stored.
create or replace function aip.outbox_change_set() returns trigger language plpgsql security definer set search_path = aip, pg_temp as $$
declare
  item jsonb;
  rec jsonb;
begin
  if not exists (select 1 from aip.outbox_destination d where d.tenant_id = new.tenant_id and d.enabled and 'change' = any(d.events)) then
    return new;
  end if;
  for item in select value from jsonb_array_elements(new.result) loop
    rec := null;
    if item->>'op' <> 'delete' then
      begin
        execute format('select to_jsonb(v) - ''tenant_id'' from aip.%I v where v.tenant_id = $1 and v.code = $2', 'v_' || (item->>'entity')) into rec using new.tenant_id, item->>'code';
      exception when undefined_table then rec := null;
      end;
    end if;
    insert into aip.outbox(tenant_id, destination_id, kind, event, entity, code, payload)
    select new.tenant_id, d.id, 'change', (item->>'entity') || '.' || (item->>'op'), item->>'entity', item->>'code',
           jsonb_build_object('changeSet', new.id, 'source', new.source, 'actor', new.actor, 'appliedAt', new.applied_at,
                              'entity', item->>'entity', 'op', item->>'op', 'code', item->>'code', 'rowVersion', item->'rowVersion', 'record', rec)
    from aip.outbox_destination d
    where d.tenant_id = new.tenant_id and d.enabled and 'change' = any(d.events) and (cardinality(d.entities) = 0 or (item->>'entity') = any(d.entities));
  end loop;
  return new;
end $$;
revoke all on function aip.outbox_change_set() from public, anon, authenticated;
drop trigger if exists t_outbox on aip.change_set;
create trigger t_outbox after insert on aip.change_set for each row execute function aip.outbox_change_set();

-- A proposal a person approved (and its outcome) goes to the ERP/EAM that carries it out.
create or replace function aip.outbox_proposal() returns trigger language plpgsql security definer set search_path = aip, pg_temp as $$
begin
  if new.status is not distinct from old.status or new.status not in ('approved','applied') then return new; end if;
  insert into aip.outbox(tenant_id, destination_id, kind, event, entity, code, payload)
  select new.tenant_id, d.id, 'proposal', 'proposal.' || new.status, new.proposal_type, new.code,
         jsonb_build_object('proposal', new.code, 'type', new.proposal_type, 'status', new.status, 'subject', jsonb_build_object('type', new.subject_type, 'code', new.subject_code),
                            'title', new.title, 'payload', new.payload, 'decidedBy', new.decided_by, 'decidedAt', new.decided_at, 'appliedRef', new.applied_ref)
  from aip.outbox_destination d
  where d.tenant_id = new.tenant_id and d.enabled and 'proposal' = any(d.events) and (cardinality(d.entities) = 0 or new.proposal_type = any(d.entities));
  return new;
end $$;
revoke all on function aip.outbox_proposal() from public, anon, authenticated;
drop trigger if exists t_outbox on aip.agent_proposal;
create trigger t_outbox after update on aip.agent_proposal for each row execute function aip.outbox_proposal();

-- The worker claims due events with a lease, so two workers never send the same event at once.
create or replace function aip.claim_outbox(p_limit integer) returns setof aip.outbox language plpgsql security definer set search_path = aip, pg_temp as $$
begin
  return query
  update aip.outbox o set status = 'sending', lease_until = now() + interval '2 minutes', attempts = o.attempts + 1
  where o.id in (
    select x.id from aip.outbox x
    where (x.status in ('pending','failed') and x.next_attempt_at <= now()) or (x.status = 'sending' and x.lease_until < now())
    order by x.next_attempt_at, x.id
    limit greatest(1, least(p_limit, 200))
    for update skip locked)
  returning o.*;
end $$;
revoke all on function aip.claim_outbox(integer) from public, anon, authenticated;
grant execute on function aip.claim_outbox(integer) to service_role;

-- Records the outcome of one attempt: delivered, or failed with back-off, or dead after 8 attempts.
create or replace function aip.complete_outbox(p_id bigint, p_ok boolean, p_error text) returns void language plpgsql security definer set search_path = aip, pg_temp as $$
declare
  backoff int[] := array[60,300,1800,7200,43200,86400];
begin
  update aip.outbox o set
    status = case when p_ok then 'delivered' when o.attempts >= 8 then 'dead' else 'failed' end,
    delivered_at = case when p_ok then now() end,
    last_error = case when p_ok then null else left(p_error, 500) end,
    lease_until = null,
    next_attempt_at = case when p_ok then o.next_attempt_at else now() + make_interval(secs => backoff[least(o.attempts, array_length(backoff, 1))]) end
  where o.id = p_id and o.status = 'sending';
end $$;
revoke all on function aip.complete_outbox(bigint, boolean, text) from public, anon, authenticated;
grant execute on function aip.complete_outbox(bigint, boolean, text) to service_role;

-- An administrator sends failed or set-aside events again.
create or replace function aip.retry_outbox(p_tenant uuid, p_ids bigint[]) returns integer language plpgsql security definer set search_path = aip, pg_temp as $$
declare
  n integer;
begin
  if not aip.has_role(p_tenant, array['admin']) then raise exception 'only administrators retry deliveries' using errcode = '42501'; end if;
  update aip.outbox set status = 'pending', next_attempt_at = now(), attempts = 0, last_error = null
  where tenant_id = p_tenant and id = any(p_ids) and status in ('failed','dead');
  get diagnostics n = row_count;
  return n;
end $$;
revoke all on function aip.retry_outbox(uuid, bigint[]) from public, anon;
grant execute on function aip.retry_outbox(uuid, bigint[]) to authenticated;
