-- Sustantix AIP · the runtime catalogue: each runtime dataset's layout and every sheet it uses, once, by name
-- Generated by tools/schema from src/datasets-sql.ts — do not edit by hand.

-- The first store (one entry per table, duplicates included) is replaced.
drop function if exists aip.dataset_blocks(uuid, jsonb);
drop table if exists aip.dataset_block;
drop table if exists aip.dataset_part;

create table if not exists aip.runtime_dataset (
  tenant_id uuid not null references aip.tenants(id) on delete cascade,
  dataset text not null check (dataset ~ '^[0-9a-f]{16}$'),
  label text not null check (length(label) between 1 and 200),
  layout json not null,
  bytes integer not null check (bytes > 0),
  updated_at timestamptz not null default now(),
  primary key (tenant_id, dataset)
);

create table if not exists aip.runtime_sheet (
  tenant_id uuid not null references aip.tenants(id) on delete cascade,
  sheet text not null check (length(sheet) between 1 and 300),
  row_count integer not null check (row_count >= 0),
  bytes bigint not null check (bytes >= 0),
  -- Where the sheet is used: "<dataset label> <JSON Pointer>" of each table it holds.
  used_by text[] not null default '{}',
  updated_at timestamptz not null default now(),
  primary key (tenant_id, sheet)
);

create table if not exists aip.runtime_sheet_group (
  tenant_id uuid not null,
  sheet text not null,
  group_key text not null,
  first_ordinal integer not null check (first_ordinal >= 0),
  row_count integer not null check (row_count >= 0),
  primary key (tenant_id, sheet, group_key),
  foreign key (tenant_id, sheet) references aip.runtime_sheet(tenant_id, sheet) on delete cascade
);

create table if not exists aip.runtime_sheet_block (
  tenant_id uuid not null,
  sheet text not null,
  first_ordinal integer not null check (first_ordinal >= 0),
  row_count integer not null check (row_count > 0),
  bytes integer not null check (bytes > 0),
  rows json not null,
  primary key (tenant_id, sheet, first_ordinal),
  foreign key (tenant_id, sheet) references aip.runtime_sheet(tenant_id, sheet) on delete cascade
);
alter table aip.runtime_sheet_block alter column rows set compression lz4;

alter table aip.runtime_dataset enable row level security;
drop policy if exists p_read on aip.runtime_dataset;
create policy p_read on aip.runtime_dataset for select to authenticated using (aip.has_role(tenant_id));
alter table aip.runtime_sheet enable row level security;
drop policy if exists p_read on aip.runtime_sheet;
create policy p_read on aip.runtime_sheet for select to authenticated using (aip.has_role(tenant_id));
alter table aip.runtime_sheet_group enable row level security;
drop policy if exists p_read on aip.runtime_sheet_group;
create policy p_read on aip.runtime_sheet_group for select to authenticated using (aip.has_role(tenant_id));
alter table aip.runtime_sheet_block enable row level security;
drop policy if exists p_read on aip.runtime_sheet_block;
create policy p_read on aip.runtime_sheet_block for select to authenticated using (aip.has_role(tenant_id));
-- Read-only for members: writes come from the seed or the server.
revoke all on aip.runtime_dataset, aip.runtime_sheet, aip.runtime_sheet_group, aip.runtime_sheet_block from authenticated;
grant select on aip.runtime_dataset, aip.runtime_sheet, aip.runtime_sheet_group, aip.runtime_sheet_block to authenticated;
grant all on aip.runtime_dataset, aip.runtime_sheet, aip.runtime_sheet_group, aip.runtime_sheet_block to service_role;

-- One record per row, for reading a sheet in SQL (the caller's rights apply).
create or replace view aip.runtime_sheet_rows with (security_invoker = true) as
  select b.tenant_id, b.sheet, b.first_ordinal + e.n::integer - 1 as ordinal, g.group_key, e.record
  from aip.runtime_sheet_block b
  cross join lateral json_array_elements(b.rows) with ordinality as e(record, n)
  left join aip.runtime_sheet_group g
    on g.tenant_id = b.tenant_id and g.sheet = b.sheet
   and b.first_ordinal + e.n::integer - 1 >= g.first_ordinal and b.first_ordinal + e.n::integer - 1 < g.first_ordinal + g.row_count;
grant select on aip.runtime_sheet_rows to authenticated;

-- One audit entry per statement and tenant: which datasets or sheets, and how many entries, were written or removed.
create or replace function aip.audit_runtime_write() returns trigger language plpgsql security definer set search_path = aip, pg_temp as $$
begin
  if tg_op = 'DELETE' then
    insert into aip.audit_log(tenant_id, actor, action, entity, entity_key, before, after)
    select o.tenant_id, auth.uid(), 'delete', tg_table_name, null, jsonb_build_object('records', count(*)), null
    from old_rows o group by o.tenant_id;
  else
    insert into aip.audit_log(tenant_id, actor, action, entity, entity_key, before, after)
    select n.tenant_id, auth.uid(), lower(tg_op), tg_table_name, null, null, jsonb_build_object('records', count(*))
    from new_rows n group by n.tenant_id;
  end if;
  return null;
end $$;
revoke all on function aip.audit_runtime_write() from public, anon, authenticated;
drop trigger if exists t_audit_insert on aip.runtime_dataset;
create trigger t_audit_insert after insert on aip.runtime_dataset referencing new table as new_rows for each statement execute function aip.audit_runtime_write();
drop trigger if exists t_audit_update on aip.runtime_dataset;
create trigger t_audit_update after update on aip.runtime_dataset referencing new table as new_rows for each statement execute function aip.audit_runtime_write();
drop trigger if exists t_audit_delete on aip.runtime_dataset;
create trigger t_audit_delete after delete on aip.runtime_dataset referencing old table as old_rows for each statement execute function aip.audit_runtime_write();
drop trigger if exists t_audit_insert on aip.runtime_sheet;
create trigger t_audit_insert after insert on aip.runtime_sheet referencing new table as new_rows for each statement execute function aip.audit_runtime_write();
drop trigger if exists t_audit_update on aip.runtime_sheet;
create trigger t_audit_update after update on aip.runtime_sheet referencing new table as new_rows for each statement execute function aip.audit_runtime_write();
drop trigger if exists t_audit_delete on aip.runtime_sheet;
create trigger t_audit_delete after delete on aip.runtime_sheet referencing old table as old_rows for each statement execute function aip.audit_runtime_write();
drop trigger if exists t_audit_insert on aip.runtime_sheet_group;
create trigger t_audit_insert after insert on aip.runtime_sheet_group referencing new table as new_rows for each statement execute function aip.audit_runtime_write();
drop trigger if exists t_audit_update on aip.runtime_sheet_group;
create trigger t_audit_update after update on aip.runtime_sheet_group referencing new table as new_rows for each statement execute function aip.audit_runtime_write();
drop trigger if exists t_audit_delete on aip.runtime_sheet_group;
create trigger t_audit_delete after delete on aip.runtime_sheet_group referencing old table as old_rows for each statement execute function aip.audit_runtime_write();
drop trigger if exists t_audit_insert on aip.runtime_sheet_block;
create trigger t_audit_insert after insert on aip.runtime_sheet_block referencing new table as new_rows for each statement execute function aip.audit_runtime_write();
drop trigger if exists t_audit_update on aip.runtime_sheet_block;
create trigger t_audit_update after update on aip.runtime_sheet_block referencing new table as new_rows for each statement execute function aip.audit_runtime_write();
drop trigger if exists t_audit_delete on aip.runtime_sheet_block;
create trigger t_audit_delete after delete on aip.runtime_sheet_block referencing old table as old_rows for each statement execute function aip.audit_runtime_write();

-- Several blocks in one call: p_blocks is [{"s": sheet, "f": first_ordinal}, …]; the answer is each block's rows (a json
-- array, as stored), in the order asked; a block the caller may not read answers null.
create or replace function aip.runtime_sheet_blocks(p_tenant uuid, p_blocks jsonb)
returns json language sql stable security invoker set search_path = aip, pg_temp as $$
  select coalesce(json_agg((
    select b.rows from aip.runtime_sheet_block b
    where b.tenant_id = p_tenant and b.sheet = s.value->>'s' and b.first_ordinal = (s.value->>'f')::integer
  ) order by s.ordinality), '[]'::json)
  from jsonb_array_elements(p_blocks) with ordinality as s(value, ordinality);
$$;
revoke all on function aip.runtime_sheet_blocks(uuid, jsonb) from public, anon;
grant execute on function aip.runtime_sheet_blocks(uuid, jsonb) to authenticated, service_role;
