-- Sustantix AIP · agents (runs, steps, proposals)
-- Generated by tools/schema — do not edit by hand.

create table if not exists aip.agent_run (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references aip.tenants(id) on delete cascade,
  code text not null check (length(code) between 1 and 200),
  agent text not null check (agent ~ '^[a-z][a-z0-9-]*$'),
  user_id uuid not null,
  model text not null,
  status text not null check (status in ('running','completed','failed','stopped')),
  question text,
  reply text,
  steps integer not null default 0,
  input_tokens integer not null default 0,
  output_tokens integer not null default 0,
  message text,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  row_version bigint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, code),
  unique (tenant_id, id)
);
create index if not exists agent_run_user_idx on aip.agent_run(tenant_id, user_id, started_at desc);
alter table aip.agent_run enable row level security;
-- Members read their own runs; administrators read every run of the tenant.
drop policy if exists p_read on aip.agent_run;
create policy p_read on aip.agent_run for select to authenticated using (aip.has_role(tenant_id) and (user_id = auth.uid() or aip.has_role(tenant_id, array['admin'])));
drop policy if exists p_insert on aip.agent_run;
create policy p_insert on aip.agent_run for insert to authenticated with check (aip.has_role(tenant_id) and user_id = auth.uid());
drop policy if exists p_update on aip.agent_run;
create policy p_update on aip.agent_run for update to authenticated using (aip.has_role(tenant_id) and user_id = auth.uid()) with check (aip.has_role(tenant_id) and user_id = auth.uid());
drop trigger if exists t_audit on aip.agent_run;
create trigger t_audit after insert or update or delete on aip.agent_run for each row execute function aip.audit_master_row();
drop trigger if exists t_touch on aip.agent_run;
create trigger t_touch before update on aip.agent_run for each row execute function aip.touch_versioned();

create table if not exists aip.agent_step (
  id bigint generated always as identity primary key,
  tenant_id uuid not null references aip.tenants(id) on delete cascade,
  run_id uuid not null,
  seq integer not null check (seq >= 0),
  kind text not null check (kind in ('tool_call','tool_result','reply','guardrail')),
  tool text,
  payload jsonb,
  created_at timestamptz not null default now(),
  constraint fk_agent_step_run foreign key (tenant_id, run_id) references aip.agent_run (tenant_id, id) on delete cascade,
  unique (run_id, seq)
);
alter table aip.agent_step enable row level security;
drop policy if exists p_read on aip.agent_step;
create policy p_read on aip.agent_step for select to authenticated
  using (exists (select 1 from aip.agent_run r where r.id = run_id and r.tenant_id = agent_step.tenant_id));
drop policy if exists p_insert on aip.agent_step;
create policy p_insert on aip.agent_step for insert to authenticated
  with check (exists (select 1 from aip.agent_run r where r.id = run_id and r.tenant_id = agent_step.tenant_id and r.user_id = auth.uid()));

create or replace function aip.audit_agent_steps() returns trigger language plpgsql security definer set search_path = aip, pg_temp as $$
begin
  insert into aip.audit_log(tenant_id, actor, action, entity, entity_key, after)
  select n.tenant_id, auth.uid(), 'insert', 'agent_step', n.run_id::text, jsonb_build_object('steps', count(*), 'tools', jsonb_agg(distinct n.tool) filter (where n.tool is not null))
  from new_rows n group by n.tenant_id, n.run_id;
  return null;
end $$;
revoke all on function aip.audit_agent_steps() from public, anon, authenticated;
drop trigger if exists t_audit on aip.agent_step;
create trigger t_audit after insert on aip.agent_step referencing new table as new_rows for each statement execute function aip.audit_agent_steps();

create table if not exists aip.agent_proposal (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references aip.tenants(id) on delete cascade,
  code text not null check (length(code) between 1 and 200),
  agent text not null,
  run_id uuid,
  proposal_type text not null check (proposal_type in ('intervention','inspection','intervention_update','purchase_requisition','stock_transfer','warranty_claim','data_correction_request','disclosure_draft','notification')),
  subject_type text not null,
  subject_code text not null,
  title text not null check (length(title) between 1 and 300),
  rationale text not null,
  payload jsonb not null default '{}'::jsonb,
  evidence jsonb not null default '[]'::jsonb,
  status text not null default 'pending' check (status in ('pending','approved','rejected','applied','failed')),
  proposed_by uuid not null,
  decided_by uuid,
  decided_at timestamptz,
  decision_note text,
  applied_ref text,
  row_version bigint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, code),
  constraint fk_agent_proposal_run foreign key (tenant_id, run_id) references aip.agent_run (tenant_id, id) on delete set null (run_id)
);
create index if not exists agent_proposal_status_idx on aip.agent_proposal(tenant_id, status, created_at desc);
alter table aip.agent_proposal enable row level security;
drop policy if exists p_read on aip.agent_proposal;
create policy p_read on aip.agent_proposal for select to authenticated using (aip.has_role(tenant_id));
drop policy if exists p_insert on aip.agent_proposal;
create policy p_insert on aip.agent_proposal for insert to authenticated
  with check (aip.has_role(tenant_id, array['planner','admin']) and proposed_by = auth.uid() and status = 'pending' and decided_by is null);
drop policy if exists p_decide on aip.agent_proposal;
create policy p_decide on aip.agent_proposal for update to authenticated
  using (aip.has_role(tenant_id, array['planner','admin'])) with check (aip.has_role(tenant_id, array['planner','admin']));
drop trigger if exists t_audit on aip.agent_proposal;
create trigger t_audit after insert or update or delete on aip.agent_proposal for each row execute function aip.audit_master_row();
drop trigger if exists t_touch on aip.agent_proposal;
create trigger t_touch before update on aip.agent_proposal for each row execute function aip.touch_versioned();

-- Decisions are one-way: pending → approved | rejected; approved → applied | failed. Nothing else changes after.
create or replace function aip.agent_proposal_transition() returns trigger language plpgsql set search_path = aip, pg_temp as $$
begin
  if (old.status, new.status) not in (('pending','approved'),('pending','rejected'),('approved','applied'),('approved','failed'),('pending','pending')) then
    raise exception 'proposal % cannot move from % to %', old.code, old.status, new.status using errcode = '23514';
  end if;
  if new.proposal_type <> old.proposal_type or new.payload <> old.payload or new.subject_code <> old.subject_code or new.proposed_by <> old.proposed_by then
    raise exception 'proposal % content is immutable', old.code using errcode = '23514';
  end if;
  if old.status = 'pending' and new.status in ('approved','rejected') then
    if new.decided_by is distinct from auth.uid() then raise exception 'decision must be recorded by the deciding user' using errcode = '42501'; end if;
    new.decided_at := now();
  end if;
  return new;
end $$;
drop trigger if exists t_transition on aip.agent_proposal;
create trigger t_transition before update on aip.agent_proposal for each row execute function aip.agent_proposal_transition();

-- Applies an approved proposal with the caller's own permissions (security invoker: RLS decides). Interventions
-- and inspections become intervention-register rows under review; reschedules update the intervention; every
-- other type stays approved for downstream systems (ERP, notifications) to act on.
create or replace function aip.apply_agent_proposal(p_id uuid) returns text language plpgsql security invoker set search_path = aip, pg_temp as $$
declare
  p aip.agent_proposal;
  a record;
  ref text;
  n int;
begin
  select * into p from aip.agent_proposal where id = p_id for update;
  if not found then raise exception 'proposal not found' using errcode = 'P0002'; end if;
  if p.status <> 'approved' then raise exception 'proposal % is %, not approved', p.code, p.status using errcode = '23514'; end if;
  if p.proposal_type in ('intervention', 'inspection') then
    select m.id, m.site_id into a from aip.asset m where m.tenant_id = p.tenant_id and m.code = p.payload ->> 'asset';
    if not found then
      update aip.agent_proposal set status = 'failed', decision_note = coalesce(decision_note || ' · ', '') || 'asset not found' where id = p_id;
      return null;
    end if;
    ref := 'AGT-' || p.code;
    insert into aip.intervention(tenant_id, code, site_id, asset_id, maintenance_type_id, description, priority_id, required_by, duration_hours, planning_status_id, source_record)
    values (
      p.tenant_id, ref, a.site_id, a.id,
      (select r.id from aip.ref_maintenance_type r where r.tenant_id is null and r.code = case when p.proposal_type = 'inspection' then 'INSPECTION' else p.payload ->> 'maintenance_type' end),
      p.payload ->> 'description',
      (select r.id from aip.ref_priority r where r.tenant_id is null and r.code = p.payload ->> 'priority'),
      (p.payload ->> 'required_by')::timestamp,
      (p.payload ->> 'duration_hours')::numeric,
      (select r.id from aip.ref_status r where r.tenant_id is null and r.scope = 'intervention' and r.code = 'UNDER_REVIEW'),
      'Agent proposal ' || p.code || ' (' || p.agent || ')');
  elsif p.proposal_type = 'intervention_update' then
    update aip.intervention i set
      planned_start = coalesce((p.payload -> 'changes' ->> 'planned_start')::timestamp, i.planned_start),
      planned_finish = coalesce((p.payload -> 'changes' ->> 'planned_finish')::timestamp, i.planned_finish),
      priority_id = coalesce((select r.id from aip.ref_priority r where r.tenant_id is null and r.code = p.payload -> 'changes' ->> 'priority'), i.priority_id)
    where i.tenant_id = p.tenant_id and i.code = p.payload ->> 'intervention';
    get diagnostics n = row_count;
    if n = 0 then
      update aip.agent_proposal set status = 'failed', decision_note = coalesce(decision_note || ' · ', '') || 'intervention not found or not writable' where id = p_id;
      return null;
    end if;
    ref := p.payload ->> 'intervention';
  else
    return null;
  end if;
  update aip.agent_proposal set status = 'applied', applied_ref = ref where id = p_id;
  return ref;
end $$;
revoke all on function aip.apply_agent_proposal(uuid) from public, anon;
grant execute on function aip.apply_agent_proposal(uuid) to authenticated;

grant select, insert, update on aip.agent_run, aip.agent_proposal to authenticated;
grant select, insert on aip.agent_step to authenticated;
grant all on aip.agent_run, aip.agent_step, aip.agent_proposal to service_role;
