-- Sustantix AIP · find a tenant's newest audit entry from the index alone
-- Generated by tools/schema from src/postgres.ts — do not edit by hand.

create index if not exists audit_log_tenant_latest_idx on aip.audit_log(tenant_id, at desc, id desc);
drop index if exists aip.audit_log_tenant_at_idx;
