-- Sustantix AIP · data-correction log
-- Generated by tools/schema — do not edit by hand. Loaders (seed, provisioning) write one row per derived record
-- or changed row, with the cells changed; members read it; nobody edits it through the API.
create table if not exists aip.data_correction (
  id bigint generated always as identity primary key,
  tenant_id uuid not null references aip.tenants(id) on delete cascade,
  correction_id text not null check (correction_id ~ '^C[0-9]+$'),
  kind text not null default 'derive' check (kind in ('derive','remap')),
  target_table text not null,
  row_key text not null,
  source_table text not null,
  source_key text not null,
  title text not null,
  changes jsonb,
  applied_at timestamptz not null default now(),
  unique (tenant_id, correction_id, target_table, row_key)
);
alter table aip.data_correction add column if not exists kind text not null default 'derive' check (kind in ('derive','remap'));
alter table aip.data_correction add column if not exists changes jsonb;
create index if not exists data_correction_target_idx on aip.data_correction(tenant_id, target_table, row_key);
alter table aip.data_correction enable row level security;
drop policy if exists p_read on aip.data_correction;
create policy p_read on aip.data_correction for select to authenticated using (aip.has_role(tenant_id));
grant select on aip.data_correction to authenticated;
grant all on aip.data_correction to service_role;
