-- Sustantix AIP · phase 5: integrations, staging and data-quality quarantine
-- Generated by tools/schema from src/integration-sql.ts — do not edit by hand.

-- Integrations: a named source system with a hashed key, acting as its own technical tenant member.
create table if not exists aip.integration (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references aip.tenants(id) on delete cascade,
  name text not null check (name ~ '^[A-Za-z0-9][A-Za-z0-9 ._-]{0,79}$'),
  actor uuid not null references auth.users(id) on delete cascade,
  key_hash text not null unique check (key_hash ~ '^[0-9a-f]{64}$'),
  entities text[] not null default '{}',
  enabled boolean not null default true,
  created_by uuid,
  created_at timestamptz not null default now(),
  last_used_at timestamptz,
  unique (tenant_id, name)
);
alter table aip.integration enable row level security;
drop policy if exists p_read on aip.integration;
create policy p_read on aip.integration for select to authenticated using (aip.has_role(tenant_id, array['admin']));
drop policy if exists p_update on aip.integration;
create policy p_update on aip.integration for update to authenticated using (aip.has_role(tenant_id, array['admin'])) with check (aip.has_role(tenant_id, array['admin']));
revoke all on aip.integration from authenticated;
-- Administrators see and enable or disable integrations; creating one (and its technical member) is a server action.
grant select (id, tenant_id, name, actor, entities, enabled, created_by, created_at, last_used_at), update (enabled, entities) on aip.integration to authenticated;
grant all on aip.integration to service_role;

-- Staging: one batch per delivery, one row per record, with the rule results that decided its fate.
create table if not exists aip.staging_batch (
  id uuid primary key,
  tenant_id uuid not null references aip.tenants(id) on delete cascade,
  source text not null check (length(source) between 1 and 80),
  integration_id uuid references aip.integration(id) on delete set null,
  entity text not null,
  actor uuid not null,
  received_at timestamptz not null default now(),
  total integer not null default 0,
  applied integer not null default 0,
  unchanged integer not null default 0,
  quarantined integer not null default 0
);
create index if not exists staging_batch_tenant_idx on aip.staging_batch(tenant_id, received_at desc);
create table if not exists aip.staging_row (
  id bigint generated always as identity primary key,
  tenant_id uuid not null references aip.tenants(id) on delete cascade,
  batch_id uuid not null references aip.staging_batch(id) on delete cascade,
  row_no integer not null,
  entity text not null,
  code text,
  source_record_id text,
  "values" jsonb not null,
  status text not null check (status in ('applied','unchanged','quarantined','discarded')),
  issues jsonb not null default '[]'::jsonb check (jsonb_typeof(issues) = 'array'),
  change_set_id uuid,
  updated_at timestamptz not null default now(),
  unique (batch_id, row_no)
);
create index if not exists staging_row_quarantine_idx on aip.staging_row(tenant_id, status) where status = 'quarantined';
alter table aip.staging_batch enable row level security;
alter table aip.staging_row enable row level security;
drop policy if exists p_read on aip.staging_batch;
create policy p_read on aip.staging_batch for select to authenticated using (aip.has_role(tenant_id, array['planner','admin']));
drop policy if exists p_write on aip.staging_batch;
create policy p_write on aip.staging_batch for insert to authenticated with check (actor = auth.uid() and aip.has_role(tenant_id, array['planner','admin']));
drop policy if exists p_count on aip.staging_batch;
create policy p_count on aip.staging_batch for update to authenticated using (aip.has_role(tenant_id, array['planner','admin'])) with check (aip.has_role(tenant_id, array['planner','admin']));
drop policy if exists p_read on aip.staging_row;
create policy p_read on aip.staging_row for select to authenticated using (aip.has_role(tenant_id, array['planner','admin']));
drop policy if exists p_insert on aip.staging_row;
create policy p_insert on aip.staging_row for insert to authenticated with check (aip.has_role(tenant_id, array['planner','admin']));
drop policy if exists p_update on aip.staging_row;
create policy p_update on aip.staging_row for update to authenticated using (aip.has_role(tenant_id, array['planner','admin'])) with check (aip.has_role(tenant_id, array['planner','admin']));
revoke all on aip.staging_batch, aip.staging_row from authenticated;
grant select, insert on aip.staging_batch to authenticated;
grant update (applied, unchanged, quarantined) on aip.staging_batch to authenticated;
grant select, insert on aip.staging_row to authenticated;
-- Only the outcome of a row changes after it lands; what was delivered never does.
grant update (status, issues, change_set_id, updated_at) on aip.staging_row to authenticated;
grant all on aip.staging_batch, aip.staging_row to service_role;

-- Every quarantined row, for the Data Quality grid (fix at source or in the master, then replay; or discard).
drop view if exists aip.v_staging_quarantine;
create view aip.v_staging_quarantine with (security_invoker = true) as
select r.id::text as code, r.tenant_id, b.source, r.entity, r.code as record, r.source_record_id,
       (select string_agg(i->>'message', '; ') from jsonb_array_elements(r.issues) i) as problem,
       (select string_agg(distinct i->>'rule', ', ') from jsonb_array_elements(r.issues) i) as rules,
       b.received_at, r.updated_at, r.batch_id::text as batch
from aip.staging_row r join aip.staging_batch b on b.id = r.batch_id
where r.status = 'quarantined';
grant select on aip.v_staging_quarantine to authenticated, service_role;

-- Applies a change set as an integration's technical member. Server-only (service role): the server has verified the
-- integration's key; the change set then runs with that member's role rules and is audited under it.
create or replace function aip.apply_change_set_as(p_actor uuid, p_id uuid, p_tenant uuid, p_source text, p_items jsonb)
returns jsonb language plpgsql security definer set search_path = aip, pg_temp as $fn$
declare
  r jsonb;
begin
  if not exists (select 1 from aip.integration i where i.actor = p_actor and i.tenant_id = p_tenant and i.enabled) then
    raise exception 'not an enabled integration of this tenant' using errcode = '42501';
  end if;
  perform set_config('request.jwt.claim.sub', p_actor::text, true);
  r := aip.apply_change_set(p_id, p_tenant, p_source, p_items);
  update aip.integration set last_used_at = now() where actor = p_actor and tenant_id = p_tenant;
  return r;
end $fn$;
revoke all on function aip.apply_change_set_as(uuid, uuid, uuid, text, jsonb) from public, anon, authenticated;
grant execute on function aip.apply_change_set_as(uuid, uuid, uuid, text, jsonb) to service_role;
