-- Sustantix AIP · phase 3 compatibility views (generated by tools/schema from src/sheet-model.ts — do not edit by hand)
-- Each view rebuilds one workbook sheet from the normalized model, so the runtime and integrations keep their shape.
create schema if not exists aip_compat;
grant usage on schema aip_compat to authenticated, service_role;
drop view if exists aip_compat."ai_alerts_and_rul";
create view aip_compat."ai_alerts_and_rul" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t.code)::varchar(200) as "alert_id",
  (j0.code)::varchar(200) as "asset_id",
  (j1.code)::varchar(200) as "plant_id",
  (j0."tag")::varchar(200) as "asset_tag",
  (t."component")::varchar(200) as "component",
  (t."alert_timestamp")::timestamp without time zone as "alert_timestamp",
  (t."model")::varchar(200) as "model",
  (t."risk_score")::numeric(24,3) as "risk_score",
  (t."rul_days")::integer as "rul_days",
  (t."confidence_pct")::numeric(24,2) as "confidence_pct",
  (t."risk_tier")::varchar(200) as "risk_tier",
  (r0.label)::varchar(200) as "alert_status",
  (t."evidence_summary")::varchar(200) as "evidence_summary",
  (t."data_basis")::varchar(200) as "data_basis"
from aip."alert" t
left join aip."asset" j0 on j0.id = t."asset_id"
left join aip."site" j1 on j1.id = t."site_id"
left join aip."ref_status" r0 on r0.id = t."status_id";
comment on view aip_compat."ai_alerts_and_rul" is 'Workbook sheet "AI Alerts & RUL" rebuilt from aip.alert';
grant select on aip_compat."ai_alerts_and_rul" to authenticated, service_role;
drop view if exists aip_compat."prescriptive_actions";
create view aip_compat."prescriptive_actions" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t.code)::varchar(200) as "recommendation_id",
  (j0.code)::varchar(200) as "alert_id",
  (j1.code)::varchar(200) as "asset_id",
  (j1."tag")::varchar(200) as "asset_tag",
  (t."risk_score")::numeric(24,3) as "risk_score",
  (t."rul_days")::integer as "rul_days",
  (t."recommended_action")::varchar(1000) as "recommended_action",
  (t."cost_now")::numeric(24,2) as "cost_now",
  (t."cost_if_deferred")::numeric(24,2) as "cost_if_deferred",
  (t."cost_avoided")::numeric(24,2) as "cost_avoided",
  (t."confidence_pct")::numeric(24,2) as "confidence_pct",
  (r0.label)::varchar(200) as "decision_status",
  (t."rationale")::varchar(1000) as "rationale",
  (j2.code)::varchar(200) as "plant_id",
  t.currency
from aip."recommendation" t
left join aip."alert" j0 on j0.id = t."alert_id"
left join aip."asset" j1 on j1.id = t."asset_id"
left join aip."ref_status" r0 on r0.id = t."status_id"
left join aip."site" j2 on j2.id = t."site_id";
comment on view aip_compat."prescriptive_actions" is 'Workbook sheet "Prescriptive Actions" rebuilt from aip.recommendation';
grant select on aip_compat."prescriptive_actions" to authenticated, service_role;
drop view if exists aip_compat."work_orders";
create view aip_compat."work_orders" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t.code)::varchar(200) as "work_order_id",
  (r0.label)::varchar(200) as "maintenance_type",
  (j0.code)::varchar(200) as "asset_id",
  (j1.code)::varchar(200) as "plant_id",
  (j0."tag")::varchar(200) as "asset_tag",
  (t."description")::varchar(1000) as "description",
  (r1.label)::varchar(200) as "priority",
  (r2.label)::varchar(200) as "status",
  (t."created_date")::timestamp without time zone as "created_date",
  (t."sla_due")::timestamp without time zone as "sla_due",
  (t."sla_hours")::integer as "sla_hours",
  (t."actual_resolution_hours")::numeric(24,2) as "actual_resolution_hours",
  (t."sla_result")::varchar(200) as "sla_result",
  (t."source_record")::varchar(200) as "source",
  (t."estimated_cost")::numeric(24,2) as "estimated_cost",
  (j2.code)::varchar(200) as "assigned_technician_id",
  (t."assigned_crew")::varchar(200) as "assigned_crew",
  (t."pm_frequency_days")::integer as "pm_frequency_days",
  (t."pm_due_date")::date as "pm_due_date",
  (t."actual_pm_completion_date")::date as "actual_pm_completion_date",
  (t."pm_compliance_tolerance_days")::integer as "pm_compliance_tolerance_days",
  (t."pm_compliance_result")::varchar(200) as "pm_compliance_result",
  (t."pm_overdue_days")::integer as "pm_overdue_days",
  (j3.code)::varchar(200) as "linked_alert_id",
  (j4.code)::varchar(200) as "required_part_id",
  (t."required_part_qty")::integer as "required_part_qty",
  (j5.code)::varchar(200) as "module_id",
  (t."data_basis")::varchar(200) as "data_basis",
  t.currency
from aip."work_order" t
left join aip."ref_maintenance_type" r0 on r0.id = t."maintenance_type_id"
left join aip."asset" j0 on j0.id = t."asset_id"
left join aip."site" j1 on j1.id = t."site_id"
left join aip."ref_priority" r1 on r1.id = t."priority_id"
left join aip."ref_status" r2 on r2.id = t."status_id"
left join aip."technician" j2 on j2.id = t."technician_id"
left join aip."alert" j3 on j3.id = t."alert_id"
left join aip."part" j4 on j4.id = t."required_part_id"
left join aip."pv_module" j5 on j5.id = t."pv_module_id";
comment on view aip_compat."work_orders" is 'Workbook sheet "Work Orders" rebuilt from aip.work_order';
grant select on aip_compat."work_orders" to authenticated, service_role;
drop view if exists aip_compat."event_log";
create view aip_compat."event_log" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t.code)::varchar(200) as "event_id",
  (t."incident_id")::varchar(200) as "incident_id",
  (j0.code)::varchar(200) as "plant_id",
  (j1.code)::varchar(200) as "asset_id",
  (t."event_date_time")::timestamp without time zone as "event_date_time",
  (r0.label)::varchar(200) as "event_type",
  (r1.label)::varchar(200) as "severity",
  (t."alarm_code")::varchar(200) as "alarm_code",
  (t."weather_context")::varchar(200) as "weather_context",
  (t."generation_loss_mwh")::numeric(24,2) as "generation_loss_mwh",
  (t."revenue_impact")::numeric(24,2) as "revenue_impact",
  (r2.label)::varchar(200) as "event_status",
  (r3.label)::varchar(200) as "source_system",
  (j1."tag")::varchar(200) as "asset_tag",
  (t."event_timestamp")::timestamp without time zone as "event_timestamp",
  (j2.code)::varchar(200) as "module_id",
  (t."classified_failure")::varchar(200) as "classified_failure",
  t.currency
from aip."event" t
left join aip."site" j0 on j0.id = t."site_id"
left join aip."asset" j1 on j1.id = t."asset_id"
left join aip."ref_event_type" r0 on r0.id = t."event_type_id"
left join aip."ref_severity" r1 on r1.id = t."severity_id"
left join aip."ref_status" r2 on r2.id = t."status_id"
left join aip."ref_source_system" r3 on r3.id = t."source_system_id"
left join aip."pv_module" j2 on j2.id = t."pv_module_id";
comment on view aip_compat."event_log" is 'Workbook sheet "Event Log" rebuilt from aip.event';
grant select on aip_compat."event_log" to authenticated, service_role;
drop view if exists aip_compat."event_root_cause_cases";
create view aip_compat."event_root_cause_cases" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t.code)::varchar(200) as "rca_id",
  (j0.code)::varchar(200) as "event_id",
  (j1.code)::varchar(200) as "plant_id",
  (j1."name")::varchar(200) as "plant_name",
  (j2.code)::varchar(200) as "asset_id",
  (j2."tag")::varchar(200) as "asset_tag",
  (r0.label)::varchar(200) as "asset_class",
  (t."oem_recorded")::varchar(200) as "oem",
  (t."model_recorded")::varchar(200) as "model",
  (r1.label)::varchar(200) as "event_type",
  (r2.label)::varchar(200) as "severity",
  (t."event_time")::timestamp without time zone as "event_time",
  (t."cause_name")::varchar(200) as "cause_name",
  (t."reference_id")::varchar(200) as "reference_id",
  (t."verification_method")::varchar(1000) as "verification_method",
  (t."confidence_pct")::numeric(24,2) as "confidence_pct",
  (r3.label)::varchar(200) as "validation_status",
  (t."engineer_approval")::varchar(200) as "engineer_approval"
from aip."rca_case" t
left join aip."event" j0 on j0.id = t."event_id"
left join aip."site" j1 on j1.id = t."site_id"
left join aip."asset" j2 on j2.id = t."asset_id"
left join aip."ref_asset_class" r0 on r0.id = j2."asset_class_id"
left join aip."ref_event_type" r1 on r1.id = t."event_type_id"
left join aip."ref_severity" r2 on r2.id = t."severity_id"
left join aip."ref_status" r3 on r3.id = t."status_id";
comment on view aip_compat."event_root_cause_cases" is 'Workbook sheet "Event Root Cause Cases" rebuilt from aip.rca_case';
grant select on aip_compat."event_root_cause_cases" to authenticated, service_role;
drop view if exists aip_compat."event_root_cause_evidence";
create view aip_compat."event_root_cause_evidence" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t.code)::varchar(200) as "evidence_id",
  (j0.code)::varchar(200) as "event_id",
  (j1.code)::varchar(200) as "rca_id",
  (j2.code)::varchar(200) as "plant_id",
  (j3.code)::varchar(200) as "asset_id",
  (j3."tag")::varchar(200) as "asset_tag",
  (t."signal")::varchar(200) as "signal",
  (t."actual_value")::numeric(24,2) as "actual_value",
  (t."peer_baseline")::numeric(24,2) as "peer_baseline",
  (r0.label)::varchar(200) as "unit",
  (t."deviation_pct")::numeric(24,2) as "deviation_pct",
  (r1.label)::varchar(200) as "source_system",
  (t."evidence_role")::varchar(200) as "evidence_role",
  (t."engineering_interpretation")::varchar(1000) as "engineering_interpretation"
from aip."rca_evidence" t
left join aip."event" j0 on j0.id = t."event_id"
left join aip."rca_case" j1 on j1.id = t."rca_case_id"
left join aip."site" j2 on j2.id = t."site_id"
left join aip."asset" j3 on j3.id = t."asset_id"
left join aip."ref_unit" r0 on r0.id = t."unit_id"
left join aip."ref_source_system" r1 on r1.id = t."source_system_id";
comment on view aip_compat."event_root_cause_evidence" is 'Workbook sheet "Event Root Cause Evidence" rebuilt from aip.rca_evidence';
grant select on aip_compat."event_root_cause_evidence" to authenticated, service_role;
drop view if exists aip_compat."vision_inspections";
create view aip_compat."vision_inspections" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t.code)::varchar(200) as "inspection_id",
  (j0.code)::varchar(200) as "plant_id",
  (j0."name")::varchar(200) as "plant_name",
  (t."inspection_date_time")::timestamp without time zone as "inspection_date_time",
  (t."inspection_type")::varchar(200) as "inspection_type",
  (t."device_id")::varchar(200) as "device_id",
  (t."panels_inspected")::integer as "panels_inspected",
  (t."images_captured")::integer as "images_captured",
  (t."coverage_pct")::numeric(24,3) as "coverage_pct",
  (t."weather")::varchar(200) as "weather",
  (t."flight_altitude_m")::integer as "flight_altitude_m",
  (t."inspection_status")::varchar(200) as "inspection_status",
  (t."inspector")::varchar(200) as "inspector",
  (j1.code)::varchar(200) as "asset_id",
  (t."data_basis")::varchar(200) as "data_basis"
from aip."vision_inspection" t
left join aip."site" j0 on j0.id = t."site_id"
left join aip."asset" j1 on j1.id = t."asset_id";
comment on view aip_compat."vision_inspections" is 'Workbook sheet "Vision Inspections" rebuilt from aip.vision_inspection';
grant select on aip_compat."vision_inspections" to authenticated, service_role;
drop view if exists aip_compat."vision_findings";
create view aip_compat."vision_findings" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t.code)::varchar(200) as "finding_id",
  (j0.code)::varchar(200) as "inspection_id",
  (j1.code)::varchar(200) as "plant_id",
  (j2.code)::varchar(200) as "asset_id",
  (j2."tag")::varchar(200) as "asset_tag",
  (r0.label)::varchar(200) as "defect_type",
  (t."detection_mode")::varchar(200) as "detection_mode",
  (t."confidence_pct")::numeric(24,2) as "confidence_pct",
  (r1.label)::varchar(200) as "severity",
  (r2.label)::varchar(200) as "finding_status",
  (t."estimated_loss_k_wh_day")::numeric(24,2) as "estimated_loss_k_wh_day",
  (t."annual_revenue_risk")::numeric(24,2) as "annual_revenue_risk",
  (t."recommended_action")::varchar(1000) as "recommended_action",
  (j3.code)::varchar(200) as "work_order_id",
  (t."affected_area_sqm")::numeric(24,3) as "affected_area_sqm",
  (t."physical_location")::varchar(200) as "physical_location",
  (t."inspection_date")::date as "inspection_date",
  (t."inspector")::varchar(200) as "inspector",
  (j4.code)::varchar(200) as "module_id",
  (t."classified_failure")::varchar(200) as "classified_failure",
  (t."data_basis")::varchar(200) as "data_basis",
  t.currency
from aip."vision_finding" t
left join aip."vision_inspection" j0 on j0.id = t."inspection_id"
left join aip."site" j1 on j1.id = t."site_id"
left join aip."asset" j2 on j2.id = t."asset_id"
left join aip."ref_defect_code" r0 on r0.id = t."defect_type_id"
left join aip."ref_severity" r1 on r1.id = t."severity_id"
left join aip."ref_status" r2 on r2.id = t."status_id"
left join aip."work_order" j3 on j3.id = t."work_order_id"
left join aip."pv_module" j4 on j4.id = t."pv_module_id";
comment on view aip_compat."vision_findings" is 'Workbook sheet "Vision Findings" rebuilt from aip.vision_finding';
grant select on aip_compat."vision_findings" to authenticated, service_role;
drop view if exists aip_compat."warranty_claims";
create view aip_compat."warranty_claims" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t.code)::varchar(200) as "claim_id",
  (j0.code)::varchar(200) as "warranty_id",
  (t."incident_id")::varchar(200) as "incident_id",
  (j1.code)::varchar(200) as "asset_id",
  (j1."tag")::varchar(200) as "asset_tag",
  (j2.code)::varchar(200) as "plant_id",
  (t."claim_date")::date as "claim_date",
  (t."failure_event_id")::varchar(200) as "failure_event_id",
  (r0.label)::varchar(200) as "claim_status",
  (t."claimed_amount")::numeric(24,2) as "claimed_amount",
  (t."approved_amount")::numeric(24,2) as "approved_amount",
  (t."days_open")::integer as "days_open",
  (t."evidence_completeness_pct")::integer as "evidence_completeness_pct",
  (t."notice_deadline")::date as "notice_deadline",
  (t."oem_response_date")::date as "oem_response_date",
  (t."rejection_reason")::varchar(200) as "rejection_reason",
  (t."next_action")::varchar(200) as "next_action",
  (j3.code)::varchar(200) as "work_order_id",
  (j4.code)::varchar(200) as "module_id",
  (t."data_basis")::varchar(200) as "data_basis",
  t.currency
from aip."warranty_claim" t
left join aip."warranty_contract" j0 on j0.id = t."warranty_id"
left join aip."asset" j1 on j1.id = t."asset_id"
left join aip."site" j2 on j2.id = t."site_id"
left join aip."ref_status" r0 on r0.id = t."status_id"
left join aip."work_order" j3 on j3.id = t."work_order_id"
left join aip."pv_module" j4 on j4.id = t."pv_module_id";
comment on view aip_compat."warranty_claims" is 'Workbook sheet "Warranty Claims" rebuilt from aip.warranty_claim';
grant select on aip_compat."warranty_claims" to authenticated, service_role;
drop view if exists aip_compat."pm_plans";
create view aip_compat."pm_plans" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t.code)::varchar(200) as "pm_plan_id",
  (j0.code)::varchar(200) as "asset_id",
  (j0."tag")::varchar(200) as "asset_tag",
  (t."task")::varchar(1000) as "task",
  (t."frequency_days")::integer as "frequency_days",
  (t."last_done")::date as "last_done",
  (t."next_due")::date as "next_due",
  (t."overdue_days")::integer as "overdue_days",
  (t."standard_labour_hours")::integer as "standard_labour_hours",
  (j1.code)::varchar(200) as "primary_part_id",
  (r0.label)::varchar(200) as "required_skill",
  (j2.code)::varchar(200) as "plant_id",
  (t."data_basis")::varchar(200) as "data_basis"
from aip."pm_plan" t
left join aip."asset" j0 on j0.id = t."asset_id"
left join aip."part" j1 on j1.id = t."primary_part_id"
left join aip."ref_skill" r0 on r0.id = t."required_skill_id"
left join aip."site" j2 on j2.id = t."site_id";
comment on view aip_compat."pm_plans" is 'Workbook sheet "PM Plans" rebuilt from aip.pm_plan';
grant select on aip_compat."pm_plans" to authenticated, service_role;
drop view if exists aip_compat."cbm_assessments";
create view aip_compat."cbm_assessments" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t.code)::varchar(200) as "cbm_assessment_id",
  (j0.code)::varchar(200) as "plant_id",
  (j0."name")::varchar(200) as "plant_name",
  (j1.code)::varchar(200) as "asset_id",
  (j1."tag")::varchar(200) as "asset_tag",
  (r0.label)::varchar(200) as "asset_class",
  (coalesce(r1.label, r2.label))::varchar(200) as "failure_mode",
  (t."primary_condition")::varchar(200) as "primary_condition",
  (t."source_mode")::varchar(200) as "source_mode",
  (t."latest_evidence_time")::timestamp without time zone as "latest_evidence_time",
  (t."freshness_class")::varchar(200) as "freshness_class",
  (t."max_deviation_pct")::numeric(24,2) as "max_deviation_pct",
  (t."evidence_count")::integer as "evidence_count",
  (t."corroboration_count")::integer as "corroboration_count",
  (t."condition_severity")::varchar(200) as "condition_severity",
  (t."risk_context")::varchar(200) as "risk_context",
  (t."evidence_sufficiency_pct")::numeric(24,2) as "evidence_sufficiency_pct",
  (t."engineering_physics_fit_pct")::numeric(24,2) as "engineering_physics_fit_pct",
  (t."confidence_pct")::numeric(24,2) as "confidence_pct",
  (r3.label)::varchar(200) as "priority",
  (t."condition_state")::varchar(200) as "condition_state",
  (t."recommended_action")::varchar(1000) as "recommended_action",
  (t."governance_class")::varchar(200) as "governance_class",
  (t."approval_role")::varchar(200) as "approval_role",
  (t."source_module")::varchar(200) as "source_module",
  (t."source_record_id")::varchar(200) as "source_record_id",
  (t."target_view")::varchar(200) as "target_view",
  (t."work_order_code")::varchar(200) as "work_order_id",
  (t."reference_id")::varchar(200) as "reference_id",
  (t."verification_method")::varchar(1000) as "verification_method",
  (t."decision_basis")::varchar(1000) as "decision_basis"
from aip."cbm_assessment" t
left join aip."site" j0 on j0.id = t."site_id"
left join aip."asset" j1 on j1.id = t."asset_id"
left join aip."ref_asset_class" r0 on r0.id = j1."asset_class_id"
left join aip."ref_failure_mode" r1 on r1.id = t."failure_mode_id"
left join aip."ref_defect_code" r2 on r2.id = t."observed_defect_id"
left join aip."ref_priority" r3 on r3.id = t."priority_id";
comment on view aip_compat."cbm_assessments" is 'Workbook sheet "CBM Assessments" rebuilt from aip.cbm_assessment';
grant select on aip_compat."cbm_assessments" to authenticated, service_role;
drop view if exists aip_compat."cbm_evidence";
create view aip_compat."cbm_evidence" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t.code)::varchar(200) as "cbm_evidence_id",
  (j0.code)::varchar(200) as "cbm_assessment_id",
  (j1.code)::varchar(200) as "plant_id",
  (j2.code)::varchar(200) as "asset_id",
  (t."evidence_source")::varchar(200) as "evidence_source",
  (t."arrival_mode")::varchar(200) as "arrival_mode",
  (t."source_module")::varchar(200) as "source_module",
  (t."target_view")::varchar(200) as "target_view",
  (t."source_record_id")::varchar(200) as "source_record_id",
  (t."observed_time")::timestamp without time zone as "observed_time",
  (t."signal_name")::varchar(200) as "signal_name",
  (t."observed_value")::numeric(24,2) as "observed_value",
  (t."baseline_or_peer")::numeric(24,2) as "baseline_or_peer",
  (r0.label)::varchar(200) as "unit",
  (t."deviation_pct")::numeric(24,2) as "deviation_pct",
  (t."evidence_role")::varchar(200) as "evidence_role",
  (t."quality_pct")::numeric(24,2) as "quality_pct",
  (t."engineering_interpretation")::varchar(1000) as "engineering_interpretation",
  (t."freshness_label")::varchar(200) as "freshness_label"
from aip."condition_evidence" t
left join aip."cbm_assessment" j0 on j0.id = t."assessment_id"
left join aip."site" j1 on j1.id = t."site_id"
left join aip."asset" j2 on j2.id = t."asset_id"
left join aip."ref_unit" r0 on r0.id = t."unit_id";
comment on view aip_compat."cbm_evidence" is 'Workbook sheet "CBM Evidence" rebuilt from aip.condition_evidence';
grant select on aip_compat."cbm_evidence" to authenticated, service_role;
drop view if exists aip_compat."msi_spare_requirements";
create view aip_compat."msi_spare_requirements" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t.code)::varchar(200) as "requirement_id",
  (j0.code)::varchar(200) as "intervention_id",
  (j1.code)::varchar(200) as "work_order_id",
  (t."decision_id")::varchar(200) as "decision_id",
  (j2.code)::varchar(200) as "plant_id",
  (j3.code)::varchar(200) as "asset_id",
  (j3."tag")::varchar(200) as "asset_tag",
  (r0.label)::varchar(200) as "maintenance_type",
  (j4.code)::varchar(200) as "part_id",
  (t."required_qty")::integer as "required_qty",
  (to_char(t."required_by", 'YYYY-MM-DD HH24:MI'))::varchar(200) as "required_by",
  (t."status")::varchar(200) as "requirement_status",
  (t."requirement_source")::varchar(200) as "requirement_source",
  (t."source_record_id")::varchar(200) as "source_record_id",
  (to_char(t."as_of", 'DD-MM-YYYY HH24:MI'))::varchar(200) as "as_of"
from aip."part_requirement" t
left join aip."intervention" j0 on j0.id = t."intervention_id"
left join aip."work_order" j1 on j1.id = t."work_order_id"
left join aip."site" j2 on j2.id = t."site_id"
left join aip."asset" j3 on j3.id = t."asset_id"
left join aip."ref_maintenance_type" r0 on r0.id = t."maintenance_type_id"
left join aip."part" j4 on j4.id = t."part_id";
comment on view aip_compat."msi_spare_requirements" is 'Workbook sheet "MSI_Spare_Requirements" rebuilt from aip.part_requirement';
grant select on aip_compat."msi_spare_requirements" to authenticated, service_role;
drop view if exists aip_compat."plan_requirements";
create view aip_compat."plan_requirements" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t.code)::varchar(200) as "requirement_id",
  (j0.code)::varchar(200) as "intervention_id",
  (t."requirement_type")::varchar(200) as "requirement_type",
  (t."requirement_ref")::varchar(200) as "requirement_ref",
  (t."quantity")::integer as "quantity",
  (case when t."mandatory" then 'Yes' when not t."mandatory" then 'No' end)::varchar(200) as "mandatory",
  (t."source_record")::varchar(200) as "source"
from aip."intervention_requirement" t
left join aip."intervention" j0 on j0.id = t."intervention_id";
comment on view aip_compat."plan_requirements" is 'Workbook sheet "PLAN_Requirements" rebuilt from aip.intervention_requirement';
grant select on aip_compat."plan_requirements" to authenticated, service_role;
drop view if exists aip_compat."planned_outages";
create view aip_compat."planned_outages" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t.code)::varchar(200) as "outage_id",
  (j0.code)::varchar(200) as "plant_id",
  (t."asset_scope")::varchar(200) as "asset_scope",
  (t."capacity_out_mw")::numeric(24,2) as "capacity_out_mw",
  (t."start_at")::timestamp without time zone as "start",
  (t."end_at")::timestamp without time zone as "end",
  (t."reason")::varchar(200) as "reason",
  (r0.label)::varchar(200) as "status",
  (t."data_provenance")::varchar(200) as "data_provenance"
from aip."planned_outage" t
left join aip."site" j0 on j0.id = t."site_id"
left join aip."ref_status" r0 on r0.id = t."status_id";
comment on view aip_compat."planned_outages" is 'Workbook sheet "Planned Outages" rebuilt from aip.planned_outage';
grant select on aip_compat."planned_outages" to authenticated, service_role;
drop view if exists aip_compat."bess_capacity_tests";
create view aip_compat."bess_capacity_tests" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t.code)::varchar(200) as "test_id",
  (j0.code)::varchar(200) as "bess_id",
  (t."test_date")::date as "test_date",
  (t."test_type")::varchar(200) as "test_type",
  (t."test_standard")::varchar(200) as "test_standard",
  (t."rated_power_during_test_mw")::integer as "rated_power_during_test_mw",
  (t."discharged_energy_poi_mwh")::numeric(24,2) as "discharged_energy_poi_mwh",
  (t."charged_energy_poi_mwh")::numeric(24,2) as "charged_energy_poi_mwh",
  (t."ac_rte_pct")::numeric(24,2) as "ac_rte_pct",
  (t."soh_energy_pct")::numeric(24,2) as "soh_energy_pct",
  (t."ambient_temp_c")::numeric(24,2) as "ambient_temp_c",
  (t."witness")::varchar(200) as "witness",
  (t."result")::varchar(200) as "result",
  (t."data_provenance")::varchar(200) as "data_provenance"
from aip."capacity_test" t
left join aip."asset_bess" j0 on j0.id = t."bess_id";
comment on view aip_compat."bess_capacity_tests" is 'Workbook sheet "BESS Capacity Tests" rebuilt from aip.capacity_test';
grant select on aip_compat."bess_capacity_tests" to authenticated, service_role;
drop view if exists aip_compat."sus_hse_hours";
create view aip_compat."sus_hse_hours" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t."period")::varchar(200) as "period",
  (j0.code)::varchar(200) as "plant_id",
  (t."worker_type")::varchar(200) as "worker_type",
  (t."hours_worked")::integer as "hours_worked",
  (r0.label)::varchar(200) as "source_system",
  (t."data_status")::varchar(200) as "data_status"
from aip."hse_hours" t
left join aip."site" j0 on j0.id = t."site_id"
left join aip."ref_source_system" r0 on r0.id = t."source_system_id";
comment on view aip_compat."sus_hse_hours" is 'Workbook sheet "SUS_HSE_Hours" rebuilt from aip.hse_hours';
grant select on aip_compat."sus_hse_hours" to authenticated, service_role;
drop view if exists aip_compat."sus_ghg_activity";
create view aip_compat."sus_ghg_activity" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t.code)::varchar(200) as "activity_id",
  (t."period")::varchar(200) as "period",
  (j0.code)::varchar(200) as "plant_id",
  (j1.code)::varchar(200) as "asset_id",
  (r0.label)::varchar(200) as "asset_class",
  (t."ghg_scope")::varchar(200) as "ghg_scope",
  (t."emission_source")::varchar(200) as "emission_source",
  (t."activity_value")::numeric(24,2) as "activity_value",
  (t."activity_unit")::varchar(200) as "activity_unit",
  (r1.label)::varchar(200) as "source_system",
  (t."data_status")::varchar(200) as "data_status",
  (t."asset_reference_basis")::varchar(200) as "asset_reference_basis",
  (t."factor_id")::varchar(200) as "factor_id",
  (t."factor_value")::numeric(24,2) as "factor_value",
  (t."factor_unit")::varchar(200) as "factor_unit",
  (t."factor_resolution")::varchar(200) as "factor_resolution"
from aip."ghg_activity" t
left join aip."site" j0 on j0.id = t."site_id"
left join aip."asset" j1 on j1.id = t."asset_id"
left join aip."ref_asset_class" r0 on r0.id = j1."asset_class_id"
left join aip."ref_source_system" r1 on r1.id = t."source_system_id";
comment on view aip_compat."sus_ghg_activity" is 'Workbook sheet "SUS_GHG_Activity" rebuilt from aip.ghg_activity';
grant select on aip_compat."sus_ghg_activity" to authenticated, service_role;
drop view if exists aip_compat."sus_water_cleaning";
create view aip_compat."sus_water_cleaning" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t.code)::varchar(200) as "cleaning_event_id",
  (t."event_date")::date as "date",
  (j0.code)::varchar(200) as "plant_id",
  (j0."name")::varchar(200) as "plant_name",
  (t."array_designation")::varchar(200) as "pv_array_id",
  (t."array_name")::varchar(200) as "pv_array_name",
  (j1.code)::varchar(200) as "asset_id",
  (r0.label)::varchar(200) as "asset_class",
  (t."cleaning_type")::varchar(200) as "cleaning_type",
  (t."water_m3")::numeric(24,2) as "water_m3",
  (t."soiling_before_pct")::numeric(24,2) as "soiling_before_pct",
  (t."soiling_after_pct")::numeric(24,2) as "soiling_after_pct",
  (t."mwh_recovered")::numeric(24,2) as "mwh_recovered",
  (t."water_per_recovered_mwh_l")::numeric(24,2) as "water_per_recovered_mwh_l",
  (r1.label)::varchar(200) as "source_system",
  (t."data_status")::varchar(200) as "data_status",
  (t."asset_reference_basis")::varchar(200) as "asset_reference_basis"
from aip."water_cleaning" t
left join aip."site" j0 on j0.id = t."site_id"
left join aip."asset" j1 on j1.id = t."asset_id"
left join aip."ref_asset_class" r0 on r0.id = j1."asset_class_id"
left join aip."ref_source_system" r1 on r1.id = t."source_system_id";
comment on view aip_compat."sus_water_cleaning" is 'Workbook sheet "SUS_Water_Cleaning" rebuilt from aip.water_cleaning';
grant select on aip_compat."sus_water_cleaning" to authenticated, service_role;
drop view if exists aip_compat."plan_execution_feedback";
create view aip_compat."plan_execution_feedback" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t.code)::varchar(200) as "execution_feedback_id",
  (j0.code)::varchar(200) as "work_order_id",
  (j1.code)::varchar(200) as "plant_id",
  (j2.code)::varchar(200) as "asset_id",
  (t."planned_start")::timestamp without time zone as "planned_start",
  (t."actual_start")::timestamp without time zone as "actual_start",
  (t."planned_duration_hours")::numeric(24,2) as "planned_duration_hours",
  (t."actual_duration_hours")::numeric(24,2) as "actual_duration_hours",
  (t."date_variance_hours")::integer as "date_variance_hours",
  (t."duration_variance_pct")::numeric(24,2) as "duration_variance_pct",
  (t."conformance_status")::varchar(200) as "conformance_status",
  (t."outcome_status")::varchar(200) as "outcome_status",
  (t."source_record")::varchar(200) as "source"
from aip."execution_feedback" t
left join aip."work_order" j0 on j0.id = t."work_order_id"
left join aip."site" j1 on j1.id = t."site_id"
left join aip."asset" j2 on j2.id = t."asset_id";
comment on view aip_compat."plan_execution_feedback" is 'Workbook sheet "PLAN_Execution_Feedback" rebuilt from aip.execution_feedback';
grant select on aip_compat."plan_execution_feedback" to authenticated, service_role;
drop view if exists aip_compat."fcst_run";
create view aip_compat."fcst_run" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t.code)::varchar(200) as "forecast_run_id",
  (j0.code)::varchar(200) as "plant_id",
  (t."forecast_run_timestamp")::timestamp without time zone as "forecast_run_timestamp",
  (t."horizon_hours")::integer as "horizon_hours",
  (t."forecast_start")::timestamp without time zone as "forecast_start",
  (t."forecast_end")::timestamp without time zone as "forecast_end",
  (t."resolution_minutes")::integer as "resolution_minutes",
  (t."physics_forecast_mwh")::numeric(24,3) as "physics_forecast_mwh",
  (t."hybrid_forecast_mwh")::numeric(24,3) as "hybrid_forecast_mwh",
  (t."operational_energy_at_risk_mwh")::numeric(24,3) as "operational_energy_at_risk_mwh",
  (t."calibrated_band_pct")::numeric(24,3) as "calibrated_band_pct",
  (t."data_trust_pct")::numeric(24,2) as "data_trust_pct",
  (t."model_reliability_n_mae_pct")::numeric(24,3) as "model_reliability_n_mae_pct",
  (j1.code)::varchar(200) as "physics_model_id",
  (j2.code)::varchar(200) as "residual_model_id",
  (j3.code)::varchar(200) as "uncertainty_model_id",
  (t."run_status")::varchar(200) as "run_status",
  (t."source_mode")::varchar(200) as "source_mode"
from aip."forecast_run" t
left join aip."site" j0 on j0.id = t."site_id"
left join aip."ml_model" j1 on j1.id = t."physics_model_id"
left join aip."ml_model" j2 on j2.id = t."residual_model_id"
left join aip."ml_model" j3 on j3.id = t."uncertainty_model_id";
comment on view aip_compat."fcst_run" is 'Workbook sheet "FCST_Run" rebuilt from aip.forecast_run';
grant select on aip_compat."fcst_run" to authenticated, service_role;
drop view if exists aip_compat."plan_outcome_validation";
create view aip_compat."plan_outcome_validation" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t.code)::varchar(200) as "outcome_validation_id",
  (j0.code)::varchar(200) as "execution_feedback_id",
  (j1.code)::varchar(200) as "work_order_id",
  (j2.code)::varchar(200) as "plant_id",
  (j3.code)::varchar(200) as "asset_id",
  (t."forecast_run_id")::varchar(200) as "forecast_run_id",
  (t."predicted_avoided_loss_mwh")::numeric(24,2) as "predicted_avoided_loss_mwh",
  (t."predicted_value_protected")::numeric(24,2) as "predicted_value_protected",
  (t."actual_validated_recovery_mwh")::numeric(24,2) as "actual_validated_recovery_mwh",
  (t."actual_value_realized")::numeric(24,2) as "actual_value_realized",
  (t."execution_cost")::numeric(24,2) as "execution_cost",
  (t."net_realized_value")::numeric(24,2) as "net_realized_value",
  (t."realization_pct")::numeric(24,2) as "realization_pct",
  (t."outcome_confidence_pct")::numeric(24,2) as "outcome_confidence_pct",
  (t."variance_driver")::varchar(200) as "variance_driver",
  (t."validation_status")::varchar(200) as "validation_status",
  (t."learning_feedback_status")::varchar(200) as "learning_feedback_status",
  (t."source_mode")::varchar(200) as "source_mode",
  t.currency
from aip."outcome_validation" t
left join aip."execution_feedback" j0 on j0.id = t."execution_feedback_id"
left join aip."work_order" j1 on j1.id = t."work_order_id"
left join aip."site" j2 on j2.id = t."site_id"
left join aip."asset" j3 on j3.id = t."asset_id";
comment on view aip_compat."plan_outcome_validation" is 'Workbook sheet "PLAN_Outcome_Validation" rebuilt from aip.outcome_validation';
grant select on aip_compat."plan_outcome_validation" to authenticated, service_role;
drop view if exists aip_compat."commercial_and_ppa";
create view aip_compat."commercial_and_ppa" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (j0.code)::varchar(200) as "ppa_id",
  (j1.code)::varchar(200) as "plant_id",
  (j2."name")::varchar(200) as "offtaker",
  (j0."tariff_per_kwh")::numeric(24,2) as "ppa_tariff_k_wh",
  (j0."contracted_capacity_mw")::integer as "contracted_capacity_mw",
  (j0."start_date")::date as "contract_start_date",
  (j0."end_date")::date as "contract_expiry_date",
  (j0."availability_obligation_pct")::integer as "availability_obligation_pct",
  (t."scheduled_energy_mwh")::numeric(24,2) as "scheduled_energy_mwh",
  (t."delivered_energy_mwh")::numeric(24,2) as "delivered_energy_mwh",
  (t."deemed_generation_mwh")::numeric(24,2) as "deemed_generation_mwh",
  (t."shortfall_energy_mwh")::numeric(24,2) as "shortfall_energy_mwh",
  (t."availability_penalty")::numeric(24,2) as "availability_penalty",
  (t."curtailment_compensation")::numeric(24,2) as "curtailment_compensation",
  (t."invoice_amount")::numeric(24,2) as "invoice_amount",
  (t."amount_received")::numeric(24,2) as "amount_received",
  (t."receivable_balance")::numeric(24,2) as "receivable_balance",
  (t."days_outstanding")::integer as "days_outstanding",
  (j0."status")::varchar(200) as "contract_status",
  t.currency
from aip."ppa_settlement" t
left join aip."offtake_contract" j0 on j0.id = t."contract_id"
left join aip."site" j1 on j1.id = t."site_id"
left join aip."party" j2 on j2.id = j0."offtaker_id";
comment on view aip_compat."commercial_and_ppa" is 'Workbook sheet "Commercial & PPA" rebuilt from aip.ppa_settlement';
grant select on aip_compat."commercial_and_ppa" to authenticated, service_role;
drop view if exists aip_compat."twin_telemetry";
create view aip_compat."twin_telemetry" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t."at")::timestamp without time zone as "timestamp",
  (j0.code)::varchar(200) as "plant_id",
  (t."poa_wm2")::numeric(24,2) as "poa_wm2",
  (t."ghi_wm2")::numeric(24,2) as "ghi_wm2",
  (t."ambient_temp_c")::numeric(24,2) as "ambient_temp_c",
  (t."module_temp_c")::numeric(24,2) as "module_temp_c",
  (t."wind_speed_ms")::numeric(24,2) as "wind_speed_ms",
  (t."soiling_ratio")::numeric(24,3) as "soiling_ratio",
  (t."expected_dc_mw")::numeric(24,2) as "expected_dc_mw",
  (t."expected_ac_mw")::numeric(24,2) as "expected_ac_mw",
  (t."actual_ac_mw")::numeric(24,2) as "actual_ac_mw",
  (t."pr_pct")::numeric(24,2) as "pr_pct",
  (t."availability_pct")::numeric(24,2) as "availability_pct",
  (t."inverter_efficiency_pct")::numeric(24,2) as "inverter_efficiency_pct",
  (t."grid_frequency_hz")::numeric(24,3) as "grid_frequency_hz",
  (t."power_factor")::numeric(24,3) as "power_factor",
  (t."data_quality_pct")::numeric(24,2) as "data_quality_pct",
  (t."source_record")::varchar(200) as "source",
  (t."clear_sky_poa_wm2")::numeric(24,2) as "clear_sky_poa_wm2",
  (t."cloud_cover_pct")::numeric(24,2) as "cloud_cover_pct",
  (t."cloud_transmittance_pct")::numeric(24,2) as "cloud_transmittance_pct",
  (t."clear_sky_ac_potential_mw")::numeric(24,2) as "clear_sky_ac_potential_mw",
  (t."weather_adjusted_expected_ac_mw")::numeric(24,2) as "weather_adjusted_expected_ac_mw",
  (t."weather_loss_mw")::numeric(24,2) as "weather_loss_mw",
  (t."plant_operational_loss_mw")::numeric(24,2) as "plant_operational_loss_mw",
  (t."curtailment_pct")::numeric(24,2) as "curtailment_pct",
  (t."asset_health_score")::integer as "asset_health_score",
  (t."weather_source")::varchar(200) as "weather_source",
  (t."weather_mode")::varchar(200) as "weather_mode",
  (t."data_provenance")::varchar(200) as "data_provenance"
from aip."plant_telemetry" t
left join aip."site" j0 on j0.id = t."site_id";
comment on view aip_compat."twin_telemetry" is 'Workbook sheet "Twin Telemetry" rebuilt from aip.plant_telemetry';
grant select on aip_compat."twin_telemetry" to authenticated, service_role;
drop view if exists aip_compat."inverter_telemetry";
create view aip_compat."inverter_telemetry" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t."at")::timestamp without time zone as "timestamp",
  (j0.code)::varchar(200) as "plant_id",
  (j1.code)::varchar(200) as "asset_id",
  (j1."tag")::varchar(200) as "inverter_tag",
  (t."dc_power_mw")::numeric(24,4) as "dc_power_mw",
  (t."ac_power_mw")::numeric(24,4) as "ac_power_mw",
  (t."dc_voltage_v")::numeric(24,2) as "dc_voltage_v",
  (t."dc_current_a")::numeric(24,2) as "dc_current_a",
  (t."inverter_temp_c")::numeric(24,2) as "inverter_temp_c",
  (r0.label)::varchar(200) as "status",
  (t."alarm_code")::varchar(200) as "alarm_code",
  (t."data_provenance")::varchar(200) as "data_provenance"
from aip."inverter_reading" t
left join aip."site" j0 on j0.id = t."site_id"
left join aip."asset" j1 on j1.id = t."asset_id"
left join aip."ref_status" r0 on r0.id = t."status_id";
comment on view aip_compat."inverter_telemetry" is 'Workbook sheet "Inverter Telemetry" rebuilt from aip.inverter_reading';
grant select on aip_compat."inverter_telemetry" to authenticated, service_role;
drop view if exists aip_compat."bess_telemetry";
create view aip_compat."bess_telemetry" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t."at")::timestamp without time zone as "timestamp",
  (j0.code)::varchar(200) as "bess_id",
  (j1.code)::varchar(200) as "plant_id",
  (t."charge_mw_poi")::numeric(24,3) as "charge_mw_poi",
  (t."discharge_mw_poi")::numeric(24,3) as "discharge_mw_poi",
  (t."charge_source")::varchar(200) as "charge_source",
  (t."dispatch_schedule_mw")::integer as "dispatch_schedule_mw",
  (t."available_mw")::numeric(24,2) as "available_mw",
  (t."so_c_pct")::numeric(24,2) as "so_c_pct",
  (t."aux_load_mw")::numeric(24,4) as "aux_load_mw",
  (t."cell_temp_max_c")::numeric(24,2) as "cell_temp_max_c",
  (t."cell_temp_avg_c")::numeric(24,2) as "cell_temp_avg_c",
  (t."ambient_temp_c")::numeric(24,2) as "ambient_temp_c",
  (t."co_located_pv_mw")::numeric(24,2) as "co_located_pv_mw",
  (t."operating_mode")::varchar(200) as "operating_mode",
  (t."data_quality_pct")::numeric(24,2) as "data_quality_pct",
  (t."data_provenance")::varchar(200) as "data_provenance"
from aip."bess_reading" t
left join aip."asset_bess" j0 on j0.id = t."bess_id"
left join aip."site" j1 on j1.id = t."site_id";
comment on view aip_compat."bess_telemetry" is 'Workbook sheet "BESS Telemetry" rebuilt from aip.bess_reading';
grant select on aip_compat."bess_telemetry" to authenticated, service_role;
drop view if exists aip_compat."bess_daily_operations";
create view aip_compat."bess_daily_operations" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t."day")::date as "date",
  (j0.code)::varchar(200) as "bess_id",
  (j1.code)::varchar(200) as "plant_id",
  (t."charge_mwh_poi")::numeric(24,2) as "charge_mwh_poi",
  (t."discharge_mwh_poi")::numeric(24,2) as "discharge_mwh_poi",
  (t."aux_mwh")::numeric(24,3) as "aux_mwh",
  (t."start_so_c_pct")::numeric(24,2) as "start_so_c_pct",
  (t."end_so_c_pct")::numeric(24,2) as "end_so_c_pct",
  (t."equivalent_full_cycles")::numeric(24,3) as "equivalent_full_cycles",
  (t."availability_pct")::numeric(24,2) as "availability_pct",
  (t."scheduled_discharge_mwh")::integer as "scheduled_discharge_mwh",
  (t."max_cell_temp_c")::numeric(24,2) as "max_cell_temp_c",
  (t."cumulative_discharge_mwh_since_cod")::numeric(24,2) as "cumulative_discharge_mwh_since_cod",
  (t."data_provenance")::varchar(200) as "data_provenance"
from aip."bess_day" t
left join aip."asset_bess" j0 on j0.id = t."bess_id"
left join aip."site" j1 on j1.id = t."site_id";
comment on view aip_compat."bess_daily_operations" is 'Workbook sheet "BESS Daily Operations" rebuilt from aip.bess_day';
grant select on aip_compat."bess_daily_operations" to authenticated, service_role;
drop view if exists aip_compat."forecast_weather";
create view aip_compat."forecast_weather" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (j0.code)::varchar(200) as "plant_id",
  (t."forecast_run_timestamp")::timestamp without time zone as "forecast_run_timestamp",
  (t."interval_start")::timestamp without time zone as "interval_start",
  (t."lead_hours")::numeric(24,2) as "lead_hours",
  (t."clear_sky_index")::numeric(24,4) as "clear_sky_index",
  (t."cloud_cover_pct")::numeric(24,2) as "cloud_cover_pct",
  (t."ambient_temp_c")::numeric(24,2) as "ambient_temp_c",
  (t."wind_speed_ms")::numeric(24,2) as "wind_speed_ms",
  (t."forecast_curtailment_pct")::numeric(24,2) as "forecast_curtailment_pct",
  (t."nwp_source")::varchar(200) as "nwp_source",
  (t."data_provenance")::varchar(200) as "data_provenance"
from aip."weather_forecast" t
left join aip."site" j0 on j0.id = t."site_id";
comment on view aip_compat."forecast_weather" is 'Workbook sheet "Forecast Weather" rebuilt from aip.weather_forecast';
grant select on aip_compat."forecast_weather" to authenticated, service_role;
drop view if exists aip_compat."fcst_interval";
create view aip_compat."fcst_interval" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t."forecast_run_timestamp")::timestamp without time zone as "forecast_run_timestamp",
  (j0.code)::varchar(200) as "plant_id",
  (t."interval_start")::timestamp without time zone as "interval_start",
  (t."interval_minutes")::integer as "interval_minutes",
  (t."lead_hours")::numeric(24,2) as "lead_hours",
  (t."clear_sky_poa_wm2")::numeric(24,2) as "clear_sky_poa_wm2",
  (t."forecast_poa_wm2")::numeric(24,2) as "forecast_poa_wm2",
  (t."cloud_cover_pct")::numeric(24,2) as "cloud_cover_pct",
  (t."ambient_temp_c")::numeric(24,2) as "ambient_temp_c",
  (t."wind_speed_ms")::numeric(24,2) as "wind_speed_ms",
  (t."soiling_pct")::numeric(24,2) as "soiling_pct",
  (t."availability_pct")::numeric(24,2) as "availability_pct",
  (t."curtailment_pct")::numeric(24,2) as "curtailment_pct",
  (t."asset_health_score")::integer as "asset_health_score",
  (t."clear_sky_ac_potential_mw")::numeric(24,4) as "clear_sky_ac_potential_mw",
  (t."weather_adjusted_physics_mw")::numeric(24,4) as "weather_adjusted_physics_mw",
  (t."after_availability_mw")::numeric(24,4) as "after_availability_mw",
  (t."after_curtailment_mw")::numeric(24,4) as "after_curtailment_mw",
  (t."after_asset_state_mw")::numeric(24,4) as "after_asset_state_mw",
  (t."ml_residual_pct")::numeric(24,4) as "ml_residual_pct",
  (t."ml_residual_correction_mw")::numeric(24,4) as "ml_residual_correction_mw",
  (t."forecast_delivered_mw")::numeric(24,4) as "forecast_delivered_mw",
  (t."uncertainty_pct")::numeric(24,3) as "uncertainty_pct",
  (t."forecast_lower_mw")::numeric(24,4) as "forecast_lower_mw",
  (t."forecast_upper_mw")::numeric(24,4) as "forecast_upper_mw",
  (j1.code)::varchar(200) as "model_id",
  (t."physics_model_version")::varchar(200) as "physics_model_version",
  (t."residual_model_version")::varchar(200) as "residual_model_version",
  (t."data_source")::varchar(200) as "data_source",
  (t."uncertainty_method")::varchar(200) as "uncertainty_method"
from aip."forecast_interval" t
left join aip."site" j0 on j0.id = t."site_id"
left join aip."ml_model" j1 on j1.id = t."model_id";
comment on view aip_compat."fcst_interval" is 'Workbook sheet "FCST_Interval" rebuilt from aip.forecast_interval';
grant select on aip_compat."fcst_interval" to authenticated, service_role;
drop view if exists aip_compat."fcst_actual";
create view aip_compat."fcst_actual" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (j0.code)::varchar(200) as "plant_id",
  (t."interval_start")::timestamp without time zone as "interval_start",
  (t."actual_ac_mw")::numeric(24,4) as "actual_ac_mw",
  (t."actual_energy_mwh")::numeric(24,4) as "actual_energy_mwh",
  (t."observed_poa_wm2")::numeric(24,2) as "observed_poa_wm2",
  (t."actual_availability_pct")::numeric(24,3) as "actual_availability_pct",
  (t."actual_curtailment_pct")::numeric(24,2) as "actual_curtailment_pct",
  (t."data_quality_status")::varchar(200) as "data_quality_status",
  (r0.label)::varchar(200) as "source_system",
  (t."source_mode")::varchar(200) as "source_mode"
from aip."plant_actual" t
left join aip."site" j0 on j0.id = t."site_id"
left join aip."ref_source_system" r0 on r0.id = t."source_system_id";
comment on view aip_compat."fcst_actual" is 'Workbook sheet "FCST_Actual" rebuilt from aip.plant_actual';
grant select on aip_compat."fcst_actual" to authenticated, service_role;
drop view if exists aip_compat."fcst_validation";
create view aip_compat."fcst_validation" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t."forecast_run_code")::varchar(200) as "forecast_run_id",
  (j0.code)::varchar(200) as "plant_id",
  (t."interval_start")::timestamp without time zone as "interval_start",
  (t."lead_hours")::numeric(24,2) as "lead_hours",
  (t."physics_forecast_mw")::numeric(24,4) as "physics_forecast_mw",
  (t."hybrid_forecast_mw")::numeric(24,4) as "hybrid_forecast_mw",
  (t."actual_mw")::numeric(24,4) as "actual_mw",
  (t."physics_error_mw")::numeric(24,4) as "physics_error_mw",
  (t."hybrid_error_mw")::numeric(24,4) as "hybrid_error_mw",
  (t."physics_abs_error_pct")::numeric(24,3) as "physics_abs_error_pct",
  (t."hybrid_abs_error_pct")::numeric(24,3) as "hybrid_abs_error_pct",
  (t."inside_80_pct_band")::varchar(200) as "inside_80_pct_band",
  (t."horizon_bucket_hours")::integer as "horizon_bucket_hours",
  (t."validation_mode")::varchar(200) as "validation_mode"
from aip."forecast_validation" t
left join aip."site" j0 on j0.id = t."site_id";
comment on view aip_compat."fcst_validation" is 'Workbook sheet "FCST_Validation" rebuilt from aip.forecast_validation';
grant select on aip_compat."fcst_validation" to authenticated, service_role;
drop view if exists aip_compat."reliability_life_history";
create view aip_compat."reliability_life_history" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t.code)::varchar(200) as "reliability_record_id",
  (t."asset_code")::varchar(200) as "asset_id",
  (t."asset_tag")::varchar(200) as "asset_tag",
  (j0.code)::varchar(200) as "plant_id",
  (r0.label)::varchar(200) as "asset_class",
  (r1.label)::varchar(200) as "failure_mode",
  (t."commissioned_date")::date as "commissioned_date",
  (t."observation_date")::date as "observation_date",
  (t."operating_hours")::numeric(24,2) as "operating_hours",
  (r2.label)::varchar(200) as "event_type",
  (t."failed_surviving")::varchar(200) as "failed_surviving",
  (t."right_censored")::varchar(200) as "right_censored",
  (t."replacement_reset")::varchar(200) as "replacement_reset",
  (t."evidence_source")::varchar(200) as "evidence_source",
  (t."source_mode")::varchar(200) as "source_mode",
  (t."data_quality_status")::varchar(200) as "data_quality_status",
  (j1.code)::varchar(200) as "group_id",
  (j2.code)::varchar(200) as "module_id",
  (t."observation_basis")::varchar(1000) as "observation_basis",
  (t."calendar_exposure_hours")::integer as "calendar_exposure_hours",
  (j3.code)::varchar(200) as "model_id",
  (t."batch_id")::varchar(200) as "batch_id",
  (t."evidence_reference")::varchar(200) as "evidence_reference",
  (t."failure_criterion")::varchar(200) as "failure_criterion",
  (t."data_basis")::varchar(200) as "data_basis"
from aip."life_observation" t
left join aip."site" j0 on j0.id = t."site_id"
left join aip."ref_asset_class" r0 on r0.id = t."asset_class_id"
left join aip."ref_failure_mode" r1 on r1.id = t."failure_mode_id"
left join aip."ref_event_type" r2 on r2.id = t."event_type_id"
left join aip."pv_module_group" j1 on j1.id = t."module_group_id"
left join aip."pv_module" j2 on j2.id = t."pv_module_id"
left join aip."equipment_model" j3 on j3.id = t."equipment_model_id";
comment on view aip_compat."reliability_life_history" is 'Workbook sheet "Reliability_Life_History" rebuilt from aip.life_observation';
grant select on aip_compat."reliability_life_history" to authenticated, service_role;
drop view if exists aip_compat."plan_resource_calendar";
create view aip_compat."plan_resource_calendar" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t.code)::varchar(200) as "resource_event_id",
  (t."resource_type")::varchar(200) as "resource_type",
  (t."resource_code")::varchar(200) as "resource_id",
  (j0.code)::varchar(200) as "plant_id",
  (t."start_at")::timestamp without time zone as "start",
  (t."end_at")::timestamp without time zone as "end",
  (r0.label)::varchar(200) as "event_type",
  (t."availability")::varchar(200) as "availability",
  (t."available_hours")::integer as "available_hours",
  (t."committed_hours")::integer as "committed_hours",
  (t."capacity_pct")::integer as "capacity_pct",
  (t."skill_or_certification")::varchar(200) as "skill_or_certification",
  (t."location")::varchar(200) as "location",
  (t."reason")::varchar(200) as "reason",
  (t."source_record")::varchar(200) as "source"
from aip."resource_event" t
left join aip."site" j0 on j0.id = t."site_id"
left join aip."ref_event_type" r0 on r0.id = t."event_type_id";
comment on view aip_compat."plan_resource_calendar" is 'Workbook sheet "PLAN_Resource_Calendar" rebuilt from aip.resource_event';
grant select on aip_compat."plan_resource_calendar" to authenticated, service_role;
drop view if exists aip_compat."plan_weather_forecast";
create view aip_compat."plan_weather_forecast" with (security_invoker = true) as
select t.tenant_id, t.code as row_key, t.source_ordinal,
  (t.code)::varchar(200) as "weather_id",
  (j0.code)::varchar(200) as "plant_id",
  (t."forecast_time")::timestamp without time zone as "forecast_time",
  (t."valid_from")::timestamp without time zone as "valid_from",
  (t."valid_to")::timestamp without time zone as "valid_to",
  (t."rain_probability_pct")::integer as "rain_probability_pct",
  (t."rainfall_mm")::numeric(24,2) as "rainfall_mm",
  (t."wind_kmh")::integer as "wind_kmh",
  (t."gust_kmh")::integer as "gust_kmh",
  (t."lightning_risk")::varchar(200) as "lightning_risk",
  (t."temperature_c")::integer as "temperature_c",
  (t."visibility_km")::integer as "visibility_km",
  (t."work_at_height_status")::varchar(200) as "work_at_height_status",
  (t."outdoor_electrical_status")::varchar(200) as "outdoor_electrical_status",
  (t."access_status")::varchar(200) as "access_status",
  (t."freshness_status")::varchar(200) as "freshness_status",
  (r0.label)::varchar(200) as "source_system",
  (t."source_mode")::varchar(200) as "source_mode",
  (t."evidence_id")::varchar(200) as "evidence_id"
from aip."site_weather" t
left join aip."site" j0 on j0.id = t."site_id"
left join aip."ref_source_system" r0 on r0.id = t."source_system_id";
comment on view aip_compat."plan_weather_forecast" is 'Workbook sheet "PLAN_Weather_Forecast" rebuilt from aip.site_weather';
grant select on aip_compat."plan_weather_forecast" to authenticated, service_role;
