-- Sustantix AIP · phase 5: change feed for live refresh
-- Generated by tools/schema from src/feed-sql.ts — do not edit by hand.

create or replace function aip.change_feed(p_tenant uuid, p_since timestamptz) returns jsonb
language plpgsql stable security definer set search_path = aip, pg_temp as $$
declare
  v_now timestamptz := clock_timestamp();
  v_items jsonb;
  v_count integer;
begin
  if not aip.has_role(p_tenant) then raise exception 'not a member of this tenant' using errcode = '42501'; end if;
  if p_since is null then return jsonb_build_object('cursor', v_now, 'items', '[]'::jsonb, 'truncated', false); end if;
  -- A page that slept for a day reloads rather than replaying a day of changes.
  if p_since < v_now - interval '1 day' then return jsonb_build_object('cursor', v_now, 'items', '[]'::jsonb, 'truncated', true); end if;
  select coalesce(jsonb_agg(x order by x->>'at', x->>'changeSet'), '[]'::jsonb), count(*) into v_items, v_count
  from (
    select jsonb_build_object('changeSet', c.id, 'entity', i->>'entity', 'code', i->>'code', 'op', i->>'op', 'at', c.applied_at) as x
    from aip.change_set c, jsonb_array_elements(c.result) i
    where c.tenant_id = p_tenant
      and c.applied_at > p_since - make_interval(secs => 120)
    order by c.applied_at, c.id
    limit 2001
  ) s;
  if v_count > 2000 then return jsonb_build_object('cursor', v_now, 'items', '[]'::jsonb, 'truncated', true); end if;
  return jsonb_build_object('cursor', v_now, 'items', v_items, 'truncated', false);
end $$;
revoke all on function aip.change_feed(uuid, timestamptz) from public, anon;
grant execute on function aip.change_feed(uuid, timestamptz) to authenticated;
