-- Sustantix AIP · phase 5: scheduled agent runs
-- Generated by tools/schema from src/schedule-sql.ts — do not edit by hand.

-- The next run after p_after: on the hour; daily at p_hour; weekly on p_weekday (0 = Sunday) at p_hour, all in p_tz.
create or replace function aip.next_agent_slot(p_cadence text, p_hour integer, p_weekday integer, p_tz text, p_after timestamptz)
returns timestamptz language plpgsql stable set search_path = aip, pg_temp as $$
declare
  t timestamp := p_after at time zone p_tz;
  c timestamp;
begin
  if p_cadence = 'hourly' then
    c := date_trunc('hour', t) + interval '1 hour';
  elsif p_cadence = 'daily' then
    c := date_trunc('day', t) + make_interval(hours => p_hour);
    if c <= t then c := c + interval '1 day'; end if;
  else
    c := date_trunc('day', t) + make_interval(days => (p_weekday - extract(dow from t)::integer + 7) % 7, hours => p_hour);
    if c <= t then c := c + interval '7 days'; end if;
  end if;
  return c at time zone p_tz;
end $$;

create table if not exists aip.agent_schedule (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references aip.tenants(id) on delete cascade,
  name text not null check (name ~ '^[A-Za-z0-9][A-Za-z0-9 ._-]{0,79}$'),
  agent text not null check (agent ~ '^[a-z][a-z0-9-]{1,60}$'),
  prompt text not null check (length(prompt) between 1 and 4000),
  cadence text not null check (cadence in ('hourly','daily','weekly')),
  at_hour smallint not null default 6 check (at_hour between 0 and 23),
  at_weekday smallint not null default 1 check (at_weekday between 0 and 6),
  time_zone text not null default 'UTC' check (length(time_zone) between 1 and 64),
  actor uuid not null references auth.users(id) on delete cascade,
  enabled boolean not null default true,
  next_run_at timestamptz not null default now(),
  last_run_at timestamptz,
  last_status text check (last_status in ('running','completed','failed','stopped')),
  last_run_id uuid,
  last_message text,
  created_by uuid,
  created_at timestamptz not null default now(),
  unique (tenant_id, name)
);
create index if not exists agent_schedule_due_idx on aip.agent_schedule(next_run_at) where enabled;
alter table aip.agent_schedule enable row level security;
drop policy if exists p_read on aip.agent_schedule;
create policy p_read on aip.agent_schedule for select to authenticated using (aip.has_role(tenant_id, array['admin']));
drop policy if exists p_update on aip.agent_schedule;
create policy p_update on aip.agent_schedule for update to authenticated using (aip.has_role(tenant_id, array['admin'])) with check (aip.has_role(tenant_id, array['admin']));
revoke all on aip.agent_schedule from authenticated;
-- Administrators see and adjust schedules; creating one (and its technical member) is a server action.
grant select (id, tenant_id, name, agent, prompt, cadence, at_hour, at_weekday, time_zone, enabled, next_run_at, last_run_at, last_status, last_run_id, last_message, created_by, created_at),
  update (prompt, cadence, at_hour, at_weekday, time_zone, enabled) on aip.agent_schedule to authenticated;
grant all on aip.agent_schedule to service_role;

-- A new or re-timed schedule (or one switched back on) runs at its next slot; an unknown time zone is refused.
create or replace function aip.agent_schedule_slot() returns trigger language plpgsql set search_path = aip, pg_temp as $$
begin
  if tg_op = 'INSERT' or new.cadence is distinct from old.cadence or new.at_hour is distinct from old.at_hour or new.at_weekday is distinct from old.at_weekday
     or new.time_zone is distinct from old.time_zone or (new.enabled and not old.enabled) then
    begin
      new.next_run_at := aip.next_agent_slot(new.cadence, new.at_hour, new.at_weekday, new.time_zone, now());
    exception when invalid_parameter_value then
      raise exception 'unknown time zone %', new.time_zone using errcode = '22023';
    end;
  end if;
  return new;
end $$;
drop trigger if exists t_slot on aip.agent_schedule;
create trigger t_slot before insert or update on aip.agent_schedule for each row execute function aip.agent_schedule_slot();
-- Audited when a schedule is created, changed or removed; the worker's run bookkeeping is recorded in agent_run instead.
create or replace function aip.audit_agent_schedule() returns trigger language plpgsql security definer set search_path = aip, pg_temp as $$
declare
  book constant text[] := array['next_run_at','last_run_at','last_status','last_run_id','last_message'];
begin
  if tg_op = 'UPDATE' and (to_jsonb(new) - book) = (to_jsonb(old) - book) then return new; end if;
  insert into aip.audit_log(tenant_id, actor, action, entity, entity_key, before, after)
  values (coalesce(new.tenant_id, old.tenant_id), auth.uid(), lower(tg_op), tg_table_name, coalesce(new.name, old.name),
          case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) - book end,
          case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) - book end);
  return coalesce(new, old);
end $$;
revoke all on function aip.audit_agent_schedule() from public, anon, authenticated;
drop trigger if exists t_audit on aip.agent_schedule;
create trigger t_audit after insert or update or delete on aip.agent_schedule for each row execute function aip.audit_agent_schedule();

drop view if exists aip.v_agent_schedule;
create view aip.v_agent_schedule with (security_invoker = true) as
select s.id::text as code, s.tenant_id, s.name, s.agent, s.cadence,
       case s.cadence when 'hourly' then 'every hour'
                      when 'daily' then 'daily at ' || lpad(s.at_hour::text, 2, '0') || ':00'
                      else 'weekly, ' || (array['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'])[s.at_weekday + 1] || ' at ' || lpad(s.at_hour::text, 2, '0') || ':00' end as runs,
       s.time_zone, s.enabled, s.next_run_at, s.last_run_at, s.last_status, s.last_message, s.prompt
from aip.agent_schedule s;
grant select on aip.v_agent_schedule to authenticated, service_role;

-- The worker claims one due schedule at a time and moves it to its next slot at once, so no slot runs twice.
create or replace function aip.claim_agent_schedule() returns setof aip.agent_schedule language plpgsql security definer set search_path = aip, pg_temp as $$
begin
  return query
  update aip.agent_schedule s
     set next_run_at = aip.next_agent_slot(s.cadence, s.at_hour, s.at_weekday, s.time_zone, greatest(now(), s.next_run_at)),
         last_run_at = now(), last_status = 'running', last_message = null
   where s.id = (select x.id from aip.agent_schedule x where x.enabled and x.next_run_at <= now() order by x.next_run_at, x.id limit 1 for update skip locked)
  returning s.*;
end $$;
revoke all on function aip.claim_agent_schedule() from public, anon, authenticated;
grant execute on function aip.claim_agent_schedule() to service_role;

create or replace function aip.finish_agent_schedule(p_id uuid, p_status text, p_run uuid, p_message text) returns void language plpgsql security definer set search_path = aip, pg_temp as $$
begin
  if p_status not in ('completed','failed','stopped') then raise exception 'bad status %', p_status using errcode = '22023'; end if;
  update aip.agent_schedule set last_status = p_status, last_run_id = p_run, last_message = left(p_message, 500) where id = p_id;
end $$;
revoke all on function aip.finish_agent_schedule(uuid, text, uuid, text) from public, anon, authenticated;
grant execute on function aip.finish_agent_schedule(uuid, text, uuid, text) to service_role;

-- An administrator runs schedules at the worker's next pass.
create or replace function aip.run_agent_schedules_now(p_tenant uuid, p_ids uuid[]) returns integer language plpgsql security definer set search_path = aip, pg_temp as $$
declare
  n integer;
begin
  if not aip.has_role(p_tenant, array['admin']) then raise exception 'only administrators run schedules' using errcode = '42501'; end if;
  update aip.agent_schedule set next_run_at = now() where tenant_id = p_tenant and id = any(p_ids) and enabled;
  get diagnostics n = row_count;
  return n;
end $$;
revoke all on function aip.run_agent_schedules_now(uuid, uuid[]) from public, anon;
grant execute on function aip.run_agent_schedules_now(uuid, uuid[]) to authenticated;
