-- Sustantix AIP · analytics results (model runs and outputs)
-- Generated by tools/schema — do not edit by hand.

create table if not exists aip.model_run (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references aip.tenants(id) on delete cascade,
  code text not null check (length(code) between 1 and 200),
  ml_model_id uuid not null,
  status text not null check (status in ('running','succeeded','skipped','failed')),
  as_of timestamp without time zone not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  params jsonb not null default '{}'::jsonb,
  metrics jsonb not null default '{}'::jsonb,
  message text,
  output_count integer not null default 0 check (output_count >= 0),
  triggered_by uuid,
  row_version bigint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, code),
  unique (tenant_id, id)
);
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'fk_model_run_ml_model_id') then
    alter table aip.model_run add constraint fk_model_run_ml_model_id foreign key (tenant_id, ml_model_id) references aip.ml_model (tenant_id, id);
  end if;
end $$;
create index if not exists model_run_model_idx on aip.model_run(tenant_id, ml_model_id, as_of desc);
alter table aip.model_run enable row level security;
drop policy if exists p_read on aip.model_run;
create policy p_read on aip.model_run for select to authenticated using (aip.has_role(tenant_id));
drop policy if exists p_write on aip.model_run;
create policy p_write on aip.model_run for all to authenticated
  using (aip.has_role(tenant_id, array['planner','admin'])) with check (aip.has_role(tenant_id, array['planner','admin']));
drop trigger if exists t_audit on aip.model_run;
create trigger t_audit after insert or update or delete on aip.model_run for each row execute function aip.audit_master_row();
drop trigger if exists t_touch on aip.model_run;
create trigger t_touch before update on aip.model_run for each row execute function aip.touch_versioned();

create table if not exists aip.model_output (
  id bigint generated always as identity primary key,
  tenant_id uuid not null references aip.tenants(id) on delete cascade,
  run_id uuid not null,
  subject_type text not null check (subject_type in ('site','asset','asset_class','part','part_stock','bess','portfolio')),
  subject_code text not null,
  measure text not null check (measure ~ '^[a-z][a-z0-9_]*$'),
  at timestamp without time zone,
  horizon_hours numeric(12,2),
  value numeric(24,6),
  q10 numeric(24,6),
  q50 numeric(24,6),
  q90 numeric(24,6),
  unit text not null,
  detail jsonb,
  created_at timestamptz not null default now(),
  constraint fk_model_output_run foreign key (tenant_id, run_id) references aip.model_run (tenant_id, id) on delete cascade,
  check (q10 is null or q50 is null or q10 <= q50),
  check (q50 is null or q90 is null or q50 <= q90)
);
create index if not exists model_output_run_idx on aip.model_output(tenant_id, run_id);
create index if not exists model_output_subject_idx on aip.model_output(tenant_id, measure, subject_code);
alter table aip.model_output enable row level security;
drop policy if exists p_read on aip.model_output;
create policy p_read on aip.model_output for select to authenticated using (aip.has_role(tenant_id));
-- Append-only: planners and administrators insert outputs; nobody updates them (a re-run is a new run).
drop policy if exists p_insert on aip.model_output;
create policy p_insert on aip.model_output for insert to authenticated with check (aip.has_role(tenant_id, array['planner','admin']));
drop policy if exists p_write on aip.model_output;

-- One audit entry per run batch instead of one per output row.
create or replace function aip.audit_output_batch() returns trigger language plpgsql security definer set search_path = aip, pg_temp as $$
begin
  insert into aip.audit_log(tenant_id, actor, action, entity, entity_key, after)
  select n.tenant_id, auth.uid(), 'insert', 'model_output', n.run_id::text, jsonb_build_object('rows', count(*), 'measures', jsonb_agg(distinct n.measure))
  from new_rows n group by n.tenant_id, n.run_id;
  return null;
end $$;
revoke all on function aip.audit_output_batch() from public, anon, authenticated;
drop trigger if exists t_audit on aip.model_output;
create trigger t_audit after insert on aip.model_output referencing new table as new_rows for each statement execute function aip.audit_output_batch();

grant select, insert, update, delete on aip.model_run to authenticated;
grant select, insert on aip.model_output to authenticated;
grant all on aip.model_run, aip.model_output to service_role;

-- Latest succeeded run per model, and its outputs with the model's code: what screens and agents read.
drop view if exists aip.v_model_output_latest;
drop view if exists aip.v_model_run_latest;
create view aip.v_model_run_latest with (security_invoker = true) as
select distinct on (r.tenant_id, r.ml_model_id) r.id, r.tenant_id, r.code, m.code as model, m.name as model_name, r.status, r.as_of, r.finished_at, r.metrics, r.output_count
from aip.model_run r join aip.ml_model m on m.id = r.ml_model_id
where r.status = 'succeeded'
order by r.tenant_id, r.ml_model_id, r.as_of desc, r.finished_at desc nulls last;
create view aip.v_model_output_latest with (security_invoker = true) as
select o.tenant_id, l.model, l.code as run, l.as_of, o.subject_type, o.subject_code, o.measure, o.at, o.horizon_hours, o.value, o.q10, o.q50, o.q90, o.unit, o.detail
from aip.model_output o join aip.v_model_run_latest l on l.id = o.run_id and l.tenant_id = o.tenant_id;
grant select on aip.v_model_run_latest, aip.v_model_output_latest to authenticated, service_role;
